### ISSUE TITLE
Nether Quartz Chicken

### ISSUE THREAD

**Issue by maethrya** [FTBTeam/FTB-Sky-Odyssey#100]
* **Issue**: I cant seem to get nether quartz chickens to spawn in the nether. I made a platform away from my portal, lit up to avoid aggressive spawns and covered, but they dont seem to be spawning. I am drowning in pigmen so its a spawnable platform(i keep killing them to make room for more spawns). From what I am seeing outside of this pack these chickens only spawn in fortresses. Is there a work around, or am I just stupid and doing this wrong?

**Comment by Jake-E** [comment]
Go find a fortress, they're available in the pack.
