### ISSUE TITLE
crashing bug between interacting with 2 mods

### ISSUE THREAD

**Issue by gamer112oj** [FTBTeam/FTB-Sky-Odyssey#101]
* **Modpack Version**: 1.0.0

* **Issue**: what happend when i try to speed up Energetic Infuser (basic) {whele there is a item} in with time in a bottle and after that the game
the game crashed

* **Link to Log or Crash File Paste**: https://pastebin.com/rej1AdPe

* **Is it Repeatable?**:  YES easyly

* **Mod/s Affected**: random things & thermal

* **Known Fix**: i dont know

**Comment by Rushmead** [comment]
Reported to the COFH Team

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 2013emi** [comment]
It's already been reported but thought I should mention that it has happened with all the thermal machines I've tried so far

**Comment by Slowpoke101** [comment]
Thanks, we will try to fix this at a later date.

**Comment by Naxanria** [comment]
This has been fixed in the update.
