### ISSUE TITLE
Quantum Solar Panel Crash

### ISSUE THREAD

**Issue by NisshoTatsu** [FTBTeam/FTB-Sky-Odyssey#102]
* **Modpack Version**: 1.0.0

* **Issue**: When placing down or breaking Quantum Solar Panels in Tech Reborn mod, the game freezes and then crashes. Have tested and the crash only happens when placing or breaking them. The crash doesn't happen every time you place or break one. Only some of the time. They have no issue at all if they are successfully placed on the ground.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4b5db5bb

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tech Reborn v2.21.2.960

* **Known Fix**: No known fix as of yet,

**Comment by VolcanoCookies** [comment]
This can also seem to happen spontaneously when near large amounts of panels, experienced with the tier right below quantum, cant remember the name.

Builder want make is crash more often, however large amounts of solar panels in general tend to make this crash happen, making the world unplayable until the panels are removed, for example using MCEdit.
