### ISSUE TITLE
[Bug] Transmutation Table

### ISSUE THREAD

**Issue by JankoGoo** [FTBTeam/FTB-Sky-Odyssey#103]
* **Modpack Version**: 1.0.0

* **Issue**: Crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3451db15

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: The game itself

* **Known Fix**: It happens, when the transmutation table shows duplicated items

**Comment by JankoGoo** [comment]
I was crafting stuff with these cards along the "Hyper speed upgrade" (<Add the mod there).

After like 2 or 3 items of making the table lerning the items I crafted it showed every item twice, until out of a sudden... Crash.

**Comment by impucky** [comment]
Same thing happened to me after placing items from Matter Overdrive into a transmutation table (table showing duplicate items, shortly followed by a crash).

Crash Log:
[https://pastebin.com/raw/gfzBWCun](https://pastebin.com/raw/gfzBWCun)

**Comment by LatvianModder** [comment]
This is a Matter Overdrive bug, but I think this may have been fixed already

**Comment by JankoGoo** [comment]
I'll see, when the patch launches.

Thanks for letting me know.
