### ISSUE TITLE
Too much EMC to deposit more

### ISSUE THREAD

**Issue by Zickzii** [FTBTeam/FTB-Sky-Odyssey#104]
* **Modpack Version**: 1.0.0

* **Issue**: I have so much EMC I can't put any more into my transmutation table, I can work around it by inputting through personal EMC links.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yeah.

* **Mod/s Affected**: ProjectE

* **Known Fix**: Input into personal EMC Links instead of Transmutation Tables/Tablets

**Comment by MrNovaz** [comment]
So putting items into the Personal EMC Links dont teach the table the items your crafting, what i would recommend and what i have personally done is take out 64 "The Final Power Flower Bonsai Pot" take as many of those out as you can and store em somewhere else and that free's up alot of EMC and allows you to teach new things to the table.

**Comment by TheOfficialButton** [comment]
This is an issue that cannot be fixed as Java can only read up to 9.4 quintillion. If you still want to learn items in your table, put them in the middle on the right side instead of burning them into it :)
