### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by Havoc1001** [FTBTeam/FTB-Sky-Odyssey#106]
I downloaded the Server pack from the website, and uploaded them to my server, when starting, it fails to load, and says Missing core lib files. Any fix for this?

Thanks

**Comment by Havoc1001** [comment]
20.03 17:48:39 [Multicraft] Loading server properties
20.03 17:48:39 [Multicraft] Starting server!
20.03 17:48:39 [Multicraft] Loaded config for "@ Custom Jar (Recommended) (Place "custom.jar" in base directory)"
20.03 17:48:39 [Multicraft] Updating eula.txt file
20.03 17:48:39 [Server] INFO We appear to be missing one or more essential library files.
20.03 17:48:39 [Server] INFO You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
20.03 17:48:39 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
20.03 17:48:39 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
20.03 17:48:39 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
20.03 17:48:39 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
20.03 17:48:39 [Server] INFO at java.lang.Class.forName0(Native Method)
20.03 17:48:39 [Server] INFO at java.lang.Class.forName(Class.java:348)
20.03 17:48:39 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
20.03 17:48:39 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
20.03 17:48:39 [Multicraft] Server shut down (starting)
20.03 17:48:39 [Multicraft] Restarting crashed server in 10 seconds
20.03 17:48:39 [Multicraft] Looks like a crash, check the server console. Return value: 1
20.03 17:48:39 [Multicraft] Server stopped
20.03 17:48:42 [Multicraft] Received stop command
20.03 17:48:42 [Multicraft] Server stopped

**Comment by DinnerBeef** [comment]
I would say try and reinstall forge on the server and see what happens.

**Comment by Havoc1001** [comment]
This is the only pack that is doing this. I had stoneblock on first, and everything worked just fine. I will try installing forge first. Thanks

**Comment by Havoc1001** [comment]
Thanks for your help that did work. The Forge files in the server download are broken, or mission files,
