### ISSUE TITLE
Liquifacted Coal can't be replicated

### ISSUE THREAD

**Issue by ClassixX** [FTBTeam/FTB-Sky-Odyssey#107]
* **Modpack Version**: 1.0.0

* **Issue**: The Tech Reborn Fluid Replicator is supposed to be able to replicate Liquifacted Coal, but this is impossible, because the Replicator needs to have a source block of the Fluid is replicates placed inside it's multiblock. This is impossible to do with Liquifacted Coal, since it cannot be placed down.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Foundation, Tech Reborn

**Comment by Slowpoke101** [comment]
Working as intended. this would need to go to mod developers for a possible change.
