### ISSUE TITLE
Game crashes after placing 64 flux plugs with a wand

### ISSUE THREAD

**Issue by canguscaan** [FTBTeam/FTB-Sky-Odyssey#109]
* **Modpack Version**: 1.0.0

* **Issue**: Was placing flux plugs with a diamond builders wand, with ultimate solar panels on top. Half way through, screen goes blue-grey and then crashes

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/62e36031
* **Is it Repeatable?**: Yes

**Comment by Naxanria** [comment]
Seems like the same crash as in https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/102
This seems like a Tech Reborn/Better Builder Wands
