### ISSUE TITLE
Mob grinding utils allows cheesing spawn egg quests

### ISSUE THREAD

**Issue by impucky** [FTBTeam/FTB-Sky-Odyssey#111]
* **Modpack Version**: 1.0.0
* **Issue**: 
With mob grinding utils it is possible to create spawn eggs (Mob Swab, crafted with seeds and a bucket of xp makes GM Chicken Feed, creating the egg when fed to a chicken).     
This completely trivializes most if not all of the spawn egg quests, as you only need to find one of the target mob.

* **Mod/s Affected**: mob_grinding_utils

* **Known Fix**: The mob doesn't seem to have a config file, so I guess removing the Mob Swab recipe works. 
It may be possible to remove individual GM Feed recipes with CraftTweaker (to still allow for non-quest eggs to be made) but I couldn't figure it out.

**Comment by Slowpoke101** [comment]
Fixed in dev
