### ISSUE TITLE
Disable the /rtp command

### ISSUE THREAD

**Issue by Bluev0** [FTBTeam/FTB-Sky-Odyssey#112]
* **Modpack Version**: 1.0.0
* **Issue**:

/rtp causes the server to do an almost infinite loop for searching save teleport spots while generating thousands of empty .mca files.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ece7394c

* **Is it Repeatable?**: yes. just do /rtp

* **Mod/s Affected**: FTB Utilities v5.4.0.87

* **Known Fix**: Disable the rtp command in the config

**Comment by Jake-E** [comment]
This shouldn't need to be disabled. This should be fixed in the mod.

**Comment by Slowpoke101** [comment]
Fixed in Dev
