### ISSUE TITLE
Cyanite and Blutonium chickens not working correctly.

### ISSUE THREAD

**Issue by Unratedpupet** [FTBTeam/FTB-Sky-Odyssey#113]
* **Modpack Version**: 1.0.0

* **Issue**: Cyanite Chicken when... hatching?... in the Roost, it gives off the non-textured pink/black. However, the tooltip shows it as "Cyanite Ingot" from "Extreme Reactors". I was unable to use that item in crafting. Unable to put the items in a drawer with when it has cyanite ingots from crafting locked in. Same issue with Blutonium chickens.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Roost

* **Known Fix**:

**Comment by Slowpoke101** [comment]
Fixed in dev, thanks for letting us know.

**Comment by Kingnocraft** [comment]
The problem back in version 1.2.0
