### ISSUE TITLE
Beast Coin market (RF per coin) doesn't reset when buying items

### ISSUE THREAD

**Issue by KaraNoelle** [FTBTeam/FTB-Sky-Odyssey#114]
* **Modpack Version**: 1.0.0

* **Issue**: Title. Had 300K+ BC and bought a creative flux capacitor for 250k. Each BC costs me 36M RF to make. Buying the item did not lower the cost per coin. Played on server.

**Comment by applemes** [comment]
Same, mines taking 17M right now, after i got the watch

**Comment by DinnerBeef** [comment]
I just want to kmow where you got the idea that the miner resets when you by something. The mimer does NOT RESET.

**Comment by TheOfficialButton** [comment]
The miner does not reset after purchasing something from the shop. The coin generation is continuous.
