### ISSUE TITLE
MPUtils Incorrect issue tracker

### ISSUE THREAD

**Issue by GenDeathrow** [FTBTeam/FTB-Sky-Odyssey#115]
* **Modpack Version**: 1.0.0

* **Issue**:  I think the mputils link to the issue tracker is going to the default. Had a few bug reports today and Im now directing them to come here. 

* **Known Fix**:     Change  the 'config/mputils/addon/mpbasic.cfg' -> S:"Issue Tracker url" to your url.

**Comment by Slowpoke101** [comment]
Thanks, this should be fixed on the next release.
