### ISSUE TITLE
game not downloading

### ISSUE THREAD

**Issue by doopee** [FTBTeam/FTB-Sky-Odyssey#117]
First and only version right now

Issue modpack doesnt download just instantly tells me to click play then when i try download from versions it gives me 
Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip

crash file none

Is it Repeatable? yes

Known Fix none

**Comment by Keaton1188** [comment]
Why are you trying to download the .zip files? or is that just where its timing out? 

You could just use the Twitch launcher or FTB Legacy launcher and download the pack from there, would be a lot easier?

**Comment by Jake-E** [comment]
Try the FTB Launcher. We will be pushing a version without the animation files to make extraction easier soon.
