### ISSUE TITLE
Creative Jetpack

### ISSUE THREAD

**Issue by Adam022695** [FTBTeam/FTB-Sky-Odyssey#118]
* **Modpack Version**: 1.0.0

* **Issue**: The creative jetpack gathers RF from the flux network until it states that the jetpack is depleted and it can no longer be used

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes I've done so twice it just takes a little while. Equip a creative jetpack with a flux network charging items. The pack will take energy from the system until it states that the jetpack RF is depleted even though its infinate

* **Mod/s Affected**: Flux Networks and simply jetpacks 2

* **Known Fix**:

**Comment by Jake-E** [comment]
Have you reported this to the mod authors? This isn't something we can fix without a mod update.

**Comment by Excederus** [comment]
I have the same issue. I enabled Wireless charging with my Flux Network and my Creative Jetpack became depleted.

**Comment by TheRealPaulioliolio** [comment]
I also have the same issue, its exactly as stated by the other users for me as well. I'm trying to find out if disabling the Wireless Charging will allow the jetpack to return to it's normal state.

**Comment by Lost-Ninja** [comment]
Same issue, wireless charging (via Flux Networks) is off.

Is there a way to refund the beast coins?
