### ISSUE TITLE
IE Conveyor Belts become useless in transmutation table

### ISSUE THREAD

**Issue by 3lementalS** [FTBTeam/FTB-Sky-Odyssey#119]
* **Modpack Version**: 1.0.0

* **Issue**: Storing a conveyor belt (Of any kind) in the transmutation table renders it useless

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectE-1.12.2-PE1.4.0, ImmersiveEngineering-0.12-89

* **Known Fix**:

![2019-03-20_17 30 44](https://user-images.githubusercontent.com/22643112/54727698-6a955700-4b36-11e9-9eb1-6463bc0a7050.png)
![2019-03-20_17 31 14](https://user-images.githubusercontent.com/22643112/54727699-6a955700-4b36-11e9-809f-3c8cd4a65704.png)

**Comment by TheOfficialButton** [comment]
This has been a mod issue for a long time and is known by the mod dev. For now you will have to make all the conveyor belts manually or use vector plates.
