### ISSUE TITLE
Breaking Task Screens do not drop themselves.

### ISSUE THREAD

**Issue by madun1999** [FTBTeam/FTB-Sky-Odyssey#120]
* **Modpack Version**: 1.0.0

* **Issue**: Breaking Task Screens using pickaxes do not drop Task Screens. 
Also, there is no recipe for Task Screens larger than 3x3. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: FTB Quests

**Comment by DinnerBeef** [comment]
Yea the screens are made to not drop blocks. Also not having bigger screens is for lag reasons.

**Comment by TheOfficialButton** [comment]
This is intended. Task screens are not supposed to drop blocks which is why they are so easy to craft.
