### ISSUE TITLE
No EMC value for glass panes

### ISSUE THREAD

**Issue by Etheria137** [FTBTeam/FTB-Sky-Odyssey#121]
* **Modpack Version**: 1.0.0

* **Issue**: I don't know if this is a bug or intentional, but glass panes don't have an emc value but glass does. 

* **Is it Repeatable?**: yes

* **Mod/s Affected**:     ProjectE-1.12.2-PE1.4.0.jar

* **Known Fix**:

**Comment by TheOfficialButton** [comment]
Glass panes are intended to not have an EMC value. This is a default EMC value in the mod.
