### ISSUE TITLE
Final collector quest bug

### ISSUE THREAD

**Issue by sanswitch1** [FTBTeam/FTB-Sky-Odyssey#126]
* **Modpack Version**: 1.0.0

* **Issue**: The basic collector and relay completed the quests for the final collector and relay when crafted.

* **Is it Repeatable?**: Yes, as you need to craft the energy collector and anti relay first and then craft them into the other version.

**Comment by Jake-E** [comment]
Fixed. See #40

**Comment by Jake-E** [comment]
Fixed. See #40
