### ISSUE TITLE
Addition/query

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Sky-Odyssey#130]
Not a bug.
Is there a way to admin pay a player beast coins, should something happen and they lose them. 
Any help would be appreciated.
I'm aware of the /pay command however that uses the players money to transfer to another player.

**Comment by Rushmead** [comment]
There is a /setmoney command: 

> /setmoney <player> <amount>

**Comment by nzminecraftDOTcom** [comment]
Darn, thanks for the help. Was hoping there would be one to add to their current balance rather than wipe it all together and start from whatever you set it.
