### ISSUE TITLE
Sky Odyssey isn't working as intended

### ISSUE THREAD

**Issue by Duffa1337** [FTBTeam/FTB-Sky-Odyssey#131]
FTBSkyOdyssey-1.0.0-1.12.2
forge-14.23.5.2815 - FTB Sky Odyssey
Twitch launcher

The issue is that my map has been completely deleted from my directory and there are no map templates - meaning that they 'Skyblock' part of the modpack isn't working. All I'm able to do is spawn into a vanilla world. The intro-screen also doesn't play the credits it used to, nor is the UI the way it was, as it's now the standard 'Minecraft Java version' splash. Beastcoin is also not working as there are no items in the shop available to see.

No crash file details as it isn't a crash.

The issue is consistently repeatable as the modpack isn't fully set.

I'm not sure if any modpacks are causing this issue.

Image of the version:
![launch-screen with version](https://user-images.githubusercontent.com/48791851/54747631-8a567900-4c23-11e9-8bce-fbc51015b1ee.PNG)

Lacking start-screen and FTB logo:
![Not FTB](https://user-images.githubusercontent.com/48791851/54747676-a9eda180-4c23-11e9-8e3b-a74b3a

Main menu:
![Mainscreen](https://user-images.githubusercontent.com/48791851/54748199-1321e480-4c25-11e9-9f62-501fd1ce807f.PNG)
66770e.PNG)

No templates availble:
![No templates](https://user-images.githubusercontent.com/48791851/54748209-1ae18900-4c25-11e9-9e6f-84e27f0576ac.PNG)

No island map; vanilla map:
![Vanilla map](https://user-images.githubusercontent.com/48791851/54748254-32207680-4c25-11e9-8b5d-73244e07d32a.png)

**Comment by DinnerBeef** [comment]
Try and redownload the pack

**Comment by Duffa1337** [comment]
> Try and redownload the pack

I did try repairing the pack with Twitch launcher but I am trying it out with the legacy launcher as I'm typing this

**Comment by Jake-E** [comment]
This seems like an installation issue. If you aren't fully downloading the configs the modpack won't work as intended.
