### ISSUE TITLE
Stabilized Spawner quest not completing

### ISSUE THREAD

**Issue by Petrel63** [FTBTeam/FTB-Sky-Odyssey#132]
I tried to complete the Stabilized spawner questby right clicking with a core or crafting a broken spawner with a core both neither worked

* **Modpack Version**: 1.0.0

* **Issue**: 

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Jake-E** [comment]
This needs the damage/nbt settings changed to work.

**Comment by Slowpoke101** [comment]
Fixed in Dev

**Comment by Sugarman96** [comment]
I'm also having this problem with the stabilized spawner and the Woot factory controller. What's the fix?

**Comment by DerDerARKmag** [comment]
how to get a broken spawner
