### ISSUE TITLE
Extra Utilities 2 Voided Items

### ISSUE THREAD

**Issue by BrainInBlack** [FTBTeam/FTB-Sky-Odyssey#134]
* **Modpack Version**: 1.0.0

* **Issue**: Extra Utilities 2 has a known bug in versions 1.9.9 and 1.9.8, where items get voided in the GUI's (regardless of which machine).

* **Is it Repeatable?**: The issue is repeatable with pretty much any machine.

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: Downgrade Extra Utilities to version 1.9.7

https://github.com/rwtema/Extra-Utilities-2-Source/issues/226

**Comment by Jake-E** [comment]
I presume the known issue is 1.9.9 and 1.9.8 - not 1.9.7 as this is the proposed fix?
Please confirm.

**Comment by BrainInBlack** [comment]
Yes, the issue does not happen with 1.9.7 and below.

**Comment by BrainInBlack** [comment]
The issue was reported to Tema in the following issues:

https://github.com/rwtema/Extra-Utilities-2-Source/issues/235
https://github.com/rwtema/Extra-Utilities-2-Source/issues/257
https://github.com/NillerMedDild/Enigmatica2/issues/232

Apparently the issue is around since version 1.9.6, so my "fix" probably won't work anyways. And as Slow said on stream, the current version fixes a nasty bug. So we have to wait for Tema to fix it.

**Comment by Slowpoke101** [comment]
We cant roll this mod back due to it re-introducing an even worse bug that causes the game to crash.
