### ISSUE TITLE
Stoneburnt Chicken cant be crafted

### ISSUE THREAD

**Issue by Mack3sh** [FTBTeam/FTB-Sky-Odyssey#135]
* **Modpack Version**: 1.0.0

* **Issue**: Stoneburnt Chicken cant be crafted, the normal chicken is not recognized

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities 2, More Chickens, Chickens, Roost, CraftTweaker2

**Comment by Slowpoke101** [comment]
You can craft the egg which is used to spawn the chicken.

**Comment by Mack3sh** [comment]
no its not possible the recipe dosent work, the normal chicken is not recognized, although it is there
