### ISSUE TITLE
missing quest items

### ISSUE THREAD

**Issue by setanator** [FTBTeam/FTB-Sky-Odyssey#136]
* **Modpack Version**: 1.0.0 

* **Issue**: In the introduction tab the coal generator and furnace quests do not have the ender io version of the machines but the sag mill does  

* **Is it Repeatable?**:  yes
* **Mod/s Affected**: questing mod

* **Known Fix**: the simple Stirling generator gets added to the coal generator quest , simple furnace into the furnace quest

**Comment by Slowpoke101** [comment]
Thanks this is fixed in dev
