### ISSUE TITLE
Beast coin miner in -

### ISSUE THREAD

**Issue by KillerKana** [FTBTeam/FTB-Sky-Odyssey#139]
Version 1.0.0

Connecting flux point with power to beast coin miner seems to send beast coin miners energy into -

https://paste.feed-the-beast.com/view/ad963680
connecting flux point to beast coin miner seems to do it every time so far yeah, not instant but over time

**Comment by Jake-E** [comment]
No, it doesn't. Hover over the power inside of the machine.

**Comment by Naxanria** [comment]
The number is going to be bigger than what the tooltip can show, so it shows negative. Inside the beastcoin miner it will be showing correctly :)

**Comment by KillerKana** [comment]
you mean that red bar inside the miner? it moves up and down as it wishes whatever i have power connected or not

**Comment by DinnerBeef** [comment]
the miner hold near unlimited amount of power

**Comment by KillerKana** [comment]
mm okay
