### ISSUE TITLE
Chosen Architect's island start issue

### ISSUE THREAD

**Issue by mgrimm21** [FTBTeam/FTB-Sky-Odyssey#14]
Since you only start with dark oak saplings, you can't start playing the pack due to the first quest requiring regular oak saplings and logs only.

**Comment by Naxanria** [comment]
You can, as there is a shop. The shop has other saplings as well.
You can complete other quests with wood to get started :)

**Comment by Alfurin** [comment]
I can even seem to get the dark oak to grow by twerking.
