### ISSUE TITLE
Turning 1EMC into 8 kEMC

### ISSUE THREAD

**Issue by TomiPomi** [FTBTeam/FTB-Sky-Odyssey#140]
Modpack Version: 1.0.0

Issue: So the Problem is, you can turn one dirt into a Akashic Tome, which is completly fine, but then you can use the Tome to acces the Draconic Information Tablet, which than can be turned into 8 kEMC.
And I guess its not supossed to work that way.

**Comment by Naxanria** [comment]
This is not a problem, as the amounts of emc are way to large to make real use of this.

**Comment by TomiPomi** [comment]
Well, I just started playing the modpack, and having 250 000 EMC at the beginging ist really op. turning a dirt with 1EMC into something with 8000EMC is I think considered OP

**Comment by Naxanria** [comment]
Nah,  just less grindy start :)

**Comment by TheOfficialButton** [comment]
This doesn't make a big difference as there is so much EMC generated pretty quickly in the pack.
