### ISSUE TITLE
can't build Chrome Chicken

### ISSUE THREAD

**Issue by Wumpsi** [FTBTeam/FTB-Sky-Odyssey#141]
* **Modpack Version**: 1.0.0

* **Issue**: all recepis for the Chrome Chicken needs Chrome.
There is no Chrome buyable.

**Comment by 2013emi** [comment]
You have to make chrome dust and then put that in the blast furnace. It doesn't come from an ore.

**Comment by TheOfficialButton** [comment]
Chrome is not an ore and can only be obtained through smelting the dust.
