### ISSUE TITLE
Transformer Upgrade Quest

### ISSUE THREAD

**Issue by kalanihelekunihi** [FTBTeam/FTB-Sky-Odyssey#142]
* **Modpack Version**: 1.0.0

* **Issue**: The Transformer Upgrade quest is to craft an IndustrialCraft 2 item, however the recipe crafts a Tech Reborn version. This prevents the quest from completing.

* **Link to Log or Crash File Paste**: Not applicable

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IndustrialCraft 2 / Tech Reborn crafting conflict

* **Known Fix**: Unknown

**Comment by Slowpoke101** [comment]
Can you confirm that you are using the 2xinsulated cable in your recipe rather than the normal insulated cable. We are not able to reproduce this.

**Comment by kalanihelekunihi** [comment]
You're right. My mistake.
