### ISSUE TITLE
Is it possible to get the Transmutation Chamber mod added to the pack?

### ISSUE THREAD

**Issue by sLpFhaWK** [FTBTeam/FTB-Sky-Odyssey#145]
* **Modpack Version**: 1

* **Issue**: The way EMC is used in the ME system could be optimized, was wondering if the Transmutation Chamber, the Soulbound Talisman, Alchemical Algorithm and the Efficiency Catalyst from the mods Equivalent Integrations could be added. The pack motif is EMC based heavily, and the way to import items from EMC into the ME system now is very flawed using the EMC links as you have to teach it every item you want. It's a very long and drawn out process as seen in Chosens playlist episode 8.

A quick video description can be found here is how I learned about the addon, and it was very VERY helpful in my playthrough of Project ozone 3. 

https://www.twitch.tv/matrixis/clip/WiseObliviousRutabagaThisIsSparta  

* **Link to Log or Crash File Paste**: None needed

* **Is it Repeatable?**: Yes, everytime you want to teach your EMC Table a new item you need to teach it to an EMC link on an import bus in your ME system. 

* **Mod/s Affected**:  AE2 could be improved with the addon Equivalent Integrations.

* **Known Fix**: Add the addon? =)

This is merely a suggestion. It would definitely improve the pack tremendously. I am having fun playing it but when it comes time for my AE2 ME system this part I am dreading.

**Comment by Slowpoke101** [comment]
We did try this mod in the pack originally, unfortunately, we had to remove the mod due to performance issues at the time. However if you are playing single player, you are totally free to add the mod yourself.
