### ISSUE TITLE
Refined Storage/EMC Link deleting items

### ISSUE THREAD

**Issue by Petrel63** [FTBTeam/FTB-Sky-Odyssey#146]
I have an Compressed EMC link attached to an RS system where the RS disks and the EMC
are at the same priority. When I put an item in the RS grid that hasn't been scanned for EMC
then the item is deleted.

If you then scan another of that item and insert it into the grid then it is put into the RS disks as
expected.

If you set the EMC link(s) to be a lower priority than the RS disks then the item gets put into the RS disks whether it has been scanned before or not.

I hope the above is clear but I will attempt to supply extra info if you need clarification.

* **Modpack Version**: 1.0.0

* **Issue**: 

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: projecte, projectex and refined storage

* **Known Fix**: see above for in-game work around

**Comment by DinnerBeef** [comment]
Set the priority of the disk drives higer than emc links

**Comment by Petrel63** [comment]
With all due respect I said that in my description of the problem.

BUT items should NOT be deleted if you get the priorities wrong

**Comment by Petrel63** [comment]
With all due respect I said that in my description of the problem.

BUT items should NOT be deleted if you get the priorities wrong

(Sorry if this is repeating myself, but I didn't know how to re-open the issue)

**Comment by Naxanria** [comment]
You put items in your emc link that has emc, they get turned into emc.
This is intended behaviour. Maybe change the storage buses to only extract?

**Comment by Slowpoke101** [comment]
Hey Petrel as has already been asked can you just confirm that the item is being deleted and not just added to EMC. Everything you are saying in the original post indicates the mod is working as intended.

**Comment by IamStig** [comment]
I think it is all working as intended. Basically if you, for instance, set up a mob farm/loot opener and exported all items into a Personal EMC, the EMC would get added to your EMC total BUT the Personal EMC is not intended to "Learn" items so you can't pull out any item that has been added to your EMC that way. Putting items into your RS system and setting it up so that items go into a Personal EMC as priority over the drives is doing the same thing bypassing "Learning" the item.

**Comment by bruhzinga** [comment]
> I think it is all working as intended. Basically if you, for instance, set up a mob farm/loot opener and exported all items into a Personal EMC, the EMC would get added to your EMC total BUT the Personal EMC is not intended to "Learn" items so you can't pull out any item that has been added to your EMC that way. Putting items into your RS system and setting it up so that items go into a Personal EMC as priority over the drives is doing the same thing bypassing "Learning" the item.
 
Sorry for late posting but am i getting this correctly?Does this mean there is no way to automate learning something with EMC?thx in advance

**Comment by IamStig** [comment]
That's right learning is manual only. Input of items, for EMC, can be automated but any item that goes in that way that hasn't been previously learned can not be taken out.
