### ISSUE TITLE
Noob Error

### ISSUE THREAD

**Issue by veenjain** [FTBTeam/FTB-Sky-Odyssey#147]
Hey im kinda new to this but i accidentally used a torch on my lava so now i dont have it anymore or any obsidian in my table or in the world. Can you shwo me hot to get into gamemode to spawn it in or another way i can get it back? Thank you

**Comment by sLpFhaWK** [comment]
This isn't what this medium is for, but if you CTRL Right click on the wrench in JEI it'll turn red, you can then search for the item you want and right click to spawn 1 item, or left click to spawn a stack.

You can also left click on the wrench and in the sub menu turn cheats on then click done for the same results.

You will need to be /op if you're playing on a server if you're playing single player you needed to create the world with cheats on i think to accomplish this.

**Comment by veenjain** [comment]
> This isn't what this medium is for, but if you CTRL Right click on the wrench in JEI it'll turn red, you can then search for the item you want and right click to spawn 1 item, or left click to spawn a stack.
> 
> You can also left click on the wrench and in the sub menu turn cheats on then click done for the same results.
> 
> You will need to be /op if you're playing on a server if you're playing single player you needed to create the world with cheats on i think to accomplish this.

Sorry i didnt know where to ask. Thank you anwyays
