### ISSUE TITLE
EMC table bug?

### ISSUE THREAD

**Issue by h03ga4rd3n** [FTBTeam/FTB-Sky-Odyssey#148]
Modpack version: 1.0.0

Issue: well i was farming EMC and when i reach exactly 9.25 E my table do not accept items, i can't throw anything in there, is this a bug or a thing in the pack?

**Comment by h03ga4rd3n** [comment]
i tried restarting the game and now my EMC table doesn't know some items :/, well i guess that i have to re do like 4 hours of playthrough

**Comment by DinnerBeef** [comment]
Same as #104. Use the stone tablet from now so that you can still put stuff inside you emc network.

**Comment by Slowpoke101** [comment]
Not sure if we are going to be able to fix this yet, but are looking into it.

**Comment by Slowpoke101** [comment]
You can resolve this by removing a bunch of EMC from the table. Final Stars are your best bet. In addition, you can start to use the new Stone Transmutation Table as an alternative that does not have this issue.
