### ISSUE TITLE
Create from template does not shows.

### ISSUE THREAD

**Issue by yairs135** [FTBTeam/FTB-Sky-Odyssey#149]
* **Modpack Version**: 1.0.0

* **Issue**: When I open the singal player option the option to create a world from template does not appear and I can't create the modpack's world.

* **Link to Log or Crash File Paste**: Don't have

* **Is it Repeatable?**:Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by DinnerBeef** [comment]
redownload the pack

**Comment by yairs135** [comment]
Tried and didn't work...

**Comment by Slowpoke101** [comment]
I have no idea how to troubleshoot this, can you open up the directory that you downloaded and see if there is a maps folder present in the main directory and inside the maps folder there are different worlds inside.

**Comment by BocoClacko** [comment]
Same issue, re-download solved it for me first try though...

**Comment by yairs135** [comment]
I already checked out for the maps folder and I have it with few worlds inside, but when I want to create a world I don't have the button **"Create From Template"**... Do you have any idea what is the mod that adds that ao I can download it manually?

**Comment by Slowpoke101** [comment]
Hardcore Map Reset is the mod that provides Create From Template.

**Comment by yairs135** [comment]
OK. I downloaded it and deleted the one that I had in the mods folder and that fixed the problem.
thx for helping
