### ISSUE TITLE
Crook

### ISSUE THREAD

**Issue by applemes** [FTBTeam/FTB-Sky-Odyssey#15]
I can't make a crook for some reason

**Comment by Alfurin** [comment]
Dont think its in the pack.

**Comment by Naxanria** [comment]
There is no crook in the pack, as there is no ex-nihilo.
You can vein-mine the leaves (default key: grave)

**Comment by Slowpoke101** [comment]
Confirmed no ex nihilism in the pack.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
