### ISSUE TITLE
[Bug] Tech reborn: Auto Crafting Table breaking recipes

### ISSUE THREAD

**Issue by mesbozi** [FTBTeam/FTB-Sky-Odyssey#150]
**FTBSkyOdyssey-1.0.0-1.12.2.zip - (Release)**

I was trying to use the Auto Crafting Table from Tech reborn to auto craft inferium essence into prudentium essence using the master infustion crystal. The first time the table crafted the prudentium it was outputted as expected however the master infusion crystal disappeared. I can now no longer use either infusion crystal to craft prudentium essence and I am completely locked out of mystical aggriculture. The recipe still shows up in JEI however the next tier essence isn't available to craft from anywhere. Through testing i have found that the bug doesnt happen if you lock the table from crafting first, if you dont and it starts crafting as soon as the last item is put in then, when finished, the recipe will be broken

The issue is repeatable and I have found that the bug is 100% with the Auto Crafting Table because it did the same thing with diamonds into diamond blocks. I loaded up another world to test in and all previous bugged recipes were still bugged in other worlds.

**Mod causing the issue:** Tech Reborn version 2.21.2.960

A simple restart of the pack will fix all broken recipes

**Comment by Slowpoke101** [comment]
Sent to Modmuss to check this out

**Comment by modmuss50** [comment]
Already fixed, https://github.com/TechReborn/TechReborn/commit/0ca18ade97b02499d8567398ad0579226d46b1c7 just need to release the update.
