### ISSUE TITLE
ChosenArchitect map start

### ISSUE THREAD

**Issue by areathena** [FTBTeam/FTB-Sky-Odyssey#152]
* **Modpack Version**: 

Updated: 3/20/2019

Played: 2 days ago

Version: 1.0.0

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2815

* **Issue**: question did you mean to not give lava, water, and oak saplings at the start of the ChosenArchitect map. the first wood quest only takes normal oak and in the chest is only dark oak.  i also spent a bit of time trying to get lava or Obsidian and could not find a way to get one with out the other.

**Comment by ThePoet444** [comment]
Vulcan amulet, a bucket, and redstone in a crafting grid gets a bucket of lava. 2 lava, 2 water buckets gets obsidian. Water from an aqueous accumulator.  Have to do a couple other quests first to get the coins but it's possible. Least that's how I did it anyway.

**Comment by DinnerBeef** [comment]
See issues #14 #21 #65. As @ThePoet444 there are ways for you to get all the stuff you need to get for the pack on this island

**Comment by TheOfficialButton** [comment]
There are multiple ways to get started on Chosens map. If you find it too difficult then maybe consider an easier map and come back to that world later?
