### ISSUE TITLE
server EMC bug

### ISSUE THREAD

**Issue by Meepdude212** [FTBTeam/FTB-Sky-Odyssey#154]
* **Modpack Version**: 1.0.0

* **Issue**: There is a bug in servers where if you go offline, any EMC that you automate, chunkloaded or not, will not be given. even the power flower bonsai pots.

* **Link to Log or Crash File Paste**: there is no file

* **Is it Repeatable?**: yes

* **Mod/s Affected**: possibly Project EX

* **Known Fix**:

**Comment by Firefox37** [comment]
you can get around this by connecting the matter collectors to a energy condenser and it will generate offline, but it seems that the personal EMC links do not still link to the player once offline or something. and this obviously will be limited by the fact that you won't be able to use the flower bonsai pots.

**Comment by Naxanria** [comment]
This has been reported to the mod author, will be fixed in the future.
