### ISSUE TITLE
Holograms falling through the world

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Sky-Odyssey#155]
* **Modpack Version**: 1.0.0

* **Issue**: Holograms are falling through the world. There was a ticket made [here](https://github.com/randombyte-developer/holograms/issues/32) which I've been using. This ticket will hopefully provide all the needed information.

* **Mod/s Affected**: Holograms, HuskyCrates and any other mod/plugin that used holograms with invisible flying armor stands.

* **Known Fix**: Not sure yet. I tried a few things listed in the ticket listed above but nothing worked.

**Comment by Naxanria** [comment]
Holograms, HuskyCrates are NOT part of this mod pack, so we can not support you on this issue here.
You should contact the author(s) of those mods.

**Comment by NLBlacky** [comment]
The issue does not lay with those plugins. This modpack, and Project Ozone 3 which also got marked in the issue, both have a setting or mod included that cause any armor stand to fall by gravity. The NBT to disable gravity seems to be disabled for some reason. Disabling all plugins, just a vanilla modpack and vanilla anti gravity armor stand commands didn't work either. More details on my exact tests can be found in the issue report I linked here.

**Comment by Naxanria** [comment]
This seems like a vanilla issue? https://bugs.mojang.com/browse/MC-105728

**Comment by NLBlacky** [comment]
Sadly I do not agree with that. All other modpacks (1.12.2 as well) do not have this issue. 

In case you want some examples:
These modpacks work fine: Modern Skyblock 3, Roguelike Adventures and Dungeons, Stoneblock 2, Sky Adventures, Direwolf2.0, Revelation, Mystical Village 2, Life in the Village, Ultimate Reloaded and Enigmatica 2 Expert.
These modpacks do not: Project Ozone 3, Sky Odyssey

All modpacks listed above are on 1.12.2. Tests were done with and without Sponge.

**Comment by randombyte-developer** [comment]
As reported, this can be simply reproduced with only the modpack installed (no Sponge or other mods). Summon an ArmorStand. Here is an example command:

```
/summon armor_stand ~ ~ ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:"TEST",CustomNameVisible:1b}
```

And it falls down to the ground.

**Comment by NLBlacky** [comment]
and I've been testing this without Sponge, just the modpack and can confirm that the holograms keep falling through the world.

**Comment by TheFlash787** [comment]
Bump. We've tested with and without Sponge. Same issue. Please get this fixed asap.
