### ISSUE TITLE
Problem creating a server with server.pro

### ISSUE THREAD

**Issue by levi-packard** [FTBTeam/FTB-Sky-Odyssey#156]
I was planing on creating a server for a friend and I. but when i start the server and join for the first time it starts me in the overworld. how to i get it to spawn in the original easy, normal and challenge map?.    im following the instructions for how to make a ftb server on server.pro by using the  sky odyssey download and importing the zip into the server.  how do i get the server to start with the island rather then getting a regular world.    if anyone can help me make the server that would be greatly appreciated.   if you have a server.pro account i can give that account access to the server if you can help me set it up properly.  any help would be welcome.  i know that creeper host is the sponsored hosting service but i have already payed for the server on server.pro

**Comment by DinnerBeef** [comment]
make sure you copy all the files from the server download including the world folder and make sure in server.properties you have
Level-type=void_world 
that should do it (you can pick your island when you make a team)

**Comment by Naxanria** [comment]
This has been reported to the developer.

**Comment by Slowpoke101** [comment]
Sorry I have no idea about how server.pro operates. I would suggest you contact their support to help with server installation issues. However when you first downloaded the server, it would have come with a world folder for you to use.
