### ISSUE TITLE
Cant Access Creative Mode

### ISSUE THREAD

**Issue by TLeroseXC** [FTBTeam/FTB-Sky-Odyssey#157]
I do not know how to change my game mode to creative because i am transfering all my progress from Sky Adventures to Sky Odyssey using cheats that way i don't have to start from scratch but also keep up to date with the newest Sky Factory mod pack based around ProjectE. Please tell me how soon. Thank you 😄

**Comment by DinnerBeef** [comment]
Do to bug with opening to lan atm I would add this mod https://minecraft.curseforge.com/projects/enable-cheats.

Basically the same issue as #60

**Comment by TLeroseXC** [comment]
Thanks for the help!
