### ISSUE TITLE
Very Minor Quest Issues

### ISSUE THREAD

**Issue by PebbleTwig** [FTBTeam/FTB-Sky-Odyssey#158]
2 things, both have to do with quests. Firstly, in the description of introduction it says "Getting started in Sky Adventures" when it should instead say "Sky Odyssey". Secondly, in the chapter complete tab in the quest book all of the icons match the sections above except for tool mastery, which in the above tab has a forge hammer and the icon in the chapter complete tab has a dark matter pickaxe. Again, very minor and easily fixable issues.

**Comment by 016Nojr** [comment]
@Slowpoke101 The Storage Expertise chapter also mismatch to the Chapter Complete tab, one has a RS Drive and the other has an AE2 Drive.

**Comment by 016Nojr** [comment]
Also, "Technology Mastery" is missing a chapter complete quest
