### ISSUE TITLE
[FEATURE] Add Crimson Cultist spawn egg / Crimson Portal Spawn egg to the shop

### ISSUE THREAD

**Issue by hron84** [FTBTeam/FTB-Sky-Odyssey#159]
* **Modpack Version**: 1.0.0

* **Issue**: 

Crimson Knights / Crimson Cultists cannot spawned in the game since they only spawn in specific conditions from a Crimson Portal. If I remember correctly, Crimson Book cannot obtained for Thaumcraft, neither it could be bought at the shop. Also, Crimson armor cannot obtained by any way in the game.

* **Is it Repeatable?**: yup

* **Mod/s Affected**: 

* **Known Fix**: 

Add Crimson Portal spawn egg or Crimson Cultist / Crimson Knight spawn eggs to the shop, so they could be spawned by any way game provides spawning them. 

Alternatively add Crimson book and Crimson armor to the shop (since that armor is basically iron level, it should not be too expensive, as it serves pure aesthetic in this pack as there is no night)

**Comment by monkeybug34** [comment]
yes please
