### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by Smalllevy** [FTBTeam/FTB-Sky-Odyssey#16]
When I try to download the pack it shows the error message "Cannot find addon dependency 222348"

**Comment by xellosmetallum** [comment]
Having the same issue with a different dependency number. "Cannot find addon dependency 225635"

**Comment by Smalllevy** [comment]
I just updated Twitch and now it says "Failed to get mod loader from manifest!"

**Comment by Jake-E** [comment]
This is a Twitch app issue

**Comment by totlnerd** [comment]
got a error message saying: Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip need help

**Comment by Smalllevy** [comment]
> This is a Twitch app issue

I think so too, at this point Twitch doesn't do anything when I click install.

**Comment by xellosmetallum** [comment]
Yeah i restarted the twitch app and tried downloading again and it worked

**Comment by Smalllevy** [comment]
Yeah, restarting Twitch seems to make it work. Sadly, my laptop isn't powerful enough to handle more than 120 mods. Oh well...
