### ISSUE TITLE
Wrong inscriber press recipes?

### ISSUE THREAD

**Issue by Elrol** [FTBTeam/FTB-Sky-Odyssey#160]
* **Modpack Version**: 1.0.0

* **Issue**: The calculation press needs gold (when it turns quartz into printed calculation circuit) while the logic press needs quartz (which turns gold into printed logic circuits) It is a minor thing that may have been overlooked, or even intended. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: I would assume so.

* **Mod/s Affected**: N/A

* **Known Fix**: Change the scripts to output the correct items.

**Comment by Naxanria** [comment]
Its fine, just throws people for a loop :P

**Comment by Ludi87** [comment]
Also the recipe only works with EnderIO Silicon, tried with AE2's and Refined Storages first.
