### ISSUE TITLE
[Quest] Unbreakable Wand

### ISSUE THREAD

**Issue by dsabecky** [FTBTeam/FTB-Sky-Odyssey#162]
* **Modpack Version**: 1.0.0

* **Issue**: The quest "Unbreakable Wand" does not get credit once the wand is crafted.

* **Link to Log or Crash File Paste**: 
![2019-03-21_23 52 11](https://user-images.githubusercontent.com/778367/54799635-7109f880-4c34-11e9-8dd4-4cbf7e886b7a.png)

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by GotYourOreo** [comment]
You might need to craft the highest tier wand, I was able to do this mission fine. Search for the wand in your JEI and you'll see there are 3 versions that all have a different amount of max blocks placed.

**Comment by dsabecky** [comment]
I'll double check this when I get to my computer. If that is the case, it should be annotated somewhere.

**Comment by GotYourOreo** [comment]
When you click on the mission press the "r" key for recipe and you'll see that it requires 4 of the second stage ones.

**Comment by Naxanria** [comment]
Its the 16k blocks one, see the tooltip for the required wand :)
