### ISSUE TITLE
Liquifacted coal repeatable quest

### ISSUE THREAD

**Issue by GotYourOreo** [FTBTeam/FTB-Sky-Odyssey#163]
Modpack Version: 1.0.0

Issue: Not really an issue but more of a balancing thing. I'd suggest doubling the amount of liquid required or halving the reward get from the Liquifacted coal mission, it's very easy beastcoin I think too easy. Let me know what you think.

Link to Log or Crash File Paste: n/a

Is it Repeatable?: yes

Mod/s Affected:

Known Fix:

**Comment by TheOfficialButton** [comment]
The liquifacted coal is actually one of the meh ones to do and not one of the best. So there are even easier options out there. So this quest will remain as is. Thank  you for the feedback though :)
