### ISSUE TITLE
Dimension X - Too easy to access - possibly broken?

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Sky-Odyssey#164]
* **Modpack Version**: 
1.0.0
* **Issue**: 
I don't know if this is an issue, but dimension x is probably a wee bit too easy to get into, few enderpearls bit of marble and you're in... And you get a tome of knowlege, i don't know if this is intentional but kinda puts a stopper on the gameplay.
* **Link to Log or Crash File Paste**: 
No crash

* **Is it Repeatable?**: 
Well, yes.
* **Mod/s Affected**: 

* **Known Fix**: 
Make it a tad harder perhaps? It is the "finale" according to the quest lines.

**Comment by bestxp** [comment]
To get Dim X you should get trophy from final quests

**Comment by nzminecraftDOTcom** [comment]
I got to dim X by making the portals, placing blocks on top of the portal frames, and then jumping into the portal.

**Comment by Naxanria** [comment]
Send to mod author.
