### ISSUE TITLE
crash while trying to make a wireless crafting terminal

### ISSUE THREAD

**Issue by Nightsgift** [FTBTeam/FTB-Sky-Odyssey#165]
* **Modpack Version**: 1.0.0

* **Issue**: when i put the wireless terminal and the crafting terminal in the ME crafting terminal it crashes

* **Link to Log or Crash File Paste**: https://paste.ee/p/bF4co

* **Is it Repeatable?**: yes

* **Known Fix**:

**Comment by bontavi** [comment]
with universal terminal same.

**Comment by Slowpoke101** [comment]
Added a new mod that should fix this issue
