### ISSUE TITLE
Some shop items are not showing up when I am on servers

### ISSUE THREAD

**Issue by DaBlueSheep** [FTBTeam/FTB-Sky-Odyssey#167]
* **Modpack Version**: 1.0.0

* **Issue**: So i tried buying the acceleration wand on a server and it is not in my shop menu. I can buy it on single player but not in a server for some reason.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/598988b1

* **Is it Repeatable?**: I tried logging out and back in but the glitch is still there so I guess so. 

* **Mod/s Affected**: beast coin miner or whatever the shop mod is and not enough wands

**Comment by Towny01** [comment]
they removed some of those things as they are not server friendly, can be changed to be available in the configs.

**Comment by Naxanria** [comment]
Yes this is intended, the acceleration wand and the watch can cause massive issues on servers, hence they arent available on the server.
