### ISSUE TITLE
Glass Chicken Recipe dont work. 

### ISSUE THREAD

**Issue by justinfns** [FTBTeam/FTB-Sky-Odyssey#168]
Version: FTB Sky-Odyssey 1.0.0
I want to make the Glass Chicken but it didnt show up when i want to breed log and coal chickens. 
Is it Repeatable? Yes, it is repeatable**:

Mods : Chickens Mod and Roost

**Comment by Chara-Reborn** [comment]
No, this works just fine. It's a core mechanic of breeding where you have a chance of getting what you want.

**Comment by Naxanria** [comment]
It is indeed a chance of getting the result, not a 100% chance.
