### ISSUE TITLE
The Final Collector

### ISSUE THREAD

**Issue by MineplayerHDYT** [FTBTeam/FTB-Sky-Odyssey#169]
* **Modpack Version**: 
1.0
* **Issue**: 
The "The Final Collector" Quest Triggers completed when you have only the tier 1 collector in your inventory
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
no because the quest is then completed
* **Mod/s Affected**: 
FTB Quests
* **Known Fix**: 
Every Collector got a diffrent ID or do not let every metadata complete the quest

**Comment by MineplayerHDYT** [comment]
Same with "The Final Relay"

**Comment by manmaed** [comment]
see #40 & #41
