### ISSUE TITLE
Multiplayer Error

### ISSUE THREAD

**Issue by zeranoth** [FTBTeam/FTB-Sky-Odyssey#17]
When a friend tried to open a server via the FTB Site's shown Server and I tried to join it, it showed an error related to Server Mod Rejections, Most if not all related to Ender IO. Not even he himself could join.

**Comment by Alfurin** [comment]
Me and a friend are having the same error. Its like the server is not the same version as we got from twitch.

**Comment by Slowpoke101** [comment]
Are you still having this issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zeranoth** [comment]
I fixxed the problem by downloading the version you get when you click "Get server" from the FTB Launcher.

**Comment by modmuss50** [comment]
Closing as its seems to be a one off issue that has been fixed.
