### ISSUE TITLE
Sky Odyssey crash

### ISSUE THREAD

**Issue by mikey150** [FTBTeam/FTB-Sky-Odyssey#170]
* **Modpack Version**: 1.0.0 

* **Issue**: when clicking throw to see how something is made the game crashes

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/63c8ee18

* **Is it Repeatable?**: yes this is like the 3rd time 

* **Mod/s Affected**: no mods are causing it 

* **Known Fix**: I don't

**Comment by modmuss50** [comment]
On line 475 of that crash report:

`Current Language: ~~ERROR~~ NullPointerException: null`

For some reason you have an invalid language selected. Can you try changing language, or let me know what language you have selected.

**Comment by Slowpoke101** [comment]
closing unless repeated
