### ISSUE TITLE
Game crashes when joining server

### ISSUE THREAD

**Issue by ShadowSans55** [FTBTeam/FTB-Sky-Odyssey#171]
* **Modpack Version**: 1.0.0

* **Issue**: Game crashes when entering server

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a1fbaada

* **Is it Repeatable?**: Yes

**Comment by Naxanria** [comment]
Looks like your Inventory Tweaks is checking for a weird key, might try and change the key to something else in your options.

**Comment by Slowpoke101** [comment]
Did this fix the issue?

**Comment by ShadowSans55** [comment]
Yes, it did. Thanks!

**Comment by Naxanria** [comment]
Awesome!
