### ISSUE TITLE
Error in recipe stoneburnt chicken

### ISSUE THREAD

**Issue by tuberasa** [FTBTeam/FTB-Sky-Odyssey#172]
* **Modpack Version**: 
1.0.0

* **Issue**: 
Cannot craft stoneburnt chicken egg, redstonecrystalchicken is missing the "morechickens:"

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
yes

* **Mod/s Affected**: 
roost/chickens/morechickens
* **Known Fix**: 
in chickens.sz
#Add recipe for Stoneburnt Chicken
    recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "morechickens:stoneburntchicken"}}),
	[
		[<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>],
		[<roost:chicken>.withTag({Chicken: "morechickens:redstonecrystalchicken"}),<minecraft:egg>,<roost:chicken>.withTag({Chicken: "chickens:goldchicken"})],
		[<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>]
	]

**Comment by Slowpoke101** [comment]
? Stoneburnt chicken doesn't require redstone chicken. To confirm, the original breeding recipe for the Stone burnt chicken is not in the pack, you are supposed to craft the egg that spawns the chicken in.

**Comment by SephirothWS** [comment]
@Slowpoke101 The script requires [roost:chicken.withTag({Chicken:redstonecrystalchicken"}) for the left-most chicken in the recipe which is an invalid chicken thus making the changed recipe invalid. The script didn't include the morechickens: mod prefix in the NBT data for the chicken necessary. Whoever wrote the script decided to nerf the original breeding by making it require the EXU2 redstone crystal chicken to make stoneburnt chicken.
