### ISSUE TITLE
Fluix seeds

### ISSUE THREAD

**Issue by Etheria137** [FTBTeam/FTB-Sky-Odyssey#175]
* **Modpack Version**: 1.0.0

* **Issue**: When you make a fluix seed from AE2, if you put it into the transmutation table from ProjectE it turns it into certus seed from AE2.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectE 

* **Known Fix**: remove it because this has happened in other packs I have played and they couldn't resolve the issue.

**Comment by Naxanria** [comment]
Removing the emc from them does indeed seems best course of action.
