### ISSUE TITLE
Advanced Solar Panel turning into Basic Solar Panel

### ISSUE THREAD

**Issue by TomiPomi** [FTBTeam/FTB-Sky-Odyssey#176]
Modpack Version: 1.0.0

Issue: I've encountered this glitch, where my advanced solar panel would turn into the basic ones.

It will happen when you try to place the solar panels with an unbreakably wand(maybe other wands too) they would turn into basic solar panels.

Please fix this, its really annoying.

**Comment by tyler489** [comment]
That's a bug on the wand not saving nbt data
