### ISSUE TITLE
Flux networks and applied energetics combined crash the server

### ISSUE THREAD

**Issue by 123Kappa** [FTBTeam/FTB-Sky-Odyssey#177]
* **1.0.0**: 

* **Issue**: Crash, judging for the crash report it happens when a flux point connects with a me system. It's a common crash, server crashed 10 times in 3 days. 

* **https://paste.feed-the-beast.com/view/6726bb55 Here's the crash report

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Applied energistics and flux networks

* **Known Fix**: No fix for now

**Comment by nzminecraftDOTcom** [comment]
Has happened on many modpacks 

Best report it directly to the AE2 mod makers.

**Comment by Naxanria** [comment]
This seems to be a sponge issue.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3965
