### ISSUE TITLE
Game Crashed when I attempted to visit another persons island

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Sky-Odyssey#178]
* **Modpack Version**: 
1.0
* **Issue**: 
Game crashed when I attempted to visit someone elses island
* **Link to Log or Crash File Paste**: 
https://pastebin.com/1NZ2yUKT
* **Is it Repeatable?**: 
No clue, still waiting on minecraft to reload
* **Mod/s Affected**: 

* **Known Fix**: 
No clue

**Comment by LatvianModder** [comment]
Appears to be a vanilla bug of some kind, I doubt it will happen again
