### ISSUE TITLE
Game Over FTBCrates not appearing on the Wither's loot table.

### ISSUE THREAD

**Issue by Chara-Reborn** [FTBTeam/FTB-Sky-Odyssey#179]
* **Modpack Version**: 1.0

* **Issue**: Game Over FTBCrates not appearing on the Wither's loot table.

* **Is it Repeatable?**: Yes, setup a Tier IV Woot Factory for the Wither. You won't be able to get "Game Over" crates 

* **Mod/s Affected**: Woot

**Comment by AnorakThePrimordial** [comment]
relevant additional info related to how woot works and why game over crates are bugged in the pack: https://www.reddit.com/r/feedthebeast/comments/b4m71v/sko_game_over_loot_bags/

**Comment by fGravity** [comment]
Can confirm, had my Woot farm running on a server, killed about 10k withers, but no crate.
Worked fine with a manual wither farm and a draconic grinder.

**Comment by Slowpoke101** [comment]
This is a problem with the way Woot works and there is nothing we can do to fix this. However you can use the command /woot flush all and this may help to fix the problem.
