### ISSUE TITLE
No server files

### ISSUE THREAD

**Issue by HTMLvin** [FTBTeam/FTB-Sky-Odyssey#18]
I click the link to go to server files. But there are no server files just the game file. Are the server files out yet or no?

**Comment by SayHerro** [comment]
Im having the same problem. I don't think they added the files.

**Comment by Redeye123** [comment]
![image](https://user-images.githubusercontent.com/828563/54568004-00fe3700-49d6-11e9-84e5-f93cd25ed223.png)

That makes it even funnier xD

**Comment by Naxanria** [comment]
That is probably a sync delay with the server files.

**Comment by Redeye123** [comment]
Prob My community is yelling at me so i looked and noticed that tweet and was laughing :P

**Comment by Jake-E** [comment]
Server files are still being processed, unfortunately, this is on Twitch's end so we can't make this any faster.

**Comment by Alfurin** [comment]
> Server files are still being processed, unfortunately, this is on Twitch's end so we can't make this any faster.

A quick fix would be just have them on ftb website.

**Comment by Jake-E** [comment]
The FTB website runs off of CurseForge, this isn't possible.

**Comment by HTMLvin** [comment]
Gotcha... Doesn't seem like a thing that would take 5hrs to process though

**Comment by DoubleDeathclaw** [comment]
https://mc-launcher.com/launcher/ftb Go here to the FTB launcher down that it and you can click Download Server files, thats how i got it.

**Comment by HTMLvin** [comment]
> https://mc-launcher.com/launcher/ftb Go here to the FTB launcher down that it and you can click Download Server files, thats how i got it.

That work great thanks!

**Comment by modmuss50** [comment]
They are now there.
