### ISSUE TITLE
Crafting Recipe broken with lapotron crystals

### ISSUE THREAD

**Issue by cateyez215** [FTBTeam/FTB-Sky-Odyssey#180]
![circuit not working](https://user-images.githubusercontent.com/48848807/54861240-f86a7100-4cf3-11e9-84ad-fe0252bd2c39.PNG)
![circuit](https://user-images.githubusercontent.com/48848807/54861252-264fb580-4cf4-11e9-8da2-96d48bc8a827.PNG)

* **Modpack Version**: < 1.0.0 >

* **Issue**: < Energy Circuit Recipe doesn't work >

* **Is it Repeatable?**: < yes >

* **Mod/s Affected**: <Tech Reborn 2.21.2.960 >

* **Known Fix**: < using another item instead of lapotron does work >

**Comment by TomiPomi** [comment]
Have you tried charging them up? 

In the recipie it looks like they are fully charged.

**Comment by tyler489** [comment]
yes but if u cursor over them they say 0 charge.... and the tech reborn ones also say 0 charge

**Comment by Ozzymud** [comment]
@tyler489 You can use 0 energy ones, they just need to be the tech reborn ones and jei doesn't populate the right ingredients for those, you have to manually do it, so I'd still call the recipes broken.

**Comment by tyler489** [comment]
Nope you definitly can't use 0 charged ones...

**Comment by Naxanria** [comment]
They indeed need to be the charged ones, will see if we can/will change the recipe for them to accept non-charged ones.

**Comment by Slowpoke101** [comment]
Working as intended, will see if we can get JEI to fix it.
