### ISSUE TITLE
Sacrificial Dagger + Draconic Armor death issue

### ISSUE THREAD

**Issue by Nezarn** [FTBTeam/FTB-Sky-Odyssey#181]
* **Modpack Version**: 1.0.0

* **Issue**: If you wear Draconic Armor and accidently kill yourself with Sacrificial Dagger, then you will lose your current gear\inventory, no grave spawns, and even openblocks won't save your inventory (so you can't reload your stuff with its command), and also since there is a grave mod, no items will be on the ground either.

* **Link to Log or Crash File Paste**: nothing death related is in the log, game doesn't even give the typical chat msg when you die. (and no errors either)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Draconic Evolution, Blood Magic

**Comment by Ozzymud** [comment]
Can confirm this also happened to me, I got like a few critical warnings then died, went back over to the spot and all that was there was some XP, no grave or items. Had to reload from a 2 hour old backup.

**Comment by Wastl-B** [comment]
and another confirmation :)

**Comment by TheOfficialButton** [comment]
This is an issue with Blood Magic. The mod dev knows about this and has done for a while. Hopefully it will be fixed in the next update to the mod.
