### ISSUE TITLE
Red Matter Furnaces do not keep smelting after relog

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-Sky-Odyssey#182]
* **Modpack Version**: 1.0.0

* **Issue**: Red Matter Furnaces do not keep smelting after relog (ask Greg for more details)

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: ProjectE

* **Known Fix**: Using tiny coal will sort of keep them going.

**Comment by MrGREGhimself** [comment]
Issue seem to be a thing **only** when using: **Aeternalis Fuel Block**

Tested with other fuel types (no issues found):
- Tiny Coal (Actually Additions)
- Coal Block (Vanilla)
- Mobius Fuel Block (Project E)
- Aeternalis Fuel (Projet E)
- Pyrotheum Dust (Thermal Foundation)

**Comment by sLpFhaWK** [comment]
Are you supplying the fuel block with an EMC link after you log off? Seeing the EMC links only work when you're online that would be the reason why it's not working.

**Comment by MrGREGhimself** [comment]
Yes, I use EMC links, it is not explaining though why other items provided with EMC links work perfectly fine.

**Comment by Slowpoke101** [comment]
This apparently is not something we can fix and is unlikely to be fixed.
