### ISSUE TITLE
Several creative items cannot be broken once placed.

### ISSUE THREAD

**Issue by mtjohnson47** [FTBTeam/FTB-Sky-Odyssey#184]
* **Modpack Version**: 1.0

* **Issue**: The creative mill cannot be broken in survival.  I've been informed the creative energy source and creative generator are the same.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities.  IC2.  Probably others.

* **Known Fix**: Add a mod to override the hardness of them to something other than 0.

**Comment by nzminecraftDOTcom** [comment]
I think you have to be in creative mode to move creative items by default, otherwise servers that have them placed down to show people how to make machines, players could remove them easily.

**Comment by mtjohnson47** [comment]
That makes sense, but...
Allowing players to enter creative mode to move their stuff is not a reasonable fix.

**Comment by Ozzymud** [comment]
The ones I could not remove with a pick I was able to pick up using a wrench.  

Like the creative tanks you can get from the thermal creative upgrade, shows an X with a pickaxe, using a crescent hammer works.

**Comment by mtjohnson47** [comment]
Doesn't work on the creative mill

**Comment by mtjohnson47** [comment]
On the creative cache, it works, but only if you're opped

**Comment by mtjohnson47** [comment]
As a workaround, the dragon egg trick works to delete these items.

**Comment by Slowpoke101** [comment]
where possible, this has been fixed in dev now, some blocks however might need items like a wrench to break the block depending on the mod.
