### ISSUE TITLE
My game is crashing when i launch it.

### ISSUE THREAD

**Issue by CrummyPaper80** [FTBTeam/FTB-Sky-Odyssey#186]
My game is crashing when i launch it. I've already deleted it and reinstalled it and I've tried other things in this thread. I'll leave a link to the crash report. What should i do?
[crash-2019-03-23_12.20.26-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2999596/crash-2019-03-23_12.20.26-client.txt)

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: net.minecraft.client.renderer.StitcherException: Unable to fit: extracells:blocks/walrus2 - size: 925x925 - Maybe try a lowerresolution resourcepack?

_Originally posted by @CrummyPaper80 in https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/94#issuecomment-475884305_

**Comment by yairs135** [comment]
Try getting into "Launch Options" in the mc launcher, then get into the version settings, and in "Java Executable" change from javaw.exe to java.exe.

**Comment by CrummyPaper80** [comment]
I did that and now it says it is unable to locate the java runtime and it changes the game directory. 

![Screenshot (1)](https://user-images.githubusercontent.com/38368436/54872142-0f619f80-4d96-11e9-92d6-36dac049fc24.png)


Unable to locate the Java runtime.
Filename on disk: 
Path: .
Exists: directory

**Comment by nzminecraftDOTcom** [comment]
Turn off your resource/texture pack

The very first line in the crash report tells you it's too high defintion.

net.minecraft.client.renderer.StitcherException: Unable to fit: extracells:blocks/walrus2 - size: 925x925 - Maybe try a lowerresolution resourcepack?

**Comment by CrummyPaper80** [comment]
So how would i turn the texture pack off? I only have the one that comes with minecraft. I haven't added any texture packs.

**Comment by nzminecraftDOTcom** [comment]
Try re installing the pack in that case, something may be corrupted in the texture pack files.

**Comment by CrummyPaper80** [comment]
yeah, i started using the legacy FTB launcher and now it works for some reason.

**Comment by nzminecraftDOTcom** [comment]
Awesome. You can probably close this now.
