### ISSUE TITLE
Ejector Upgrade Quest not accepting Item

### ISSUE THREAD

**Issue by MoreThanHidden** [FTBTeam/FTB-Sky-Odyssey#187]
* **Modpack Version**: 1.0.0

* **Issue**: Quest for Ejector Upgrade in Upgrades Mastery wont accept item.
Quest:
![image](https://user-images.githubusercontent.com/1351964/54869256-d397fb80-4dd0-11e9-8067-98d91da9d372.png)
Item:
![image](https://user-images.githubusercontent.com/1351964/54869266-ec081600-4dd0-11e9-8590-a5c7dce3c86d.png)

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IC2 and FTB Quests

* **Known Fix**: Changing NBT Mode to Ignore on the quest.

**Comment by sLpFhaWK** [comment]
I am also having this issue. I came to report but it's already been reported.

**Comment by dsabecky** [comment]
I got this to give me credit after placing it in a valid IC2 machine then removing it. Not sure if doing that changes the metadata somehow.
