### ISSUE TITLE
Game window Minimizing on it's own

### ISSUE THREAD

**Issue by spinmeround1** [FTBTeam/FTB-Sky-Odyssey#188]
* **Modpack Version**: 1.0.0

* **Issue**: Game window will minimize and go to the taskbar when I am afk.

* **Link to Log or Crash File Paste**: unknown

* **Is it Repeatable?**: game pauses on it's own to the pause screen

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Slowpoke101** [comment]
This would be almost impossible to diagnose without more information. I would imagine there must be some sort of third party interacting with the pack as I have never seen this happen to anyone else.
