### ISSUE TITLE
Builder placed EX bonsai

### ISSUE THREAD

**Issue by sgtkwol** [FTBTeam/FTB-Sky-Odyssey#189]
* **Modpack Version**: 1.0.0

* **Issue**: Project EX bonsai flowers do not generate EMC if placed by an RF Tools Builder.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: RF tools/Project EX

* **Known Fix**: N/A

**Comment by Naxanria** [comment]
As the Builder doesnt place it as you being the owner, you wont get the EMC
Cant change that.

**Comment by LatvianModder** [comment]
Actually can, I think it was fixed in latest builders wands

**Comment by Naxanria** [comment]
This is not builders wands, this is the builder from RFTools.

**Comment by dsabecky** [comment]
@Naxanria I think what @LatvianModder means is that if builders wands can fix it, so can RT Tools.

**Comment by Naxanria** [comment]
RF Tools builder uses a fake player to place stuff. Would be the same if you get another block placer, it will be linked to a fake player.

**Comment by Slowpoke101** [comment]
This is unlikely to be fixed in the near future, however we will mention it to Mcjty
