### ISSUE TITLE
Refined storage displays nothing

### ISSUE THREAD

**Issue by DBDKevin** [FTBTeam/FTB-Sky-Odyssey#190]
* **Modpack Version**: 1.0.0

* **Issue**: My Refined Storage Stopped Displaying The Items in its system the items are still there and i can craft with them with the nei recipes but i can't interact with anything in the system myself it happened after i put som IC2 Coolant fluid into a quantum fluid storage disk in the refined storage system tried breaking it all and replacing it and it doesn't do anything tried restarting world and did nothing restarted pack and it also did nothing 

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: haven't tried it in another world

* **Mod/s Affected**: refined storage

* **Known Fix**: none

**Comment by optimality** [comment]
I have a similar issue with my world - I have a Drawer Controller with a 9x9 array of 2x2 drawers, all with Creative upgrades.  When I add a new item to the array, it takes a long time for it to show up in Refined Storage.

I suspect RS is having problems with tracking billions of items or something?

**Comment by Slowpoke101** [comment]
This is unfortunately just a limit of the pack with the way that the mods operate at the moment. We can pass this information on, however, I can't give an eta on any potential fixes.
