### ISSUE TITLE
I need Titanium to make the Titanium Chicken, but the only way to get Titanium is to have the chicken

### ISSUE THREAD

**Issue by sLpFhaWK** [FTBTeam/FTB-Sky-Odyssey#191]
* **Modpack Version**: 1

* **Issue**: I need Titanium to make the Titanium Chicken, but the only way to get Titanium is to have the chicken

* **Mod/s Affected**: The only way I could get it is to use this UU-Matter from Tech Reborn, but that doesn't even tell you how to make that either.

**Comment by DBDKevin** [comment]
you'll want to look into tech reborn it has a electrolizer that when you put bauxite dust into it it gives tiny piles of titanium which can be crafted into titaniumdust which will make you your first titanium

**Comment by sLpFhaWK** [comment]
> you'll want to look into tech reborn it has a electrolizer that when you put bauxite dust into it it gives tiny piles of titanium which can be crafted into titaniumdust which will make you your first titanium

That is a REALLY roundabout way to get titanium. I don't think I've ever used that mod before. I just looked into it, will report back.

Thank you.

**Comment by sLpFhaWK** [comment]
It did work exactly as you stated, and it's needed for Chrome. Thanks for the help.
