### ISSUE TITLE
Continuous crashing on during credits

### ISSUE THREAD

**Issue by jengeld4** [FTBTeam/FTB-Sky-Odyssey#192]
* **Modpack Version**: 1.0.0 via Twitch launcher
* **Issue**: about 3 out of 4 times when I launch the pack, the loading/credit screne appears, but the game crashes sometime during the credits, often within the first 30 seconds or so. If I keep trying to launch it, eventually, I will make it through the credits and I seem to be good at that point.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/c0118092

* **Is it Repeatable?**: about 3 of 4 times, yes. I have 17 logs that I can provide if needed.

* **Mod/s Affected**: Don't know. Possibly customcredits. Possibly Forge initialization

* **Known Fix**: I have updated my java and tried to do a pack repair because I seen it mentioned in a few other topics. Neither seem to fix the problem.

**Comment by Rushmead** [comment]
The log file that you've posted is one from where you've successfully logged into the game and has crashed elsewhere.

**Comment by jengeld4** [comment]
https://paste.feed-the-beast.com/view/ffc1b9ac Try this one. crashed almost as soon as the credits started rolling.

**Comment by Naxanria** [comment]
I can not see any crash report, nor big glaring errors to warrant a crash in that paste.
You can try disabling the the credits mod and see if that helps (SplashAnimation)

**Comment by Slowpoke101** [comment]
We are temporarily removing credits in the next update till a better solution can be found.
