### ISSUE TITLE
Refined Storage, EMCed storage disks malfunctioning. 

### ISSUE THREAD

**Issue by LiXDL** [FTBTeam/FTB-Sky-Odyssey#193]
* **Modpack Version**: 1.0.0

* **Issue**: When using Refined Storage, if a storage disk is acquired by EMC, it cannot be plugged into the disk drive. Only the ones that is crafted by combining storage housings and storage parts can be placed into the disk drive. 

* **Link to Log or Crash File Paste**: There is no crash. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: Crating the storage disk will solve it.

**Comment by Slowpoke101** [comment]
This is a known issue. The relevant mod authors are aware of this afaik.
