### ISSUE TITLE
Akashic tome not crafting with draconic evolution tablet

### ISSUE THREAD

**Issue by Timcampy** [FTBTeam/FTB-Sky-Odyssey#194]
* **Modpack Version**: 1.0.0

* **Issue**: The Draconic Evolution information book (which is a tablet) can't be reattached to the Akashic tome by crafting once ejected via sneak+drop. Other books seem to work just fine. 

If I had to guess, the whitelist of things that can go to the tome, in the config file, simply doesn't contain the tag of the draconic tablet and since its name does not contain any of the default keywords, it simply doesn't work.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: No, since you only have one Akashic tome.

* **Mod/s Affected**: Draconic Evolution and Akashic Tome

* **Known Fix**: Add the tablet to the akashic tome config file?

**Comment by Slowpoke101** [comment]
This should be fixed in the next update.
