### ISSUE TITLE
Runs off of map randomly killing self

### ISSUE THREAD

**Issue by CrummyPaper80** [FTBTeam/FTB-Sky-Odyssey#195]
* **Modpack Version**: 1.0.0 using twitch launcher and FTB launcher

* **Issue**: I will randomly just run off the map when i am playing causing me to die and lose all of my items i had in my inventory. I don't know what is causing it but it has so far happened at least a dozen time to me forcing me to use cheats to get everything i had back.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4be6e65f
and https://paste.feed-the-beast.com/view/2a4f741d

* **Is it Repeatable?**: yes, too many times

* **Mod/s Affected**: No clue

* **Known Fix**: No known fix

**Comment by nzminecraftDOTcom** [comment]
Doesn't sound like a pack issue, more like your keyboard could be faulty. 
Nothing in the pack can "move" you around except vector plates and you would know if you were on those.

**Comment by Naxanria** [comment]
This does indeed sounds like a faulty keyboard.
