### ISSUE TITLE
The Thaumcraft start-up crafting recipe is not working.

### ISSUE THREAD

**Issue by Arcade43** [FTBTeam/FTB-Sky-Odyssey#197]
I was trying to do the Thaumcraft start-up recipe but nothing is happening. [https://drive.google.com/open?id=1v85aFmvMyctTUHEAOGFLtZqBS06IoDW3](url) 
Tell me if I am doind wrong or if is just the crystals you can get from the shop.

To see the screen shot you have to open the link in a new tab.

**Comment by 907470** [comment]
Place the crystals down on stone or something similar and break them. that initializes the "dream" as with normal Thaumcraft progression.
