### ISSUE TITLE
Ore Excavation: Doesn't work with Draconic Staff of Power

### ISSUE THREAD

**Issue by jonlukew** [FTBTeam/FTB-Sky-Odyssey#200]
Modpack Version: 1.0.0

Issue: I am unable to use Ore Excavation with the Draconic Staff of Power. It means I have to use the Red Morningstar (ProjectE) in place of it when I want to utilize Ore Excavation.

Link to Log or Crash File Paste: N/A

Is it Repeatable?: Yes very easily as detailed above.

Mod/s Affected: Either Ore Excavation or Draconic Evolution

Known Fix: N/A

**Comment by melbellrocks** [comment]
It's blacklisted in the ore excavation config.  I'm in single player so I just changed mine, but I'm guessing it's by design since it was put into the blacklist.
