### ISSUE TITLE
RFTools Crafter Tier 3 Crashing? Stopping java

### ISSUE THREAD

**Issue by Ootie** [FTBTeam/FTB-Sky-Odyssey#202]
Modpack Version: FTBSkyOdyssey-1.0.0-1.12.2

Issue: Was trying to set up Dilithium Ore emc loop with an RFTools crafter Tier 3. When i place the crafter my world works for a little bit then minecraft becomes un-responsive, and wont come back despite how long i wait. MultiMC also becomes unresponsive. 

Link to Log or Crash File Paste: Nothing crashes so im not sure which log to include. 

Is it Repeatable?: Not really, i tried three worlds. Original, backup from a few days ago (deleting everything up until i placed the crafter); brand new test world in creative, i was able to set up the emc loop fine and was able to run for 10 minutes with no issues. 

Other info: 
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_201, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 12GB allocated

Actually got a crash report loading my world: https://paste.feed-the-beast.com/view/987d4957

**Comment by Ootie** [comment]
I just thought i would include some more information:

- Not using/never have used Optifine.
- Original bug occurred on a world where i downloaded the zip and installed it that way through MultiMC.  
- I started a new world last night, this time installing the pack directly through MultiMC. This time my java became unresponsive when I had just gotten to RM furnace and personal EMC link. I was using translocators to push emerald ore into the furnace and emeralds out back into the link. Nothing else in the world should have been an issue; it was on the easy starting island had the 3 starting chickens and a non-automated mob farm.

**Comment by Slowpoke101** [comment]
Unfortunately the crash log does not tell us much, however if this crops up again, please let us know.
