### ISSUE TITLE
Infinite Creative Items

### ISSUE THREAD

**Issue by Arveldis** [FTBTeam/FTB-Sky-Odyssey#204]
* **Modpack Version**
1.0.0

* **Issue**
Creative barrel upgrades
When i try to input creative upgrades in a Yabba barrel its being blocked. I assume this is intentional since its kinda OP. 
The vending upgrade from StorageDrawers however allows me to get an infinite supply of Yabba's Creative drawer upgrade and Endgame lootcrates, allowing me to get more creative items then ill ever need. 
I did note that the Creative vending upgrade from Storage Drawers cant be given an infinite supply in the storage drawers 
I dont know if this is intentional but i think its a bug and you guys should know about it

* **Is it Repeatable?**
You can repeat it by placing a storage Drawer barrel, put Endgame lootcrates in it and then applying a creative upgrade.

* **Mod/s Affected**
Storage Drawers, Yabba

* **Known Fix**

**Comment by Ozzymud** [comment]
@Arveldis You can get an infinite supply, after installing the creative vending upgrade, use a hopper to insert another. Profit.

**Comment by Arveldis** [comment]
oh i am profiting dont you worry :P i just want to make sure that its intentional

**Comment by nzminecraftDOTcom** [comment]
I thought the aim of this pack was to get as op as fast as possible. @arveldis has done it.

**Comment by TheOfficialButton** [comment]
This is intentional. The game over crates may seem OP but they dont really give you too much of an advantage in the game and are just great fun to use and abuse. This is why we have left it in :)
