### ISSUE TITLE
Laser Base (Industrial foregoing)instant crash.

### ISSUE THREAD

**Issue by kaspermwh** [FTBTeam/FTB-Sky-Odyssey#205]
[crash-2019-03-24_14.17.43-server.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3000435/crash-2019-03-24_14.17.43-server.txt)

* **Modpack Version**: 1.0

* **Issue**: First cycle of the laserbase from industrial foregoing causes game to crash. unable to open the save file at all. Had it installed with 4 drills, 6 black lenses and resonent ender fluxducts for power.

* **Link to Log or Crash File Paste**: [crash-2019-03-24_14.17.43-server.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3000435/crash-2019-03-24_14.17.43-server.txt)

* **Is it Repeatable?**: Crashes every time i open the save.

* **Mod/s Affected**: Industrial Foregoing? the version in modpack 1.0

**Comment by Slowpoke101** [comment]
Are you still having this issue? I cant replicate this in my dev environment atm.

**Comment by kaspermwh** [comment]
> 
> 
> Are you still having this issue? I cant replicate this in my dev environment atm.

I fixed my savefile by deleting the laser entity with MCedit.

Looking back at that i might not have had a clear beam to the void, could that be the cause of a crash?
