### ISSUE TITLE
Androids not being affected by persnal nanobot beacons.

### ISSUE THREAD

**Issue by bruhzinga** [FTBTeam/FTB-Sky-Odyssey#208]
* **Modpack Version**: 1.0.0

* **Issue**: Personal nanobot Beacon not affecting androids.Basically being an android disables you from getting buffs.With speed buffs the speedmeter jumps from the buffed value to you max android speed value.

* **Link to Log or Crash File Paste**
* **Is it Repeatable?**: Yes

* **Mod/s Affected**:: Overdrive: Legacy Edition and environmental Tech

* **Known Fix** Stop being an android i guess.

**Comment by Naxanria** [comment]
As an android you can not receive any potion effects. So also not speed from the personal nanobots.
