### ISSUE TITLE
No gravestone after dying to blood magic

### ISSUE THREAD

**Issue by Patiic** [FTBTeam/FTB-Sky-Odyssey#209]
* **Modpack Version**: 1.0.0

* **Issue**: i accidentally sacrificed too many times and killed myself but it respawned me in the same spot where i died with all my stuff and i couldn't move or do anything so i killed myself again and when i respawned i had no inventory note and no gravestone

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: blood magic

**Comment by Naxanria** [comment]
This seems to be the same, or at least similar issue to #181 
What armour were you wearing?

**Comment by Slowpoke101** [comment]
This has been reported to the relevant dev.

**Comment by fEdlbV9IdW50ZXJ8** [comment]
This is a common problem with the Blood Magic mod. Don't quote me on this, but i'm pretty sure that this is an intentional feature, similar to Extra Utilities' unstable ingots, and the portal gun mod's portal to the moon.

**Comment by Naxanria** [comment]
Intentional feature of destroying your items? That would be a bit sucky lol.

**Comment by miezebieze** [comment]
I had a fully upgraded draconic armor on.
But the bigger loss is the portable grid with all the things that had no emc value.

This mod pack is over for me.

**Comment by UMiAntares** [comment]
It’s a bit late, but I don’t think that it’s a feature of blood magic because I had the same issue. So I did some testing and when you aren’t wearing the draconic armor it drops a grave.
