### ISSUE TITLE
Cant get water on Chosens island?

### ISSUE THREAD

**Issue by Guagsch** [FTBTeam/FTB-Sky-Odyssey#21]
is there a way to get water while starting on chosens island i cant find one

**Comment by Naxanria** [comment]
There are a few ways to get water. One of them is chickens, other is Aquous accumulator and there is the evertide amulet.

**Comment by Guagsch** [comment]
thanks

**Comment by bloodbound121** [comment]
but how can you breed the chickens without the water to get the wheat?

**Comment by Slowpoke101** [comment]
As was mentioned there are ways to get water. Yea chickens does not work in this pack as an initial source but there are other valid methods. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Naxanria** [comment]
You can grow crops without water. Farmfields return to dirt if they have no water nearby, but will stay farmland with a crop on them :)

**Comment by TheOfficialButton** [comment]
Water is obtainable on this island. If you find this island too challenging. Maybe consider doing an easier island and coming back to this one on another playthrough :)
