### ISSUE TITLE
"An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience."

### ISSUE THREAD

**Issue by Sandfog** [FTBTeam/FTB-Sky-Odyssey#211]
* **Modpack Version**: 1.0.0

* **Issue**: Whenever I try to launch FTB Sky Odyssey (In both Native and JAR), I get message "GAME CRASH" "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience." I have tried to re-install the mod, minecraft launcher and my java version. This crash started after I changed my Allocated Memory for minecraft mods in Twitch. I've now tried various ways to fix this problem but so far I haven't been able to fix it.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e2d9b8cd

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: -

* **Known Fix**: -

**Comment by Naxanria** [comment]
Are you using Java 8? Other versions seem to cause problems that look similar to yours.

**Comment by Sandfog** [comment]
Yes, I'm using Java 8 (Offline 64GB) Also my I'm playing on a laptop that has 8G, if that helps. I don't really know much about coding or anything so I cannot track the issue from my crash file.

**Comment by dsabecky** [comment]
Do you have OptiFine installed?

**Comment by Sandfog** [comment]
@dsabecky I had, but I deleted all the downloads and files when I deleted minecraft and re-installed it. Am I supposed to have it in order to make it work? (I know how to install it for regular minecraft but I'm not sure about Twitch?)

**Comment by Naxanria** [comment]
Optifine is something that can cause problems with mods and cause crashes at times.

**Comment by dsabecky** [comment]
@Sandfog did you resolve your issue?

**Comment by Sandfog** [comment]
@dsabecky Yeah sorry I forgot to update it here. I just had to delete Twitch and download it again. I'm not sure how that fixed it but it works now.

**Comment by dsabecky** [comment]
Don't forget to mark as closed. ♥
