### ISSUE TITLE
Beast Coin Miner Chunkloaded

### ISSUE THREAD

**Issue by OldDogy** [FTBTeam/FTB-Sky-Odyssey#214]
* **Modpack Version**: 
1.0.0

* **Issue**: 
While the Beast Coin Miner is chunkloaded the Coin price goes up, but you don't get any coins.
I just woke up to coin price of 2 million RF per coin while I gained 0 coins. 

I'm totally fine with being unable to gain coins while offline but the coin cost shouldn't go up either.

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Beast Coin Miner

* **Known Fix**: 
**shrug**

**Comment by Naxanria** [comment]
The coin cost goes up, that is the intended mechanic. So its working as intended :)

**Comment by OldDogy** [comment]
Goes up even when you gain no coins  ? O.o

**Comment by Naxanria** [comment]
On how many coins you have mined. It will grow faster and faster in costs.

**Comment by pxoxd** [comment]
If its intended to grow based on the coins you mine, isnt it a bug than that the cost grows when ur not getting any coins, i assume that the coins you mine is the coins you get so each time you mine one your supposed to get one and therefor the cost goes up?

**Comment by OldDogy** [comment]
Here is a pic. for you to calculate if this is correct. ( I doubt it )
![image](https://user-images.githubusercontent.com/8202269/55038689-fa993c00-5021-11e9-8925-863c3ae857dd.png)

**Comment by modmuss50** [comment]
I dont see how this is possible looking at the code.

```java
MoneyUtils.addMoney(player, 1);
MoneyUtils.addTotalMoney(player);
```

**Comment by pxoxd** [comment]
Would it be possible that the miner runs while offline but cant find the targeted player, and the counter for player money increases without increasing the players money(since the player is offline)?

**Comment by OldDogy** [comment]
Basically while the player is offline , and the Miner is chunkloaded, the "Current Balance" & "Total Mined" doesn't change but the "Current coin cost" goes up.
I assume that if the "Current coin cost" was based on "Total mined" the issue would be solved. (Even tho the issue here is that player balance isn't updating when the player isn't online)

----
Could be made so that it simply doesn't work at all when player is offline ? Also disabling the power draw... ?

**Comment by Naxanria** [comment]
You can turn off the miner with redstone signal.

@modmuss50 maybe save the money mined and add it when player comes online, so it can keep mining?

**Comment by Scheigy** [comment]
When I logged today, I quickly jumped to my miners and I saw they stored a lot of energy. Within a few seconds, all the energy was drawned to generate some coins.

From what I understand, when being offline, chunkloading the miners makes them store energy but prevent the mining itself. It is easy to miss because as I said the energy is drawn really quickly.

**Comment by ChylerBH** [comment]
Just adding for additional evidence, something odd is definitely going on with the Coin Miners.  I was saving for the 500,000 coin cost Creative items and logged off last night close to my first target.  See the attached playerdata NBT files for comparison.  

The _copy is yesterdays total, the normal one is todays: 
![FTBCoinMiner_Overnight](https://user-images.githubusercontent.com/37788244/55281085-389aa680-5327-11e9-9d69-01d1968c85f7.png)

And my ingame from today also showing the power cost:
![FTBCoinMiner_Overnight_Ingame](https://user-images.githubusercontent.com/37788244/55281090-4b14e000-5327-11e9-8f30-801a1fc83436.png)

This is on a personal / private server which I play with one other.  No errors client side, or server side.

Thanks.

**Comment by modmuss50** [comment]
I can stop the miner from taking power when you are offline, but unless im being stupid there is no way it should increase the total coins without generating the coins.

**Comment by OldDogy** [comment]
... XD lol ... you missed the point from the beginning.
It's not increasing total coins , it's increasing the coin cost. 
Even when you are offline and you don't get any coins , the coin cost goes up... 
total coins stays the same. (This is why I said if you make it so: "Current Coin Cost" checks the "Total mined" and adjusts itself based on Total Mined)

Say you just start out on a server, you buy and set up the coin miner and you chunkload your base ....
Then you log off.
when you come back , you gain 0 coins, but now instead of 4,000 FE per coin, the miner needs 2.5 million FE per coin... 

The coin cost is going up and just eating your power and asking for more and more and not giving you anything. 
....
Just let me know if I am making no sense  ;)

**Comment by Mattabase** [comment]
![image](https://user-images.githubusercontent.com/2126947/55857559-6f4c9a00-5b3b-11e9-8463-41fd932f139f.png)

Just wondering if that scaling looks correct.

**Comment by modmuss50** [comment]
Yes, that fits in with the function that I was given

**Comment by OldDogy** [comment]
That is absurd it's even worse now then what it used to do xD oh well ... Billion FE for a single coin .
Mine was 2 million at almost 300,000 mined, and his is only 1100 times larger on 400,000 mined :D

But meh i guess since it's absurdly easy to get a creative energy source it doesn't even matter ...
