### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by charmchuu** [FTBTeam/FTB-Sky-Odyssey#216]
* **Modpack Version**: 1.0.0

* **Issue**: Game crashes on startup when launching from MultiMC launcher.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0ac71d02

* **Is it Repeatable?**: Every time I launch the game.

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by Slowpoke101** [comment]
Are you still getting this issue? nothing we can see is wrong on our end.
