### ISSUE TITLE
Saved Worlds Not Showing

### ISSUE THREAD

**Issue by Rainviper16** [FTBTeam/FTB-Sky-Odyssey#217]
* **Modpack Version**: 1.0.0

* **Issue**: After reloading up the pack no saved worlds appear (I had two) But after checking the saves file both are there it's just they aren't appearing in the minecraft menu.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a9733dea 

* **Is it Repeatable?**: Yes closing and reloading the instance still shows no signs of the saved worlds

* **Known Fix**: none

**Comment by PandaCrazy672** [comment]
I think that this is an issue with Minecraft itself because every modpack I install this happens. My only fix is to use backups that you will find in your modpack directory and replacing it with the recent one.
And without forgetting to backup your world before colosing it.

**Comment by Naxanria** [comment]
There is nothing showing in the log you send. So cant determine the reason from that.
Is this still an issue?

**Comment by Rainviper16** [comment]
No not an issues anymore. A solution I found is a delete all saves and copy in new backups.
