### ISSUE TITLE
Final Star resets EMC count

### ISSUE THREAD

**Issue by Jrprogrammer** [FTBTeam/FTB-Sky-Odyssey#218]
* **Modpack Version**: 1.0.0

* **Issue**: Putting a Final Star in the bookmarks of the Transmutation Table resets the EMC counter to 0

* **Is it Repeatable?**:  yes, across restarts

**Comment by Rainviper16** [comment]
Just to make sure you aren't accidentally storing all of your EMC into your star?

**Comment by dsabecky** [comment]
Placing the final star in the left side charges it. There is no visual charge bar for the Project EX stars so I can understand why this would be confusing. Recommend forwarding to mod dev to add charge indicator to stars?

**Comment by Jrprogrammer** [comment]
Wouldn't the EMC stored in the star also be added to the total EMC count when put back in the table?
The final star doesn't add back the "stored" EMC back into the table.

**Comment by dsabecky** [comment]
@Jrprogrammer Yes, it should. Possibly the final star is considered a void item? Either way it should be annotated somewhere.

**Comment by Xavion3** [comment]
Klein stars fill their buffer from the table on the left and fill the table from their buffer on the right. The final star is essentially a creative klein star, you're trying to fill it if you stick it on the left which will never work. If you instead stick it in the slot on the right it'll fill the table instead, it isn't actually infinite EMC acting as if it had a 1P buffer, but you can stick it in the slot as many times as you like each time giving another 1P to your table.

**Comment by metalim** [comment]
Considering the star itself costs 600P, I suggest increasing it’s “buffer” (even though it’s creative) to 1E. All oher stars have buffer larger than their cost.
