### ISSUE TITLE
[Shop] Watch of Flowing Time

### ISSUE THREAD

**Issue by dsabecky** [FTBTeam/FTB-Sky-Odyssey#219]
* **Modpack Version**: 1.0.0

* **Issue**: Watch of Flowing Time shows in JEI as obtainable through the Shop, however is not available in the shop.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: ProjectE (1.12.2-PE1.4.0), FTBQuests (1.5.1.136)

* **Known Fix**: Add to shop or remove from shop tab in JEI.

![image](https://user-images.githubusercontent.com/778367/54957171-57183080-4f28-11e9-8019-a3f0d6fdcaa8.png)

![image](https://user-images.githubusercontent.com/778367/54957303-bd04b800-4f28-11e9-90c3-c569be1e0880.png)

**Comment by dsabecky** [comment]
After seeing issue #167, my point still stands. Even though on server version they're disabled, they should be removed from JEI tab (on server version).

**Comment by Surawsome** [comment]
If you look under the creative items tab, you can actually buy it for the 500,00 coins it says. It's in the shop :P

**Comment by dsabecky** [comment]
@Surawsome , as shown in the second screenshot (search is universal), the watch is not available through the shop whatsoever while on a server.

**Comment by Naxanria** [comment]
@LatvianModder a tooltip in JEI for it being disabled on servers might clarify this?

**Comment by Slowpoke101** [comment]
A tool tip will be getting added.

**Comment by dsabecky** [comment]
@Slowpoke101 If possible, same for the Acceleration Wand?

**Comment by nzminecraftDOTcom** [comment]
Any way to manually enable the accel wand? It's useful for players when they get up to that stage of needing to speed things up.

**Comment by dsabecky** [comment]
@nzminecraftDOTcom Edit the config/ftbmoneyshop.nbt file, or overwrite it from a single player world (world/data/ftbmoneyshop.nbt)

**Comment by Naxanria** [comment]
Issue stays open till the update actually goes out.

**Comment by dsabecky** [comment]
> Issue stays open till the update actually goes out.

👌
