### ISSUE TITLE
Watch of Flowing Time

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Sky-Odyssey#22]
You can still get one via the game over chest on servers

**Comment by manmaed** [comment]
[Game Over] (http://ss.manmaed.net/1552953149.png)

**Comment by Jake-E** [comment]
I'm sure this was removed. Will remove in dev.

**Comment by Slowpoke101** [comment]
It’s fine Jake, the watch is meant to be in the chest with a lowered drop chance.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheOfficialButton** [comment]
Resolved as an intended feature.
