### ISSUE TITLE
Game Crashes A Couple of Seconds After Loading Into World.

### ISSUE THREAD

**Issue by Potov123** [FTBTeam/FTB-Sky-Odyssey#220]
**Modpack Version:** 1.0.0

**Issue:** After placing down some quantum solar panels my game crashed and now every time i load into the world it crashes after about 5 seconds and gives me this error "Error: java.lang.ArrayIndexOutOfBoundsException: 9"

**Link to Log or Crash File Paste:** https://paste.feed-the-beast.com/view/14b13ae2

**Is it Repeatable?:** yes

**Mod/s Affected:**

**Known Fix:** After about 5 crashes with the 5 seconds of time i had i managed to mine some of the solar panels and not crash. I then counted how many solar panels there were and i had 107 solar panels without crashing so i don't know if there is a limit but it fixed it.

**Comment by Naxanria** [comment]
This bug is fixed in the next update. #102
