### ISSUE TITLE
Unable to remove Environmental Tech's Pladium from Refined Storage

### ISSUE THREAD

**Issue by xenoflot** [FTBTeam/FTB-Sky-Odyssey#221]
* **Modpack Version**: 
v1.0.0-1.12.2 in MultiMC

* **Issue**: 
I put some of Environmental Tech's Pladium blocks into the RS but I'm unable to get them back out. 

Crossposted to RefStor git https://github.com/raoulvdberge/refinedstorage/issues/2201

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by dsabecky** [comment]
Are they stored in a drive, block, external via storage drawer etc?

**Comment by xenoflot** [comment]
On a 64k disc in a drive.

**Comment by xenoflot** [comment]
OK, my bad. I just discovered that they'd found their way into the input buffer of an External Storage connector. As the connected inventory was full, they remained in the buffer, visible to the network but inaccessible.
