### ISSUE TITLE
BeastCoin Flower with Creative Energy Source (ExtraUtils2) crashes the game

### ISSUE THREAD

**Issue by Wastl-B** [FTBTeam/FTB-Sky-Odyssey#222]
* **Modpack Version**: 1.0.0

* **Issue**: I made some Beast Coin Flowers with the Creative Energy Source (ExtraUtils2) from the shop and in the middle of building a third one the game crashed. After a restart it keeps crashing after about 20-30 seconds.

* **Link to Log or Crash File Paste**: 
    the first crash: 
        https://paste.feed-the-beast.com/view/f615e470
    after restart it created 2 different crashlogs: 
        https://paste.feed-the-beast.com/view/879ed12b
        https://paste.feed-the-beast.com/view/4876c0e5

* **Is it Repeatable?**: probably, because it crashes after restart

* **Mod/s Affected**: BeastCoinMiner and ExtraUtils2

**Comment by LatvianModder** [comment]
Not related to either of those, you have abused watches too much, it seems
