### ISSUE TITLE
try to make server

### ISSUE THREAD

**Issue by MrWunz** [FTBTeam/FTB-Sky-Odyssey#223]
i try to make a nitrado server with this modpack but it doeasnd load any mod! i tried to put in every mod manuel but i cant find the mods in the mod folder! pls make a folder with all the mods to download. then it should be easy to make the server

**Comment by Wastl-B** [comment]
Did you download the server files?

**Comment by manmaed** [comment]
Are you using the Server files form the curse forge website as thay do cotain all the mods needed for a server: [FTBSkyOdysseyServer_1.0.0.zip](https://www.feed-the-beast.com/projects/ftb-sky-odyssey/files/2688904)

**Comment by dsabecky** [comment]
@MrWunz Contact Nitrado support if you're having issues using their service.

**Comment by TheOfficialButton** [comment]
This is not a bug with the pack. However make sure you are using the correct server files. If so then contact Nitrado support and they will be able to help.

**Comment by MrWunz** [comment]
even theserver files dont work!
