### ISSUE TITLE
[Bug] Cannot place down Refined Storage Wireless Transmitter

### ISSUE THREAD

**Issue by WhatThePuckPT** [FTBTeam/FTB-Sky-Odyssey#224]
* **Modpack Version**: 1.0.0

* **Issue**: Simply put, for some unknown reason, I cannot place down the Wireless Transmitter from Refined Storage, the one that allows wireless access to the grid.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1fea96c9

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refined Storage

**Comment by Scheigy** [comment]
It is tedious to place, it needs to be place on a cable going up. Did you try placing it this way ?

![2019-03-26_22 07 46](https://user-images.githubusercontent.com/7931135/55033501-9ec7b680-5013-11e9-851f-db585dd49ae2.png)

**Comment by WhatThePuckPT** [comment]
Oh... that's an odd placement method, but it works. I apologize - I had only had experience with Applied Energistics before this pack, and assumed it would work like it.
