### ISSUE TITLE
AE2 P2P ME Tunnels not working

### ISSUE THREAD

**Issue by philwilei** [FTBTeam/FTB-Sky-Odyssey#225]
* **Modpack Version**: 1.0.0

* **Issue**: The Applied Energistics P2P ME Tunnels are not functioning. Other P2Ps like the fluid P2P are working as usual.
The ME Tunnels just say 'device offline', even when connected and paired properly.
I have used P2P Tunnels before and know how they work, so I doubt this is user error.

* **Link to Log or Crash File Paste**: looked through and can't find anything suspicious

* **Is it Repeatable?**: yes, tried different savegames too

* **Mod/s Affected**: Applied Energistics 2 (rv6-stable-6)

* **Known Fix**: -/-

**Comment by Slowpoke101** [comment]
This will probably need to be checked on the AE2 side.
