### ISSUE TITLE
Consistency in gear recipes

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-Sky-Odyssey#226]
I see Tin Gear is the only recipe that forces an iron ingot in the middle, bronze can do both (4 bronze + 1 iron/4 bronze). All other gear recipes doesnt require the iron in the middle. I suggest either make all require the ingot, or make none require it. I suggest require the iron ingot, because then you'll actually benefit from using machine recipes (They dont use the iron ingot). It's a config in /cofh/thermalfoundation/common 

`# If TRUE, non-Basic Gears will require an additional Iron Ingot to craft [default: false]
    B:AlternateGears=false
`

**Comment by TheOfficialButton** [comment]
This is working as intended.
