### ISSUE TITLE
Dispersion spark does not work when over the everlasting guilty pool

### ISSUE THREAD

**Issue by Magnetul** [FTBTeam/FTB-Sky-Odyssey#227]
* **Modpack Version**: 1.0

* **Issue**: I tried using a dispersion spark over the guilty pool to other mana pools with a basic spark over them and there was no mana movement

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Slowpoke101** [comment]
I cannot seem to replicate this 
https://i.imgur.com/FzU9lMT.png
