### ISSUE TITLE
copy nbt of items with emc

### ISSUE THREAD

**Issue by ty802** [FTBTeam/FTB-Sky-Odyssey#228]
<img width="960" alt="javaw_BRZ7IFhGOh" src="https://user-images.githubusercontent.com/31832680/55034263-17fae580-4fe3-11e9-852c-d12aee2065b8.png">
* **Modpack Version**: 1.0 

* **Issue**:if you add an item like a chest transporter or a full tank to the emc link and use a storage bus filtered to the item in the emc link you can pull the exact item i recommend using the partition storage button in the storage bus to reproduce. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:i don't know 

* **Mod/s Affected**:ae2 project EX 

* **Known Fix**: 
<img width="960" alt="javaw_g9SZO0cBgF" src="https://user-images.githubusercontent.com/31832680/55034351-4ed0fb80-4fe3-11e9-95d0-74934c3afb72.png">
<img width="960" alt="javaw_NNVbkOPfHv" src="https://user-images.githubusercontent.com/31832680/55034404-68724300-4fe3-11e9-9b3a-42ef911a79bf.png">

**Comment by Rushmead** [comment]
This is known and will hopefully be fixed in the next update
