### ISSUE TITLE
Creative Builders Wand not working properly

### ISSUE THREAD

**Issue by DeltaCore** [FTBTeam/FTB-Sky-Odyssey#229]
* **Modpack Version**:  1.0.0

* **Issue**: The Creative Builders Wand uses items from the players inventory. As far as my knowledge goes, it's not supposed to do that. I looked up some wikis and all told me that it does not use items from the players inventory. Am i missing something here or is that the way it works in this pack, because then it would be very overpriced with 150k coins vs the unbreakable wand with 1k coins.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Every server i created and tested with my friends, the same thing (i re downloaded the server files multiple times).

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: None

**Comment by DeltaCore** [comment]
Here are some screenshots:
![2019-03-26_22 32 54](https://user-images.githubusercontent.com/5575913/55035272-c91b7300-5017-11e9-8888-46d4a2bde9ee.png)
![2019-03-26_22 32 59](https://user-images.githubusercontent.com/5575913/55035274-c91b7300-5017-11e9-9da2-76a60f897af5.png)
![2019-03-26_22 33 02](https://user-images.githubusercontent.com/5575913/55035275-c91b7300-5017-11e9-8139-b531e9b450ea.png)
![2019-03-26_22 33 05](https://user-images.githubusercontent.com/5575913/55035276-c9b40980-5017-11e9-809c-45737c7dd41f.png)

**Comment by Lost-Ninja** [comment]
As far as I know this is as intended - or certainly the way it has always worked for me. It uses items from the players inventory unless you're in Creative (you still need to have at least 1 of the item you want to place). The creative version of this tool is unbreakable and can place more blocks than the normal one. And I use this and the Destruction one a lot in many different packs.

**Comment by DeltaCore** [comment]
But why is it so expensive? The Unbreakable wand can be bought for just 1k coins against 150k for this one. The destruction one i get, but this one is stupid. What i don't get is why  is every wiki saying that it does **not** use items from the players inventory regardless of the players mode he's in...

**Comment by Slowpoke101** [comment]
Its expensive because it carries the Creative tag, I have not intended to make sure that all items have perfectly balanced prices. You are expected to pay a premium for items that have been deemed creative by the respective mod author.

**Comment by DeltaCore** [comment]
Yeah, balancing is quite the task :D So i gues it is intented that the wand uses the items from the players inventory?

Either way, thanks for the clarification 👍
