### ISSUE TITLE
Spawn Eggs can be made with Mob Grinding Utils

### ISSUE THREAD

**Issue by moustachemuskrat** [FTBTeam/FTB-Sky-Odyssey#232]
* **Modpack Version**: 1.0.0

* **Issue**: You can cheat the spawn egg quests with the GM chicken feed from mob grinding utils. Not sure if this is supposed to happen,

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mob grinding utils

**Comment by sreekrishn** [comment]
the GM chicken feed can be gotten thru mob swab which is juz 2 wool and a stick

**Comment by Naxanria** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/111
