### ISSUE TITLE
Too much EMC

### ISSUE THREAD

**Issue by Rainviper16** [FTBTeam/FTB-Sky-Odyssey#233]
* **Issue**: Around 9.15E EMC the transmutation tablet and table stop accepting items although EMC can still be increased with bonsais and EMC links

* **Is it Repeatable?**: Yes messing around with final stars around this number allowed me narrow it down to around 9.15E EMC possibly less 

* **Mod/s Affected**:  Projecte

* **Known Fix**: just dump EMC but it would be nice to remove the limit or stop EMC gain after that point.

**Comment by piisawheel** [comment]
This bug is due to javascript only being able to store 9.some-odd quintillion.  A fix would involve allowing the item to be learned and just waste extra EMC, instead of preventing insertion.  It's actually a known issue with project E and I imagine that FTB will reject your issue based on that.

**Comment by Naxanria** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/148
