### ISSUE TITLE
Personal EMC Link Issue

### ISSUE THREAD

**Issue by PandaCrazy672** [FTBTeam/FTB-Sky-Odyssey#234]
* **Modpack Version**: 1.0.0

* **Issue**: Whwn you put unlearned items in the personal EMC link, it just transforms it into EMC whithout learning it. (BTW I am using the personal EMC link because i can't use the EMC table due to the large amount of EMC as listed in issue #104 and #95)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectE and Project EX

**Comment by dsabecky** [comment]
This is by design. The personal EMC link is not intended to "learn" items.

**Comment by TheOfficialButton** [comment]
Personal EMC links are not intended to learn items. If your tablet is full. Place the item in the centre on the right hand side and you can learn it that way.
