### ISSUE TITLE
Potion Brewer crash the game

### ISSUE THREAD

**Issue by kenieveges** [FTBTeam/FTB-Sky-Odyssey#239]
Modpack Version: 1.0.0

Issue: "Potion Brewer crash the game when I try to get Awkward Potion

Link to Log or Crash File Paste: N/A

Mod/s Affected: Industrial Foregoing

**Comment by Naxanria** [comment]
Cant do much without a crash report.

**Comment by Naxanria** [comment]
Closing due to lack of information.

**Comment by Flymeck** [comment]
i have the same problem
[crash-2019-07-07_21.12.24-server.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3366023/crash-2019-07-07_21.12.24-server.txt)
