### ISSUE TITLE
Unable to apply Creative Barrel upgrade

### ISSUE THREAD

**Issue by xenoflot** [FTBTeam/FTB-Sky-Odyssey#242]
* **Modpack Version**: 
1.0.0-1.12.2

* **Issue**: 
I got a YABBA "Creative Barrel" upgrade but I'm unable to apply it to a barrel. I tried on both a virgin barrel and one that had been upgraded to Infinite. Found a couple of similar reports on reddit, so reporting it here. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by LatvianModder** [comment]
1. insert item in barrel. 2. rightclick with upgrade on barrel. you cant put upgrade on upgrades or lootcrates

**Comment by xenoflot** [comment]
Thanks for that. As the other upgrades don't require an item to be in the barrel, I didn't think to do that. Perhaps you could add a mention to the tooltip?

Cheers
