### ISSUE TITLE
Android' skin

### ISSUE THREAD

**Issue by PatatoBy** [FTBTeam/FTB-Sky-Odyssey#243]
* **Modpack Version**: 1.0.0

* **Issue**: Cannot see my android skin when plugged up all parts in android station

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: I've been tryied it even in single and multiplayer, same studd 

* **Mod/s Affected**: Matter overdrive

* **Known Fix**:

**Comment by Naxanria** [comment]
Mod is removed in next update.
