### ISSUE TITLE
Unable to craft Flux-Infused JetPlate / Thermal Energy Cells

### ISSUE THREAD

**Issue by martinschuberteu** [FTBTeam/FTB-Sky-Odyssey#244]
Modpack Version: 1.0.0

Issue: To craft the Flux-Infused JetPlate you need a resonant Flux Pack, which requires an Energy Cell (Resonant). There are only recipes for Leadstone Energy Cells and it does not seem to be possible to craft Reinforced or Resonant Energy Cells and thus, impossible to craft the Flux Packs and Flux-Infused JetPlate.

**Comment by Dryxen** [comment]
You should be able to place the leadstone energy cell down and smack a resonant conversion kit on it.

**Comment by martinschuberteu** [comment]
I did not think about that and only ever used the conversion kits on machines. It worked but I still feel like the recipes are missing?

**Comment by Dryxen** [comment]
If i remember correctly it was something that changed with Thermal Expansion 5. Pretty much every thing outside of ducts are upgraded with kits now.
