### ISSUE TITLE
Refined Storage 1k disk drives stored in ProjectE aren't usable

### ISSUE THREAD

**Issue by kkewl** [FTBTeam/FTB-Sky-Odyssey#245]
* **Modpack Version**:  1.0.0

* **Issue**: Created 1k storage drives for Refined Storage.  Stored them as EMC.  As I pull them out they are not usable in disk drive.  the 1k storage parts are usable to build a storage drive that works, but not the completed product.  No errors, just wont take the item.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Refined Storage, ProjectE

* **Known Fix**: Work Around, store the 1k storage part as EMC then craft drive.

**Comment by Wastl-B** [comment]
This is already known and a dupe to [#192](https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/193)

**Comment by Naxanria** [comment]
Duplicate of 192.
