### ISSUE TITLE
Coal Essence

### ISSUE THREAD

**Issue by Etheria137** [FTBTeam/FTB-Sky-Odyssey#246]
* **Modpack Version**: 1.0.0

* **Issue**: When I went to make coal from coal essence it doesn't work. I've tried doing it in a crafting table and auto crafters.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Magical Crops

**Comment by Naxanria** [comment]
![image](https://user-images.githubusercontent.com/3246224/55279711-bbb5ff80-531b-11e9-972d-30c93ff9593a.png)
Seems to work fine for me.
