### ISSUE TITLE
Memory leak in Matter Overdrive

### ISSUE THREAD

**Issue by cpw** [FTBTeam/FTB-Sky-Odyssey#249]
* **Modpack Version**: 1.0.0

* **Issue**: There's a slow but certain memory leak in Matter Overdrive, that is causing lag spikes as it fills memory.
(from class histogram report):
```   1:      12917026     2273396576  matteroverdrive.fx.GravitationalAnomalyParticle```

* **Mod/s Affected**: Matter Overdrive?

**Comment by dsabecky** [comment]
Similar to issue #240, #241, and issue #54.

**Comment by Naxanria** [comment]
@dsabecky This is a memory leak, not a crash due to division by zero.

**Comment by LatvianModder** [comment]
If its particle, I'd assume its only a leak on client. We also suspect a leak on dedi server, havent found it yet

**Comment by Slowpoke101** [comment]
Mod is getting removed in the next update.
