### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by applemes** [FTBTeam/FTB-Sky-Odyssey#25]
When i make a nether portal, and go through, it spawns me in a void looking area.

https://puu.sh/D21Xx/6fb8fe8d5b.png
https://puu.sh/D21XV/d59197094a.png

**Comment by Alfurin** [comment]
That is a skyblock nether make a platform and then mobs start spawning there.

**Comment by applemes** [comment]
Is there anyway to get to like regular nether for the ore and stuff

**Comment by Alfurin** [comment]
All ores can be bought it the store that is how you are suppose to get them

**Comment by applemes** [comment]
ah thanks

**Comment by Naxanria** [comment]
The fortresses do spawn, so you can look for them if you want :)
