### ISSUE TITLE
armour mastery chapter completion

### ISSUE THREAD

**Issue by martinschuberteu** [FTBTeam/FTB-Sky-Odyssey#252]
Modpack Version: 1.0.0

Issue: I've completed all quests in the armour mastery chapter, but did not get the chapter completion. It also says "Complete the Draconic Mastery Chaper" in the tooltip.

![2019-03-29_20 10 24](https://user-images.githubusercontent.com/19508559/55257094-26553580-525f-11e9-8e9e-eb154f03a936.png)

![2019-03-29_20 13 04](https://user-images.githubusercontent.com/19508559/55257098-29e8bc80-525f-11e9-94a1-f981c20d53b9.png)

**Comment by MrGcGamer** [comment]
You just need to craft the Elemtium helmet with the goggles of revealing and you are done

**Comment by martinschuberteu** [comment]
ahhhhh, I'm blind... sorry
