### ISSUE TITLE
Flux Network not working because of Tech Reborn

### ISSUE THREAD

**Issue by MrGcGamer** [FTBTeam/FTB-Sky-Odyssey#253]
* **Modpack Version**: 1.0

* **Issue**: If you connect 2 Devices from Tech Reborn to one Flux Point your whole network breaks and no Flux point in your network is able to output energy

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes, every time you place two devices from Tech Reborn to one flux point

* **Mod/s Affected**: Flux Network v.3.0.19-21, Tech Reborn 2.21.2.960
* **Known Fix**:

**Comment by PatatoBy** [comment]
It happens with MatterOverride stuff

**Comment by Slowpoke101** [comment]
This appears to be fixed in dev, however once the patch is released, if you can let me know if this still exists. I cannot seem to replicate in dev.
