### ISSUE TITLE
Multiplayer server problem

### ISSUE THREAD

**Issue by CrispLake** [FTBTeam/FTB-Sky-Odyssey#254]
* **Modpack Version**: 
FTBSkyOdyssey-1.0.0-1.12.2.
* **Issue**: 
So we are trying to join our server with the mod and it gives just this screen
![sss](https://user-images.githubusercontent.com/49078792/55260398-fd3da080-5270-11e9-906f-9cd18aaef008.PNG)

Also there was a issue made similar to this but it was closed without any real answer so i had to make a new one
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 
Ender IO

**Comment by Naxanria** [comment]
This looks like you added your own mods. As there is No Tinkers and no Open Computers in the pack either, those integrations wont work.
If you didnt, try reinstalling the pack? There is nothing else we can really do about it.
