### ISSUE TITLE
Transmutation tablet lost almost all items

### ISSUE THREAD

**Issue by DocAgro** [FTBTeam/FTB-Sky-Odyssey#255]
Modpack Version:1.00

Issue: Upon a new login I lost almost all items in the transmutation tablet, Still have all the EMC but just a few basic items in there such as wood, marble crafting table and sticks. 
![EMC](https://user-images.githubusercontent.com/49081532/55267198-1c442e80-5281-11e9-86e8-8c340aee9a50.PNG)

**Comment by Junkberry** [comment]
It is weird how some items dissapeared but others are still in there. You could of course learn everything again you had in there or use the book to get all the items in there in the game. Unless someone knows a way to restore it.

**Comment by nzminecraftDOTcom** [comment]
Is this single player or a server. Was the world stopped without properly shutting down and saving all player data? [server] a world rollback may have happened while you were offline or your player file may have been reverted.

**Comment by LatvianModder** [comment]
Looks like corruption to me, nothing else can make your items disappear like that, and we can't fix that
