### ISSUE TITLE
Crash/Corruption building Draconic Pylon

### ISSUE THREAD

**Issue by Vinsombra** [FTBTeam/FTB-Sky-Odyssey#256]
* **Modpack Version**: <1.00>

* **Issue**: Crash/save corruption

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/454533aa

* **Is it Repeatable?**: Sort of.  Everytime i try to start up, it crashes during the mod loading

* **Mod/s Affected**: I don't know if it's at fault, but I was building the Draconic energy storage pylons at the time.

* **Known Fix**: I can't even load the game anymore.

**Comment by LatvianModder** [comment]
Try giving it more RAM, like 4-5 gigabytes, this is a JVM crash, nothing we can do.

**Comment by Vinsombra** [comment]
At 12G, but thanks.

**Comment by Naxanria** [comment]
As this is a JVM crash, sadly we cant do anything about it.
