### ISSUE TITLE
Unplayable

### ISSUE THREAD

**Issue by alper5ozx** [FTBTeam/FTB-Sky-Odyssey#257]
Modpack Version: 1.0.0

Issue: Everytime I walk my screen shakes and creates massive lag
I decrased particles and turned clouds off which was causing the lag

Is it Repeatable?: It happens on every map

[bug.zip](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3025318/bug.zip)

**Comment by MineplayerHDYT** [comment]
try to use Optifine and go to graphic settings - Particles - Animated Terrain Off

**Comment by alper5ozx** [comment]
I changed the algorithm to vanilla and it seems fine

**Comment by Naxanria** [comment]
As this seems fixed, I am closing this issue.
