### ISSUE TITLE
Multiplayer world creation issue

### ISSUE THREAD

**Issue by Ryliia** [FTBTeam/FTB-Sky-Odyssey#259]
* **Modpack Version**: FTBSkyOdyssey-1.0.0

* **Issue**: Created a multiplayer world, but spawned on a normal world. When A team was created, it made an island but the normal world was still below.

* **Link to Log or Crash File Paste**: no crash file

* **Is it Repeatable?**: it is repeatable

* **Mod/s Affected**: n/a

* **Known Fix**: no known fix

**Comment by hitmafia** [comment]
Hi, were you able to solve this issue? I am having the same problem.

**Comment by pkpn** [comment]
I am having the same issue. Seems like it doesn't spawn in a void world type of map. :/

**Comment by Naxanria** [comment]
There should be a default world for multiplayer with the server files.

**Comment by pkpn** [comment]
> There should be a default world for multiplayer with the server files.

Even with the server files there is not a default world for multiplayer. At least there wasn't any for me.
I fixed it by changing the Level-type=DEFAULT from "DEFAULT" to "void_world".

**Comment by moonbeast32** [comment]
I had this issue too when trying to create a multiplayer world. I tried deleting the Heaven Release maps to no effect. I eventually did what Pkpn did, and made the world a void type. I feel like that isn't a sure solution though
