### ISSUE TITLE
Stalling on load on Manjaro linux

### ISSUE THREAD

**Issue by terrigan** [FTBTeam/FTB-Sky-Odyssey#26]
Modpack has been loading for the last 25 minutes. it seems to get to certain mods and stalls. I've noticed it stall on the backpack mod in phase 1. It's now on phase 3 and stuck on Xaero's minimap. Running java 8.0.202. I have adjusted  the amount of ram for the launcher from 5 to 6gb. The modpack never seems to use more than 2gb. The game eventually crashes back to the launcher and doesn't actually load. Most likely same issue as #27.

**Comment by terrigan** [comment]
Hmm.. today it loaded fine.. I'll keep an eye on it.

**Comment by TheOfficialButton** [comment]
Please resubmit this again if this issue continues
