### ISSUE TITLE
Mana Spreader not spreading to Pool

### ISSUE THREAD

**Issue by MySickBananas** [FTBTeam/FTB-Sky-Odyssey#261]
* **Modpack Version**: <1.0.0>

* **Issue**: <When using Mana Spreader from Botania, when linked to the Mana Pool, it does not spread to the pool therefore not allowing the pool to fill up. I moved the spreader and pool in many locations and made sure that the Endoflames were functioning correctly.>

* **Link to Log or Crash File Paste**: <please use http://paste.feed-the-beast.com/ to paste the text of your log/crash file>

**Comment by Naxanria** [comment]
Did you link the Endoflames to the spreader? After moving/placing a spreader tehy are not automatically linked. They will link if you place the Endoflame after you placed a spreader, as they will link to the closest.

**Comment by Naxanria** [comment]
Closed for lack of information and cant reproduce.

**Comment by LilMxPlagueRat** [comment]
Hi, I know you've closed this but I'm having the exact same issue, I started on the default world on easy, I've not changed anything in the configs and I'm playing Version 1.1.0
![image](https://user-images.githubusercontent.com/23294423/58373583-3cface80-7f28-11e9-8453-b693d33c43e5.png)
![image](https://user-images.githubusercontent.com/23294423/58373589-57cd4300-7f28-11e9-8c17-6f58e88c0add.png)
