### ISSUE TITLE
Game Crash while crafting wireles terminal + crafting terminal

### ISSUE THREAD

**Issue by Easyjo4** [FTBTeam/FTB-Sky-Odyssey#263]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Easyjo4** [comment]
Game crashed while crafting in Me craft. terminal

**Comment by Naxanria** [comment]
duplicate of #165
