### ISSUE TITLE
Tardis Blueprint recipe

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-Sky-Odyssey#265]
* **Modpack Version**: 1.0.0

* **Issue**: Tardis Blueprint has no recipe, so a no shop run is impossible.

**Comment by dsabecky** [comment]
@Naxanria Would this also include making the Miner, and Assembling Machine (Tech Reborn) craftable?

**Comment by Naxanria** [comment]
@dsabecky Maybe make a separate issue for that :)

**Comment by dsabecky** [comment]
@Naxanria There ya go boss. <3

**Comment by Slowpoke101** [comment]
The tardis does not need the blueprint to load.
