### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by NarwhalAssassin** [FTBTeam/FTB-Sky-Odyssey#269]
* **Modpack Version**: 1.0.0

* **Issue**: After opening a world to LAN and closing it, attempting to open any world in single player (including creating a new world) results in a "Connection Lost: Server not found" error

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a647c1c2

* **Is it Repeatable?**: Yes

**Comment by nzminecraftDOTcom** [comment]
[16:17:56] [Client thread/INFO]: [CHAT] §e§l[Config Checker] You only have 2.7 GB of RAM assigned to this modpack. You may expierence performance issues.

Says it all right there in the first few lines of your log.
Give the pack more ram, 4-6gb should be plenty.

**Comment by Naxanria** [comment]
2.7 GB should be enough to open a world at least.
Opening to LAN seems to give Minecraft some troubles, not much we can do about as this seems to be a vanilla problem.
