### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Krysommor** [FTBTeam/FTB-Sky-Odyssey#27]
while loading the mod pack it seems to be slow loading, I have allocated 8gb ram and it getting stuck at 3/5 in the loading. is there anything I can do to improve this?

**Comment by Krysommor** [comment]
same issue as #26 was using the twitch launcher and tested with native and jar formats and both the same

**Comment by Naxanria** [comment]
If you have a log for when it hangs, we could help a bit better. (There is an option in twitch to keep launcher open when starting/playing MC)

**Comment by Krysommor** [comment]
I will try to look into it but on first load there was 4 fatal errors, at the moment I have deleted all and see if a fresh install would help. just keep this open to see if anyone else gets it

**Comment by Slowpoke101** [comment]
Krysommer can you confirm if this is still an issue. If this is still an issue can you try something for me? If you are using the twitch app, at the top right go to Get more content, then untick 'Locked' this should allow you to see a new option to the left of the mods listed in the pack. Scroll down till you see the mod called Splash Animation. Uncheck this option to disable that mod and then try loading the pack again. If you can reply here letting me know if this has any effect, I would be grateful.

**Comment by Krysommor** [comment]
Hi there slowpoke, sorry that I have not got back sooner, the issue has resolved it self and I am using the twitch launcher, I don't know how it fixed itself but all better.
