### ISSUE TITLE
Lack of recipe cannot complete q

### ISSUE THREAD

**Issue by d1ronin** [FTBTeam/FTB-Sky-Odyssey#270]
* **Modpack Version**:  FTB-Sky-Odyssey v. 1.0.0.

* **Issue**: Can not craft ic2 reinforced stone because no valid recipe 
* **Mod/s Affected**:  pattern storage and replicator are noot craftable

**Comment by monokin1114** [comment]
you craft it by spraying construction foam on to iron scaffolding

**Comment by sLpFhaWK** [comment]
This is how you do it. I had to check the Wiki for the mod on how to complete this.

**Comment by Naxanria** [comment]
Oh I see, I was not aware of that. In that case I am closing this issue.
