### ISSUE TITLE
game keeps crashing when i log onto a server

### ISSUE THREAD

**Issue by Gleebie** [FTBTeam/FTB-Sky-Odyssey#272]
Modpack Version: 1.0,0

Issue: My game keeps on crashing when ever i try to join a server

Link to crash: https://paste.feed-the-beast.com/view/d6a023f3

Is it repeatable?: Yes

Mod's affected: Not sure

If anyone knows a fix please tell me :D

**Comment by Naxanria** [comment]
This is a bug fixed in next update. To fix it, dont look with the better builders wand at the Solar Panels. As you are on a server, maybe someone can remove the solar panels so that doenst happen?

**Comment by Gleebie** [comment]
It worked thanks :D
