### ISSUE TITLE
Fusion crafting stuck at 99% | spawn blaze quest

### ISSUE THREAD

**Issue by DemonMadd** [FTBTeam/FTB-Sky-Odyssey#274]
* **Modpack Version**: Sky Odyssey 1.0

* **Issue**: charging stuck at 99% when fusion crafting blaze egg, i have enough power to complete.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by dsabecky** [comment]
This means one (or more) of your injectors isn't getting enough power or being blocked by an object. Make sure your edge injectors arent overlapping at the item block (in front of it).

**Comment by DemonMadd** [comment]
w

> This means one (or more) of your injectors isn't getting enough power or being blocked by an object. Make sure your edge injectors arent overlapping at the item block (in front of it).

whats the best design for 28 injectors

**Comment by dsabecky** [comment]
@DemonMadd I can include screenshots of my setup when I get to my home computer. Can you include screenshots of your setup? List the connections as well (how are the injectors receiving power, etc).

**Comment by dsabecky** [comment]
@DemonMadd Here are the screenshots (tried to get multiple angles for you) of a working 28 injector setup.
![2019-04-02_20 26 02](https://user-images.githubusercontent.com/778367/55444699-a17f5a00-5585-11e9-88e9-454cf080061d.png)
![2019-04-02_20 26 06](https://user-images.githubusercontent.com/778367/55444700-a17f5a00-5585-11e9-8630-3c8107976cde.png)
![2019-04-02_20 26 12](https://user-images.githubusercontent.com/778367/55444701-a17f5a00-5585-11e9-8506-a4d7bb96d827.png)
![2019-04-02_20 26 14](https://user-images.githubusercontent.com/778367/55444702-a17f5a00-5585-11e9-9ae6-c1885d4a13e9.png)

**Comment by obstinate3** [comment]
It is 27
