### ISSUE TITLE
Woot farm will not work

### ISSUE THREAD

**Issue by Thor-Axe** [FTBTeam/FTB-Sky-Odyssey#276]
* **Modpack Version**: Sky Odyssey 1.0.0

* **Issue**: After building tier 4 Woot farm, Factory Heart UI will not open when right clicked on. In addition, Power cell will not accept power from Flux Point or Ender IO Conduits.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Woot

* **Known Fix**: None

**Comment by dsabecky** [comment]
Can you take a screenshot of it? What factory controller are you using (mob)? Did the multiblock fully form?

**Comment by Thor-Axe** [comment]
![2019-04-02_18 45 13](https://user-images.githubusercontent.com/49215767/55447286-fcaa5000-5577-11e9-9b4c-0d3e27862ae9.png)
I am using the wither controller. And how do i know if the multi block fully formed? I'm pretty sure i had all of the blocks needed.

**Comment by dsabecky** [comment]
You'll know when it forms when all the gaps between the blocks close, it'll become one big piece. Did you place those by hand or use The Intern to place them?

**Comment by Thor-Axe** [comment]
I used the intern

**Comment by dsabecky** [comment]
And you placed the power cell, importer, and exporter (in that order) below the factory heart (no more than 10 blocks away)

**Comment by Thor-Axe** [comment]
That did it, i didn't realize the order of those blacks mattered. Thank you so much.
