### ISSUE TITLE
Twitch download times out

### ISSUE THREAD

**Issue by TheNubbler** [FTBTeam/FTB-Sky-Odyssey#278]
* **Modpack Version**: Current downloadable

* **Issue**: When attempting to download/install modpack from the twitch app, I get the foollowing error: Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip

I'll be the first to admit I don't have the most stable internet, but I certainly stream netflix/youtube. I also downloaded and play FTB Ultimate Reloaded just fine.

I saw a small handful of users have the same issue, but couldn't find a fix.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

**Comment by TheGeekFire** [comment]
me too it's the same problem

**Comment by SoLaRzz** [comment]
same here

**Comment by Star1369** [comment]
I'm having the same issue

**Comment by dsabecky** [comment]
See ftbteam/ftb-sky-odyssey/readme.md

**Comment by Naxanria** [comment]
You can try downloading it through the curseforge page ( https://www.feed-the-beast.com/projects/ftb-sky-odyssey/files/ ) and then importing it into the twitch launcher ( Create Custom Profile -> import -> select the file )
Other than that, not much we can do about.

**Comment by LatvianModder** [comment]
Not a modpack issue, this is a Twitch issue
