### ISSUE TITLE
fused quartz cannot be inserted into Induction Smelter

### ISSUE THREAD

**Issue by youwebaba** [FTBTeam/FTB-Sky-Odyssey#28]
HardenedGlass unobtainable using Induction Smelter

**Comment by Svannon** [comment]
Default Recepie works just fine. 1 Pulverized lead = 4 Pulverized obsidian.

**Comment by TheOfficialButton** [comment]
Hardened glass is able to be created in an Induction Smelter with Lead and obsidian.
