### ISSUE TITLE
Object refence not set to instance of an object

### ISSUE THREAD

**Issue by LooseVALVe** [FTBTeam/FTB-Sky-Odyssey#280]
* **Modpack Version**: Current downloadable

* **Issue**: Trying to install, Twitch app just tells me "object of reference not set to instance of an object"

* **Is it Repeatable?**: Yes, everytime I try to install.

* **Mod/s Affected**: All of them?

**Comment by dsabecky** [comment]
See README:
https://github.com/FTBTeam/FTB-Sky-Odyssey/blob/master/README.md

**Comment by Naxanria** [comment]
See if the solution for https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/278 works.
