### ISSUE TITLE
just a question 

### ISSUE THREAD

**Issue by aliyar15** [FTBTeam/FTB-Sky-Odyssey#281]
can i still farm game over loots with Woot? it doesnt show on the Woot configuration that wither drops a game over loot

**Comment by dsabecky** [comment]
Yes they are.
Read more here: https://www.reddit.com/r/feedthebeast/comments/b4m71v/sko_game_over_loot_bags/

**Comment by JankoGoo** [comment]
Max out the fortune.

You're welcome. :D

**Comment by aliyar15** [comment]
I did from the beginning. That is not much help

**Comment by JankoGoo** [comment]
Weird... works for me in 1.0.0 tho.

**Comment by dsabecky** [comment]
@aliyar15 Read the post I linked, it is possible, HOWEVER it does require some RNG.

**Comment by aliyar15** [comment]
Ye I read that thanks

**Comment by Naxanria** [comment]
Yes, it is a chance you get it or not.
