### ISSUE TITLE
Creative energy source EU2 -> creative solar panel TR

### ISSUE THREAD

**Issue by obstinate3** [FTBTeam/FTB-Sky-Odyssey#283]
Switch in shop, cause the solar panel should be better for servers than the energy source

**Comment by dsabecky** [comment]
The Creative Energy Source (Extra Utilities 2) creates grid power, while the Creative Solar Panel (Tech Reborn) generates forge energy. Grid Power operates differently than other "regular" power sources (rf/fe/cf/eu/j/etc) in that it can't be convereted. Maybe I'm misunderstanding what you're saying @obstinate3, but what do you mean "better for servers"?

**Comment by Naxanria** [comment]
Creative energy Source from EU2 creates forge energy, same as that solar panel. The creative mill is the GP generating one.
It is better for servers as in they produce less lag.

**Comment by dsabecky** [comment]
@Naxanria thanks for the correction.

**Comment by MrNinja93** [comment]
I would second removing the ex utils creative energy source in favour of some other mods creative energy.

Extra Utilities one is absolute trash on a server I've had to swap the shop/loot chest over to draconic evolutions creative energy and replace in world ones.

**Comment by ThePoet444** [comment]
This isn't concrete evidence by any means.. but I was having some block breaking lag on my single player world. (My computer isn't a complete potato mind). I replaced all the ExU2 creative energy sources with draconic ones and my game is monumentally improved.
