### ISSUE TITLE
Project EX Crashes Game with AE2 Autocrafting

### ISSUE THREAD

**Issue by MarsOnion** [FTBTeam/FTB-Sky-Odyssey#284]
Modpack Version: 1.0.0

Issue: Using AE2 Patterns to autocraft crashes the game whenever a compressed EMC Link is connected to the AE2 Controller via Storage Bus. 

Link to Log or Crash File Paste: Is it Repeatable?: Yes

Mod/s Affected: Project EX, Applied Energistics 2

Known Fix: According to my testing, as well as the help of a wonderful redditor, if Project EX is updated (current version is 1.1.0.14) to 1.1.0.18, Latvian has added a config option to change the Max Output of the EMC Link, as opposed to maxing out at 2 Billion by default. If this config is changed to a much smaller, more manageable value, such as 200,000, then the game no longer crashes when autocrafting with the AE2 system. This fixed the issue for me.

**Comment by Naxanria** [comment]
See https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/84
