### ISSUE TITLE
Wireless Universal Crafting Terminal not crafteable.

### ISSUE THREAD

**Issue by xxBLoS** [FTBTeam/FTB-Sky-Odyssey#288]
* **Modpack Version**: 1.00

* **Issue**: Wireless Universal Terminal not craftable (like in JEI described). When I get it in Creative it works. But Im not able to craft in it. Dispite it says in the description that I should be able to craft items inside.

* **Mod/s Affected**: Applied Energistics 2 & Extra Cells 2

**Comment by Naxanria** [comment]
You need to use different type of screen than the wireless terminal (eg. fluid terminal, item crafting terminal) You combine the functionality of both.

**Comment by xxBLoS** [comment]
No its not like that. I tried that but no result in the crafting grid. After giving myself one universal wireless terminal (in creative) I tried it again and didnt work too. The description of the item (Wireless Universal Terminal) is that the modes Item, Fluid, Gas and Crafting are Installed. But I can only change (with Shift Rightclick) between Fluid and Items. But no craftin grid in there.

**Comment by Naxanria** [comment]
Ok, I misread your issue.
