### ISSUE TITLE
Dimension X quest should be linked.

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-Sky-Odyssey#289]
* **Modpack Version**: 1.0.0

* **Issue**: Dimension X quest can be completed before completing the final quests.

* **Known Fix**: Make Dimension X be a dependency to the final quests.

**Comment by LatvianModder** [comment]
🤔

**Comment by dsabecky** [comment]
This could prevent people on a server from visiting someone elses island and completing the quest prematurely. It's not really an issue (in my opinion), but it makes sense that it would be linked to all the other "final" quests.
