### ISSUE TITLE
Cannot create a test world

### ISSUE THREAD

**Issue by mtjohnson47** [FTBTeam/FTB-Sky-Odyssey#29]
There is no way to set a world to creative or enable cheats when making a new world.

**Comment by Firefox37** [comment]
open to LAN then enable cheats.

**Comment by mtjohnson47** [comment]
Yes.  Every time you load it, should have an option when making world

**Comment by Naxanria** [comment]
It purposefully has not, you could add a mod to enable cheats from the main menu :)
