### ISSUE TITLE
Recipes for "shop only" items

### ISSUE THREAD

**Issue by dsabecky** [FTBTeam/FTB-Sky-Odyssey#290]
* **Modpack Version**: 1.0.0

* **Issue**: Tardis Blueprint (issue #265), Assembling Machine, and Beast Coin Miner have no recipe, so a no shop run is impossible, as they are required to complete quests.

**Comment by obstinate3** [comment]
Tardis blueprint recipe is not needed

**Comment by dsabecky** [comment]
@obstinate3 you put the recipe into the controller block once you build it. Yes, you need the recipe.

**Comment by LoveAlmstrom** [comment]
You do not have to put it in there

**Comment by Slowpoke101** [comment]
Added these 2 items as quest rewards, allowing the no shop run to be completed.
