### ISSUE TITLE
AE2WTLib cant be used

### ISSUE THREAD

**Issue by Menphis88** [FTBTeam/FTB-Sky-Odyssey#291]
* **Modpack Version**: 1.0.0

* **Issue**: AE2 Wireless Terminals mod added, though no terminals support it. Making Infinity Booster Cards useless.

* **Link to Log or Crash File Paste**: No logs

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2WTlib - AE2

* **Known Fix**: Unfortunately i dont know, since the mod does not have its own terminal anymore.

**Comment by Naxanria** [comment]
This does indeed seem to be the case.
