### ISSUE TITLE
Fusion Control Computer can't charge

### ISSUE THREAD

**Issue by ASDG8632** [FTBTeam/FTB-Sky-Odyssey#292]
* **Modpack Version**: 1.0.0

* **Issue**: Fusion Control Computer can't charge
![圖片](https://user-images.githubusercontent.com/31956417/55619989-6753c980-57cc-11e9-9c77-63925d23edfb.png)

**Comment by Naxanria** [comment]
It does charge, but you need to put energy in from the side.
