### ISSUE TITLE
Problems with my world i think!

### ISSUE THREAD

**Issue by h03ga4rd3n** [FTBTeam/FTB-Sky-Odyssey#293]
Version: 1.0

Issue: Sometimes when i close my world and reopen it, my inventory is diferent, i lose things, on EMC table i have to burn some things that i already did. I don't know if its a problem with just my world, or with the mod pack, i really don't know but im kinda angry because it already happend like six times!

Is it Repeatable?: yeah

**Comment by Naxanria** [comment]
This sounds like a corruption with your world. Nothing we can do about.
Maybe try using a backup and see if that works.
