### ISSUE TITLE
stuck loading the game

### ISSUE THREAD

**Issue by gameking79** [FTBTeam/FTB-Sky-Odyssey#294]
my game keeps loading on the mod let's encrypt craft when i start up my game 

![loading](https://user-images.githubusercontent.com/49314077/55635272-95331100-57c0-11e9-8c71-ab0f5ab5b3e3.png)

**Comment by Naxanria** [comment]
This might be because you have an older version of Java, try updating that.

**Comment by gameking79** [comment]
And where do i update java via curse launcher?
________________________________
Van: Naxanria <notifications@github.com>
Verzonden: Friday, April 5, 2019 5:37:54 PM
Aan: FTBTeam/FTB-Sky-Odyssey
CC: gameking79; Author
Onderwerp: Re: [FTBTeam/FTB-Sky-Odyssey] stuck loading the game (#294)


This might be because you have an older version of Java, try updating that.

**Comment by gameking79** [comment]
i updated my java and it still does the same thing i tried to redownload several times still nothing

**Comment by Naxanria** [comment]
Do you have any logs/crash reports of this?

**Comment by gaypenguinz** [comment]
i have the same problem but i dont even get to the loading page :L

**Comment by gameking79** [comment]
I found out what the issue was every time i started up my game and it starts loading i go in task manager and somewhere in background processes it started running the minecraft launcher 2times i closed both of them and then it start loading again.
i dont know if this is gonna help with your issue butt maybe its worth trying


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: gaypenguinz <notifications@github.com>
Verzonden: Sunday, May 5, 2019 11:38:58 PM
Aan: FTBTeam/FTB-Sky-Odyssey
CC: gameking79; Author
Onderwerp: Re: [FTBTeam/FTB-Sky-Odyssey] stuck loading the game (#294)


i have the same problem but i dont even get to the loading page :L
