### ISSUE TITLE
Uncompletable Quests

### ISSUE THREAD

**Issue by Flemmli97** [FTBTeam/FTB-Sky-Odyssey#296]
* **Modpack Version**: 1.0.0

* **Issue**: There are currently 3 uncompletable quests: Factory Heart (Woot), Stabilized Spawner (Draconic Evolution) and Ejector Upgrade (Industrialcraft 2). Seems like its a nbt issue or something like that

**Comment by jonlukew** [comment]
I believe the development team are already aware of these three issues. Is this correct @Slowpoke101?

**Comment by Naxanria** [comment]
These issues are fixed in the update.
