### ISSUE TITLE
stuck loading 

### ISSUE THREAD

**Issue by gameking79** [FTBTeam/FTB-Sky-Odyssey#297]
my game keeps loading on the mod let's encrypt craft when i start up my game

![loading](https://user-images.githubusercontent.com/49314077/55667812-9700e100-5861-11e9-960e-20a85cf978ba.png)

**Comment by nzminecraftDOTcom** [comment]
How much ram have you allocated to the game through the FTB/Twitch launcher?

**Comment by gameking79** [comment]
9GB

**Comment by Naxanria** [comment]
Duplicate of #294

**Comment by gameking79** [comment]
stop closing this it isnt fixed bro

**Comment by Naxanria** [comment]
I closed other one by accident, reopened it and waiting for more info there.
