### ISSUE TITLE
Game Crash While Loading NBT Data

### ISSUE THREAD

**Issue by Revv1e** [FTBTeam/FTB-Sky-Odyssey#298]
* **Modpack Version**: 
1.0.0
* **Issue**: 
Crash on world load due to NBT Values, upon reading the crash report, my suspicions are on the power flowers.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/54aa5b0a
* **Is it Repeatable?**: 
Yep, whenever I load the world.
* **Mod/s Affected**: 
Possibly ProjectEX
* **Known Fix**: 
Dunno any, however I tried deleting forcedchunk.dat from the world folder and nothin

**Comment by Naxanria** [comment]
This looks like a corrupted world. Will look into it but most likely nothing we can do about it.

**Comment by Revv1e** [comment]
Ah crap, really?? I even spent so long to make sure everything was all pretty compared to my other bases.
If in the end there is no fixing it, would you be able to tell what caused the corruption? So as to prevent this from happening. Thanks for the quick answer!

**Comment by nzminecraftDOTcom** [comment]
looks like your issue is at (-5,92,-5) in your overworld
Region file r.-1.-1.mca needs to be opened in an NBT editor, you need to locate chunk -1,-1 and find the block projectex:power_flower block data value 6
Remove that, try again

OR load from a backup that your game should have created.

**Comment by Revv1e** [comment]
I can't find chunk -1,-1 while searching through r.-1.-1.mca...Hmm I'll keep searchin through all of these, maybe I can find it somehow!

**Comment by Revv1e** [comment]
Alrighty so, an update, I've deleted that block...but more blocks came into problem and keep crashing my game, a personal emc link which I deleted and now a tile.null// codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block.....

couldn't quite find the block whilst searching through the regions so I'm going to have to....welp, delete the world and start again, or at the very least, I'm going to MCEdit all modded blocks out of here so I can at least spare myself having to remake everything, thanks for the help though guys.

**Comment by Revv1e** [comment]
UPDATE, I deleted all EMC Links and Powerflowers, my suspicions is that something must have gone wrong when adding more value to my emc....so yeah

Guess case closed! Thanks for the help guys!!

**Comment by Naxanria** [comment]
Glad it is fixed :)
