### ISSUE TITLE
Very glitchy  time in a bottle

### ISSUE THREAD

**Issue by TZ47** [FTBTeam/FTB-Sky-Odyssey#299]
* **Modpack Version**: 1.0.0 (+optifine tested the same thing without it, same issue)

* **Issue**: With one click it looks and acts properly, however with  the next clicks it will not update nor speed up properly, it takes me about 30 clicks minimum to get to tier 2 speed up, and i have only once gotten it to work for the tier 3 speed up 

* **Link to Log or Crash File Paste**: no crashing

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Random Things

* **Known Fix**: oddly it seems you can reach higher tiers by not being focused on minecraft and doing something else (as in opening chrome and typing this)

**Comment by Naxanria** [comment]
Every extra tier of speeding up cost more. 
https://lumien.net/rtwiki/items/time-in-a-bottle/

**Comment by TZ47** [comment]
Thank you I am stupid
