### ISSUE TITLE
Aspen & Boreal maps appear to be swapped

### ISSUE THREAD

**Issue by mtjohnson47** [FTBTeam/FTB-Sky-Odyssey#30]
The Aspen map has a huge spruce tree reminiscent of a boreal forest.  The Boreal map has 3 jungle trees which don't make any sense in the context of Boreal.

**Comment by Jake-E** [comment]
Interesting. This may have been a mix up when setting the names. Will look into it.

**Comment by Slowpoke101** [comment]
fixed
