### ISSUE TITLE
Industrial Foregoing  + Mystical Agriculture

### ISSUE THREAD

**Issue by jonalange** [FTBTeam/FTB-Sky-Odyssey#300]
* **Modpack Version**: 1.00

* **Issue**: It seems like that Industrial Foregoing isnt working with Mystical Agriculture. The Plant Interactor and the Plant Gatherer both of them cant pick up a fully grown MA Plant (in our case draconium). It works with normal vanilla seeds.

* **Mod/s Affected**: Industrial Foregoing, Mystical Agriculture

**Comment by LoveAlmstrom** [comment]
The gatherer works just fine for me, not interactor though

**Comment by jonalange** [comment]
> The gatherer works just fine for me, not interactor though

Well, my bad. I placed the gatherer wrong. But still. I think the interactor should work.

**Comment by Naxanria** [comment]
Confirmed, the interactor doesnt work. But as the gatherer works, I suggest using that one :D
