### ISSUE TITLE
A little Help

### ISSUE THREAD

**Issue by Fistandantilus1** [FTBTeam/FTB-Sky-Odyssey#302]
* **Modpack Version**: FTBSkyOdyssey- 1.0.0

* **Issue** I was just wondering why I can't use creative mode. I was trying to create a test world for the pack. But it keeps telling me that I dont have permission....

**Comment by jonalange** [comment]
Try open to lan and enable cheats.

**Comment by Naxanria** [comment]
What xxBLOS said, or install Enable Cheats mod.
Opening to lan can crash the game and corrupt your world so I would suggest installing the mod.

**Comment by Fistandantilus1** [comment]
Thx. It worked.
