### ISSUE TITLE
Mod sugestion for refined storage

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Sky-Odyssey#303]
I would love to see 

https://minecraft.curseforge.com/projects/equivalent-integrations

for beter refined storage integration with project-e

cant get external storage working with the tablet

**Comment by Naxanria** [comment]
As Project EX is in, you can use a Personal Link and choose what item to have as an output slot (or slots for the higher tiers). And put an external storage on that to see it inside RS.

**Comment by djoey123** [comment]
Then you cant access all the items sadly

**Comment by Naxanria** [comment]
You need to manually set them. But as that functionality is already in, the mod has no need to be added.

**Comment by djoey123** [comment]
Okey would be easier but will try that
