### ISSUE TITLE
Crashing after placing multiple solar panels/crashing on world load

### ISSUE THREAD

**Issue by Hanger84** [FTBTeam/FTB-Sky-Odyssey#304]
* **Modpack Version**: 1.0.0

* **Issue**: Cashing and possible world corruption after placing multiple solar panels. I was using these same solar panels for a few days without issue. I got 64 of them out of the EMC table and placed 32 of them before the pack crashed, but now the world crashes as soon as it loads.

* **Link to Log or Crash File Paste**:  Initial crash: https://paste.feed-the-beast.com/view/a111f5c9
Second crash, immediately after loading the world: https://paste.feed-the-beast.com/view/24518599

* **Is it Repeatable?**: Yes, the game no crashes every time I load the game

* **Mod/s Affected**: Uncertain, but likely the mod the solar panels are from (don't remember which)

* **Known Fix**: None so far

**Comment by Naxanria** [comment]
This is fixed in next update. 
When having a builderwand in hand and looking at a solar panel, it crashes.
So either not looking/removing the wand temporarily will fix this for now.
