### ISSUE TITLE
camera/movement/everything glitches

### ISSUE THREAD

**Issue by Sip147** [FTBTeam/FTB-Sky-Odyssey#305]
* **Modpack Version**:Sky Odyssey 1.12.2 (1.0.0) ftb launcher

* **Issue**:Okay so basically my game went nuts.My arms and legs were twisting and going everywhere and when i tryed to move my camera it just went somewhere in the sky and didnt come back down for about 5 seconds

* **Link to Log or Crash File Paste**:idk what this is

* **Is it Repeatable?**: yes

* **Mod/s Affected**:my whole game

* **Known Fix**:idk

and also i cant post videos or pictures here

**Comment by Sip147** [comment]
i reinstalled and it fixed itself

**Comment by Naxanria** [comment]
As that seems fixed I am closing it.
