### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: 9

### ISSUE THREAD

**Issue by DaBosSauce** [FTBTeam/FTB-Sky-Odyssey#308]
The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: 9

Crash Report Linked
[crash-2019-04-07_20.35.01-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3052240/crash-2019-04-07_20.35.01-client.txt)

If you need any other data/info please lmk and I can provide!

**Comment by Naxanria** [comment]
This bug has been resolved in the next update.
See #304 also
