### ISSUE TITLE
The Transmutation Table/Tablet has multiple of the same item

### ISSUE THREAD

**Issue by v-andiar** [FTBTeam/FTB-Sky-Odyssey#310]
v1.0.0

When opening the Transmutation Table, there is multiple of a single item. This does not cause any issues with duping or game mechanics, however, it does take up space, and it is extremely annoying to have to scroll to twenty pages to access diamonds. At first, this happened only to items with durability, such as the Morning Star, or TE machines, so it wasn't such a big of a deal. Also, there were only two "items" shown. But now, almost every item has 3-5 duplicates. It happened after I crafted the Matter Overdrive: Legacy Edition battery. I don't know how it would possibly affect the Transmutation Tablet, but it did.

No crash report, since the game didn't crash

I guess crafting the batteries should recreate the issue, but I'm not sure it will work 100% of the time

Restarting the game and launcher does work, but my computer isn't the best (loading  the game takes cca. 20 mins) so it is kinda annoying

**Comment by Naxanria** [comment]
This is a visual glitch, relogging usually fixes it.
We cant do anything about it.

**Comment by Buffbud96** [comment]
I had this same problem, as soon as i added Matter Overdrive: Legacy Edition items to my tablet, everything started duping, i create a new EMC item and add it, dupped, I try to remove the Matter Overdrive: Legacy Edition items from my EMC stuff, dupped, i ened off with like 18-ish duped of EVERYTHING. Thankfully relogging DID FIX IT!!! Thank you!
P.S. It is NOT visual. At the amounts of dupes i had, it was severely lagging my game

**Comment by fEdlbV9IdW50ZXJ8** [comment]
I had this happen when I registered the philosopher's stone in the table, and this was before using anything from Matter Overdrive. it also happened with quartz seeds, also before I interacted with Matter Overdrive at all. I am using the standard Transmutation table, not the stone one from ProjectEX. (it did crash later when I registered batteries from Matter Overdrive, as well).

**Comment by Buffbud96** [comment]
> I had this happen when I registered the philosopher's stone in the table, and this was before using anything from Matter Overdrive. it also happened with quartz seeds, also before I interacted with Matter Overdrive at all. I am using the standard Transmutation table, not the stone one from ProjectEX. (it did crash later when I registered batteries from Matter Overdrive, as well).
that is very strange... and although this issue is supposedly only visual, it seems to be happeing to many people, and it slows the game, and in this case it made one person crash... I feel like this issue should be re-opened...
