### ISSUE TITLE
Old bugs fixed?

### ISSUE THREAD

**Issue by jonalange** [FTBTeam/FTB-Sky-Odyssey#311]
When will there be an update for all the bugs and fixes? I saw that the ME with EMC autocraft thing is fixed with a new version of the mod (saw it in an issue post). But its still not working for me. 
For me the modpack is still on 1.0.0 
When will there be an update?
Sorry for this post, its not really an issue but I dont know where else to ask you.
Thanks and great work on the modpack!

**Comment by Naxanria** [comment]
You can always check https://www.twitch.tv/slowpoke101 for those type of questions.
The update should be out today.
