### ISSUE TITLE
spawning in the void

### ISSUE THREAD

**Issue by draconickage** [FTBTeam/FTB-Sky-Odyssey#313]
version 1.0.0

iv been trying to create a server so i can play with my friend but when i log into the server i just keep falling into the void

i can clearly see the hub above me, but i keep spawning next to it/ below it

any solutions for this?

**Comment by Naxanria** [comment]
Fly up (when OP /fly is available or go into creative) and do /setspawn.

Let me know if that worked.

**Comment by draconickage** [comment]
okay now i dont die 'instantly' when i spawn but when i try to join a team there isnt an icon for it (see pic)

![Capture](https://user-images.githubusercontent.com/49420016/55806805-4bf50100-5ae1-11e9-9371-0c0c2402cb01.PNG)
![Capture2](https://user-images.githubusercontent.com/49420016/55806806-4c8d9780-5ae1-11e9-93be-5ebf8e43528d.PNG)

**Comment by Naxanria** [comment]
Make the sidebar button for teams be green (in the sidebar buttons screen). Then it will show up.
Glad you managed to not continuously fall :D
