### ISSUE TITLE
New Update Broke Server

### ISSUE THREAD

**Issue by artilon** [FTBTeam/FTB-Sky-Odyssey#317]
* **Modpack Version**: Sky Odyssey 1.1.0

* **Issue**: Updated client and server to new update. Logged into server, every block replaced with random other blocks which destroyed any and all automation and energy creation I had worked for a week on.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Every time

* **Mod/s Affected**: Whole Mod pack

* **Known Fix**: Delete and move on to another mod pack

**Comment by Naxanria** [comment]
Try to use a backup and update. If that doenst work, try loading the map in single player and see if that helps.

**Comment by MrGREGhimself** [comment]
Please be aware that this pack is still a BETA and mods can be added and/or removed and by extension corrupt the world.
