### ISSUE TITLE
Draconic Armor and Tool Upgrades 

### ISSUE THREAD

**Issue by DestinedByte** [FTBTeam/FTB-Sky-Odyssey#318]
* **Modpack Version**: 1.0
* **Issue**: Using the Draconic Basic Upgrade Keys in the crafting injectors does not work.

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Draconic Evolution

* **Known Fix**: None

**Comment by Naxanria** [comment]
I can not replicate this. Are you using the correct tier of infusers?

**Comment by DestinedByte** [comment]
I have all the tiers

**Comment by Naxanria** [comment]
Do you have a screenshot of your setup?

**Comment by DestinedByte** [comment]
![2019-04-09_04 43 25](https://user-images.githubusercontent.com/24615719/55790710-8c716200-5a82-11e9-8b77-8a27e7a9a20d.png)

**Comment by DestinedByte** [comment]
I am on a server but i just set it up as default.

**Comment by Naxanria** [comment]
Yeah looks good. You did all upgrades in order? From lowest to highest?
Otherwise I have no clue why it wouldnt work, unless the server somehow changed recipes.

**Comment by DestinedByte** [comment]
I tried the base upgrade and the start button for the recipe did mot show up
I might try it in single player

**Comment by Naxanria** [comment]
Yeah, I can not replicate this at all. Might be its a server side bug.

**Comment by DestinedByte** [comment]
it appears to be doing it on single player as well [https://imgur.com/a/6poMkNK](url)
would it help if i temporarily disabled my servers whitelist?

**Comment by Naxanria** [comment]
Whitelist should make no difference.

It is weird it doesnt work for you as it does for me 
![image](https://user-images.githubusercontent.com/3246224/55794568-d7609900-5ac5-11e9-8afa-f67e6bf2e880.png)

There has been a pack update, maybe try that and see if it fixes it (Can create a new profile so you can still go into the server)

**Comment by DestinedByte** [comment]
If you were to join the server do you think it would do the same thing for you?

**Comment by Naxanria** [comment]
Wait. Do you use the normal golden apple or the upgraded ones? I cant really see with your texture pack.
You just need the normal ones.

**Comment by DestinedByte** [comment]
oh, I was using the notch apples my bad.

**Comment by Naxanria** [comment]
Glad its figured out xD
