### ISSUE TITLE
Trial Keys Crash Servers

### ISSUE THREAD

**Issue by DoubleDeathclaw** [FTBTeam/FTB-Sky-Odyssey#32]
They Mine Together Public Odysssey Server! has crashed due to me trying to use a trail key synced with a wither skele

**Comment by Jake-E** [comment]
I have no idea what those things are - the server is back up.

**Comment by Jake-E** [comment]
Trial keys from Deep Mob Learning need testing on server/client.
I can't reproduce.

**Comment by Slowpoke101** [comment]
Can you still replicate this? If so can you show someone from Creeperhost. At the moment we cannot reproduce.
