### ISSUE TITLE
extra utilities 2 items have emc value of 1

### ISSUE THREAD

**Issue by OnVa54** [FTBTeam/FTB-Sky-Odyssey#320]
Just installed 1.1 extra utilities 2 items have emc value of 1 and wanted to know if this is intended or a bug

**Comment by Vonr** [comment]
I'm not sure but they also do not display in transmutation tables/tablets and are not craftable.

**Comment by Naxanria** [comment]
They have 1 EMC, but revert back to basic machine casing inside the table.
