### ISSUE TITLE
DE, JEI settings lost after update 

### ISSUE THREAD

**Issue by xcorvis** [FTBTeam/FTB-Sky-Odyssey#323]
* **Modpack Version**: 1.1.0

* **Issue**: After updating to 1.1.0 from 1.0.0, several configurations were reset. Specifically, the Draconic Evolutions GUI elements had reset to the original locations (I had moved them up to the top) and the JEI search settings reverted to default (I had enabled search by color).

* **Link to Log or Crash File Paste**: Full update log: https://paste.feed-the-beast.com/view/0b9a5590

* **Is it Repeatable?**: Unsure

* **Mod/s Affected**: Draconic Evolution, JEI

I was able to change my settings again, but I think it's likely that something in the update process blew away my settings instead of updating and retaining them. I also don't think it's limited to those two apps, but I did specifically see the problem with them.

**Comment by xcorvis** [comment]
I reverted my game, verified it worked, then cloned it, verified my settings were in place, upgraded to 1.1.0 again, and I can confirm that my DE and JEI settings were reverted, so this is repeatable. I notice my GUI scaling and sound settings (minecraft native settings, not mods) are still the same, they have not changed.

**Comment by Naxanria** [comment]
Mod config settings are being overwritten every update, in case the mod pack author changes something in them. You could copy-paste them from your old instance.
