### ISSUE TITLE
Lava Chickens drop red eggs in nesting pen

### ISSUE THREAD

**Issue by Coffeene** [FTBTeam/FTB-Sky-Odyssey#33]
Got two lava chickens from a quest and was trying to breed them but they wouldn't in the breeder so I turned one into a chicken and put it in the nesting pen. It was dropping red eggs as well as lava eggs.

**Comment by Slowpoke101** [comment]
Thanks, will look at this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Slowpoke101** [comment]
When you talk about breeding the chickens, are you using the chicken catcher on the chicken before trying to breed the 2 chickens?

**Comment by Coffeene** [comment]
I forgot about seeds so that was my fault for the breeding, but the lava chickens still drop red chicken eggs in the nesting pen.

**Comment by Slowpoke101** [comment]
OK yeah this is intended design. Thanks for getting in touch though.
