### ISSUE TITLE
Volcanite Amulet not working

### ISSUE THREAD

**Issue by ChylerBH** [FTBTeam/FTB-Sky-Odyssey#330]
* **Modpack Version**: 1.1.0

* **Issue**: Volcanite Amulet does not fill tanks using right click as per it's tooltip despite having enough EMC available (over 30Mil).  The projectile firing using R does work.

* **Is it Repeatable?**: Tested on the following tanks: Portable Tank, Fluid Tank, Ender Tank, Singularity Tank etc. and not working.

Note: The water one works on all the above as expected.

**Comment by ChylerBH** [comment]
Update: Going into creative and the Amulet works as expected, switch back to survival and it stops functioning again.

**Comment by ChylerBH** [comment]
Didn't mean to close!

**Comment by moonheart08** [comment]
@ChylerBH Try putting a "fuel EMC" type item (i.e. coal, glowstone, redstone, aeternalis fuel, etc) in your inv and then trying it. I don't think it pulls from the tablet.

**Comment by Naxanria** [comment]
Yes. Exactly that ^

**Comment by ChylerBH** [comment]
Thanks - I never knew that.  Had I had a messy inventory with stuff in it, it would probably have just consumed something and worked and I'd have been none the wiser ;)
