### ISSUE TITLE
Beast coin miner keeps mining without power using petrified Fuel generator

### ISSUE THREAD

**Issue by Sir2Medis** [FTBTeam/FTB-Sky-Odyssey#332]
* **Modpack Version**: 1.1.0
* **Issue**: I placed a beast coin miner and 4 petrified fuel generators around it. I then put fuel in the generators, when they ran out of fuel the beast miner kept on going even though there is not a single generator that is generating power and it still keeps on mining, The fuel i used was a block of aeternaelis fuel.

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: Yes with the same setup it was doing the same thing. setup is in the gyazo.
https://gyazo.com/79fef8f80225ed31572507f7bcbb920e

I tested it with the same setup using other fuels, and they seemed to work fine.

* **Mod/s Affected**: Industrial Foregoing and Beast Coin Miner
* **Known Fix**: No idea.

**Comment by Loine** [comment]
Have the same, however mine isn't connected to anything and still mines.
Mine is just placed on a slab floor and starts mining without power lol.
Don't think it has something to do with the generators.

**Comment by Sir2Medis** [comment]
Mine does stop when i break replace it and place it somewhere else then the generators

**Comment by Pyrite19** [comment]
You guys sure your miner just doesnt have energy in its storage? lol

**Comment by xcorvis** [comment]
@Pyrite19 is probably right. The miner takes energy far faster than it spends it and does have internal storage. Giving it a lot of energy doesn't mine beast coins faster, it just makes it able to mine them for longer. This is how it behaves for me.

Also the miner displays stats for all your miners, so if you have another one somewhere else it will increment the one without power. Hover over the power bar to see how much charge it actually has.

**Comment by Psifour** [comment]
This is due to players not understanding the beast coin miner. The charge bar should be changed from the "fancy" and "cool" option that it currently is to be more informative. If it has enough energy for the next coin it should show as full otherwise it should indicate the charge proportionate to the next coins cost.

**Comment by Sir2Medis** [comment]
I do know how it works and understand it fine? my power buffer from JEI is a NEGATIVE number... so yeah that probably has something to do with it...

**Comment by Naxanria** [comment]
It is probably having enough energy to mine coins. And if it has more than 2.14B RF it will start showing negative numbers. This is a visual bug,
