### ISSUE TITLE
Server generating normal world under island

### ISSUE THREAD

**Issue by lukastrkan** [FTBTeam/FTB-Sky-Odyssey#337]
* **Modpack Version**: 1.1.0

* **Issue**: Server is generating normal world under the island (using world from serverfiles). I have tried changing level-type to void_world as mentioned here https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/259 , but I am still having same issue. Any ideas? 

My server.properties: [server.properties.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3073930/server.properties.txt)

**Comment by Slowpoke101** [comment]
Is this still an issue?

**Comment by lukastrkan** [comment]
No, I have fixed it.
There is problem with Heaven Release maps. I tried to use them, but it looks like they are non-void, so they ware source of my issue.
Also I am sorry that I didn´t close this thread.

**Comment by Tristalift** [comment]
What did you do to fix it? im having the same Problem

**Comment by lukastrkan** [comment]
> What did you do to fix it? im having the same Problem

Removing Heaven Release maps.

**Comment by Jake-E** [comment]
I haven't touched server files since the original release, which worked fine.
Unsure what has changed to break this if it is broken.
