### ISSUE TITLE
Transmutation Tablet Quest Not Completing

### ISSUE THREAD

**Issue by HunterHM** [FTBTeam/FTB-Sky-Odyssey#34]
I have both had a transmutation tablet in my hand and inventory as well as crafted one and had the tablet learn how to make them on command with EMC but the quest for the transmutation tablet will not tell me I have completed the quest. I don't know if I am doing this one wrong but just thought I would share what might be a bug.

**Comment by DoubleDeathclaw** [comment]
you need to the portable one 
![image](https://user-images.githubusercontent.com/48704995/54582156-18452080-49e6-11e9-8262-deb11283757a.png)

**Comment by HunterHM** [comment]
Ok thank you. Guess I just miss read the quest.
