### ISSUE TITLE
Energy Storage Upgrade Recipe

### ISSUE THREAD

**Issue by KaosOveride** [FTBTeam/FTB-Sky-Odyssey#341]
* **Modpack Version**: 1.1.0

* **Issue**: Energy Storage Upgrade recipe. If using any type of chiseled plank, recipe will output the "Tech Reborn" Energy Storage Upgrade, which is not accepted by the quest.  Vanilla planks will output the IndustrialCraft 2 Energy Storage Upgrade

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes craft with Vanilla planks or any Chiseled plank.

* **Mod/s Affected**: Tech Reborn 2.22.1.979 & IndustrialCraft2 2.8.111-ex112

* **Known Fix**: Tweak Recipe for Tech Reborn Energy Storage Upgrade to use logs instead of planks

**Comment by Naxanria** [comment]
For Slow: Clashing recipes.

**Comment by martingolding96** [comment]
When did the pack get the updated tech reborn mod?
