### ISSUE TITLE
Missing core mods?

### ISSUE THREAD

**Issue by wormcowboy** [FTBTeam/FTB-Sky-Odyssey#343]
* **Modpack Version**: 1.0.0

* **Issue**: Whenever I try to launch the pack an error shows instead of the normal select screen,
it says that I'm missing 12 mods that other mods depend on.

* **Link to Log or Crash File Paste**: https://pastebin.com/DGrKuMGA
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: All?

* **Known Fix**: N/A 

FYI I'm using the twitch launcher and have tried deleting and redownloading the pack, also tried the fix pack button.  They didn't work

**Comment by Naxanria** [comment]
There is an updated version (1.1.0) Might try that and se if that helps?
