### ISSUE TITLE
Crash when looking at the Basic Drawer with Creative Vending Upgrade containing Creative Capacitor Bank

### ISSUE THREAD

**Issue by sharkman** [FTBTeam/FTB-Sky-Odyssey#344]
* **Modpack Version**: 1.1.0

* **Issue**: MC crashes when looking at the Basic Drawer with Creative Vending Upgrade containing Creative Capacitor Bank

* **Link to Log or Crash File Paste**: https://pastebin.com/EESdKe8t

* **Is it Repeatable?**: Yes, place Basic Drawer, add Creative Vending Upgrade, insert Creative Capacitor Bank, you are going to crash if you are looking at the Storage Drawer. If you are going to load the world again you are going to crash almost instantly.

* **Mod/s Affected**: The One Probe/Storage Drawers/Ender IO

* **Known Fix**: Do not look at the Storage Drawers with Creative Capacitor Banks or disable The One Probe.

**Comment by sharkman** [comment]
Probably related to #353

**Comment by Slowpoke101** [comment]
The relevent information has been sent to the appropriate mod authors on this. Thanks.
