### ISSUE TITLE
Snad entry in ThaumicJEI causes game to crash

### ISSUE THREAD

**Issue by RaySkids** [FTBTeam/FTB-Sky-Odyssey#345]
* **Modpack Version**: Version 1.1.0

* **Issue**: When looking at the uses for "Snad" (don't confuse it for "sand") in the JEI Menu, clicking on the ThaumCraft JEI Tab causes the game to crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/011bf0a1

* **Is it Repeatable?**: Yes

* **Mod/s Affected?**: Snad and ThaumicJEI

**Comment by Naxanria** [comment]
I can not replicate this. What items did you have in your inventory?
