### ISSUE TITLE
Please remove Thaumcraft or make it optionally

### ISSUE THREAD

**Issue by jk1895** [FTBTeam/FTB-Sky-Odyssey#348]
This is the worst mod ever (boring, difficult and annoying)! It's a huge drawback to play the pack further on.
Remove it and stop adding it in your packs, please.

Thanks :-p

**Comment by SirioIlBe** [comment]
I would upvote this 1000 times if possible... i hate that mod

**Comment by monokin1114** [comment]
If they removed every mod people complained about. There would be no pack.

**Comment by jk1895** [comment]
That's not true. Thaumcraft is a special case. Sky Odyssey is a fast-paced mainly technical pack and Thaumcraft simply don't fit. It's an overwhelming and huge mod that needs loots of knowledge and time.

For me additionally it's boring and annoying and I failed to do all the tasks. There are other annoying mods like IC2 or Botania and Blood Magic, but they are doable.

**Comment by dabigmoose** [comment]
Completely disagree. Thaumcraft is easy and flows well with pack.  If you don't like the pack the way it was designed then don't play it.  This isn't a bug.

**Comment by jk1895** [comment]
The pack is great! One of the best I have played. This is a [Suggestion] not a bug and this pack would be much better without this mod.

**Comment by ThePoet444** [comment]
Thaumcraft is a fantastic mod, very well done and thought out. However, in this case with this pack, I can see why it feels out of place. I personally am not a fan of magic mods, but botania and blood magic are passable and relatively easy. Thaumcraft requires thought and work, which isn't a bad thing by any means, but in a fast paced pack like Odyssey, it can be a bit of an annoyance.

**Comment by moonheart08** [comment]
Older thaumcrafts are great, however Thaumcraft 6 seems lacking in content to me. There simply isn't much of a reason to even bother with it, besides completing some quests.

If it had more content, and wasn't as dependant on RNG (It used to be that research was done via actually somewhat fun puzzles, not randomness), i'd not like this as much.

But in this case, making it optional would be very welcome.

**Comment by Slowpoke101** [comment]
Just no. Sorry but it would be impossible to remove that mod at this stage even if I wanted to.
