### ISSUE TITLE
Void Ore Miner Controller Tier 1

### ISSUE THREAD

**Issue by BangBangityBam** [FTBTeam/FTB-Sky-Odyssey#349]
* **Modpack Version**: 
12.2.2
* **Issue**: 
Hello, 

I can't seem to make the Void Ore Miner Controller Tier 1 working. I've rebuild it plently of times but it just doesn't work. The Structure Block stays red in chat.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Rebuild it plently of times.
![Helppls](https://user-images.githubusercontent.com/49610872/56092105-f1c8b700-5eb7-11e9-9b73-bfae1eb4cca5.png)

* **Mod/s Affected**: 

* **Known Fix**: 

CAN BE CLOSED, DIDN'T BUILD CORRECTLY, FOLLOWED WRONG BUILD. THANKS!

**Comment by jk1895** [comment]
I can't reproduce it.
https://imgur.com/a/Wtp7vHz
