### ISSUE TITLE
Salis Mundus Not Working

### ISSUE THREAD

**Issue by xTealdragonx** [FTBTeam/FTB-Sky-Odyssey#351]
Ok so I was playing and I got 64 Lamps of Growth for a quest.  To make a Lamp of Growth I've heard you need Herba from Thaumcraft.  So, I try to make an arcane crafting table With the Salis Mundus, but it wouldn't work. I tried right clicking, left clicking, and shift clicking a normal crafting table., They didn't work!  Please let me know if im doing something wrong...

**Comment by Naxanria** [comment]
Use it on a bookshelf, that will give you a thaumanomicon. Follow the book.
You need to unlock stuff to be able to creaft.

**Comment by PurpleRoyalty** [comment]
Thanks Naxanria your reply was very helpful
