### ISSUE TITLE
Transmutation Table/Tablet No Longer Burns Items

### ISSUE THREAD

**Issue by Below50** [FTBTeam/FTB-Sky-Odyssey#355]
Modpack Version: 1.0.0 and 1.1.0

Issue: Transmutation Table or Tablet suddenly do not allow items to be burned. You can learn items, you can de-learn items, you can use the compressed EMC block to get rid of items for EMC, but you cannot burn items making the mod quite unplayable.

Link to Log or Crash File Paste: No crash file or log to report as there are no errors shown.

Is it Repeatable: Not sure how I caused it in the first place, but of course, it hasn't gone away since it began.

**Comment by Below50** [comment]
Looks like the Stone Transmutation Table and the Arcane Transmutation Tablet work as they should. Not sure why the original's suddenly broke?

**Comment by LatvianModder** [comment]
It never worked with original ones, but you would never reach that amounts of EMC. once you reach 9E, the original ones have built in "can't put items in, only take out" mechanic, this is working as intended [by PE]
