### ISSUE TITLE
Matter overdrive Replicator can't fill above standard capacity

### ISSUE THREAD

**Issue by Lollerix** [FTBTeam/FTB-Sky-Odyssey#356]
Version:
1.1.0

I'm trying to use matter overdrive's Replicator but when i use the storage upgrade to increase it's capacity, the content never goes above 1024mB even if the storage should be more than that. It worked correctly the first time i placed the block. I broke it to replace it somwhere else and then the storage upgrades did nothing. Tried making a new replicator but the issue exists there too. 

Matter Overdrive: Legacy Edition

I will try to make a test world to see if it is a "corrupt" save file or something

**Comment by Naxanria** [comment]
Matter overdrive is no longer in the modpack since 1.1.0, so you are better of reporting this to the modauthor. https://rr-dev.atlassian.net/servicedesk/customer/portal/3
