### ISSUE TITLE
Chaos Shard not craftable with Draconic Evouloution..

### ISSUE THREAD

**Issue by Pyario** [FTBTeam/FTB-Sky-Odyssey#358]
Modpack Version: 1.0.0
*Issue: Chaos Shard not craftable with Draconic Evouloution..

* **Link to Log or Crash File Paste**: Nothings

* **Is it Repeatable?**: I Don't know.

* **Mod/s Affected**: Draconic Evoulution

* **Known Fix**: I Don't know.

ScreenShot: http://prntscr.com/nctvbc
ScreenShot: http://prntscr.com/nctvjy

**Comment by Naxanria** [comment]
Your setup is wrong, the infusers can only be a 3x3 with the crafter in the middle.

**Comment by Pyario** [comment]
Oh okay. Thank you @Naxanria!
