### ISSUE TITLE
Info for server world generation - sky islands

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Sky-Odyssey#36]
Is there some form of document where I can find out what generator settings to use to apply the various island types for a multiplayer server?

**Comment by nzminecraftDOTcom** [comment]
May have found it > Will close this issue if so.

**Comment by Joly0** [comment]
Can you tell me about it? Having the same issue and dont find an answer

**Comment by nzminecraftDOTcom** [comment]
@joly0
Set level-type from DEFAULT to void-world
