### ISSUE TITLE
Decent amount of emc early in game

### ISSUE THREAD

**Issue by Aresiel** [FTBTeam/FTB-Sky-Odyssey#360]
* **Modpack Version**: Not sure

* **Issue**: Not really an issue, more an trick. You can buy quest books for 1 credit each and they're worth 127 or something EMC. So buy a few thousand questbooks and you get quite a lot of EMC.

* **Link to Log or Crash File Paste**: Not useful

* **Is it Repeatable?**: Yup!

* **Mod/s Affected**: Idk, the FTB ones?

* **Known Fix**: Yeah, set the price to like 100.

**Comment by martingolding96** [comment]
As if anyone would buy the quest book more than once when there is another item that has a larger coin to emc ratio

**Comment by Naxanria** [comment]
This is a non-issue.
