### ISSUE TITLE
ME system stealing items

### ISSUE THREAD

**Issue by BabyPii** [FTBTeam/FTB-Sky-Odyssey#362]
* **Modpack Version**: 1.0.0/1.1.0 

* **Issue**: Whenever i try and input ANY items into my me system the me system just steals my item and i can never get it back again (without making another one obv)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f9734a3e

* **Is it Repeatable?**:  Happens whenever i use my me system. 

* **Mod/s Affected**:  Applied Energistics 2 / Extra Cells 2

* **Known Fix**: Dont know a perm fix but only way i can save my items is to quit to title and get back in i then have a few seconds to save them before it breaks again

* **Video Showing Bug**: https://youtu.be/OwNuB2nxOdI

**Comment by Naxanria** [comment]
You seem to have an emc link connected, set the storage bus on that to only extract. Inserting will have any item with emc to be converted into em, seemingly disappearing.
