### ISSUE TITLE
JEI crafting tab showing 4644 pages of recipes for philospher's stone

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Sky-Odyssey#364]
* **Modpack Version**: 1.1.0
* **Issue**: Displaying "uses" for Philospher's Stone in JEI, crafting tab shows 4644 pages. Only the first few recipes use the stone. The remaining appear to be just the rest of the recipes in JEI.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: JEI, ProjectE

* **Known Fix**:

**Comment by Naxanria** [comment]
As you can use the philosopher stone as a crafting table, that is correct,
