### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by LlamaMilk** [FTBTeam/FTB-Sky-Odyssey#365]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7718c2e2

* **Is it Repeatable?**:Yes

* **Mod/s Affected**: I updated botania to prevent another crash
* **Known Fix**: Unkown

**Comment by Naxanria** [comment]
This has been fixed in version 1.1.0

**Comment by LlamaMilk** [comment]
No its not cuz im in. 1.1.0
