### ISSUE TITLE
island reverts back to previous state

### ISSUE THREAD

**Issue by cc2k** [FTBTeam/FTB-Sky-Odyssey#367]
* **Modpack Version**: 
1.0.0
* **Issue**: 
Got the issue 2x, first when i was playing on my island, i teleported to friends, and after i did/hom i got back to the state of the island as i started that day...(missing a few machines and stuff i had put down) altho the alchemy table did remeber all the reciepes i learned past the start of that day.
When i just logged in, the island reverted again back to that same starting point as the previous bug... this is pretty ennouing.. as i cannot build now..

also the /home command is not recognized anymore.. tried to reproduce the error.. 

server is only online when i play.

* **Is it Repeatable?**: 
i cannot reproduce this as of now, will do some more tests when i got players on the server

**Comment by Naxanria** [comment]
This looks like an issue with the server not saving properly. Without a log from the server there is nothing we can do.

**Comment by cc2k** [comment]
ill add the logs i got, these are the non .gz files
[2019-04-17-1.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3107384/2019-04-17-1.log)
[2019-04-17-2.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3107385/2019-04-17-2.log)
[debug.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3107386/debug.log)
[debug-3.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3107387/debug-3.log)
[latest.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3107388/latest.log)
