### ISSUE TITLE
Chat ban

### ISSUE THREAD

**Issue by FraDark002** [FTBTeam/FTB-Sky-Odyssey#368]
I was banned from global chat because my cousin wrote fuck. I'm Italian and fuck in Italy is a word that does not affect a person's behavior much. I'm sorry about what was written in chat and I regret having given my cousin's profile. Where can I find an admin? I'm FraDark002 on game

**Comment by ThePoet444** [comment]
You'll have to talk to the MineTogether mods over at creeperhost. They are the ones that handle the chat bans in global.

**Comment by Naxanria** [comment]
That is a MineTogether thing. Nothing to do with the pack itself.
