### ISSUE TITLE
Error in splash.properties file

### ISSUE THREAD

**Issue by winkel** [FTBTeam/FTB-Sky-Odyssey#37]
Released file contains lines left by git after conflict during git stash pop operation.

enabled=true
** >>>>>>>=Stashed** changes
forgeTexture=fml\:textures/gui/ftb.gif
** <<<<<<<=Updated** upstream
font=0xFFFFFF

and 

barBorder=0x000000
** =\=\=\=\=\=\=
fontTexture=textures/font/ascii.png

**Comment by Jake-E** [comment]
Thanks, not a file that usually gets checked. Will fix.

**Comment by Slowpoke101** [comment]
Will be resolving this in a different way.
