### ISSUE TITLE
Infinite early game EMC Iron -> Refined Iron

### ISSUE THREAD

**Issue by Sulhrive** [FTBTeam/FTB-Sky-Odyssey#371]
* **Modpack Version**:
 Updated: 4/22/2019
Version: 1.1.0
Minecraft Version: 1.12.2
(modded) forge-14.23.5.2815

* **Issue**: In early game, if you buy one piece of iron, you can double the EMC for that iron by smelting it a second time. so early game you can create infinite EMC with some wood and iron.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: Nope

**Comment by moonheart08** [comment]
Likely intended. Same dupe can be done much more efficiently by grinding emerald ore into emeralds (x2) and then using the tablet to convert that into emerald ore (x2)

**Comment by Sulhrive** [comment]
Yea, after playing a little longer, I realized this is basically a non issue.  early game EMC gen is meant to be pretty quick from the looks of it.
