### ISSUE TITLE
advancements page doesnt show anything

### ISSUE THREAD

**Issue by loucor** [FTBTeam/FTB-Sky-Odyssey#376]
* **1.10**: 

* **When you click the hot key or use the advancement book or go to quests in your inventory it says theres nothing here at the moment.**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Slowpoke101** [comment]
This is intended. All the advancements were removed.
