### ISSUE TITLE
[Bug] The Final Relay - Quest

### ISSUE THREAD

**Issue by dsabecky** [FTBTeam/FTB-Sky-Odyssey#41]
The quest "The Final Relay" gets completion credit after crafting Basic Relay [MK1].

**Comment by DoubleDeathclaw** [comment]
^^^ same

**Comment by Slowpoke101** [comment]
Pretty sure the dev version has this fixed now. Thanks for the report though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheError007** [comment]
Had the same exact issue
