### ISSUE TITLE
Sun stuck in sky

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Sky-Odyssey#42]
Running this pack on a server, probably not supported yet but the sun/moon do not move yet day and night cycles happen, mobs burn etc if you force the time to night however the sky is displayed as daytime, mid day.

**Comment by MrGREGhimself** [comment]
Eternal day is there by design so no day/night cycles.

**Comment by nzminecraftDOTcom** [comment]
Ah, thanks. Is this designed to also stop mobs from spawning?

**Comment by MrGREGhimself** [comment]
Yes. If you need mobs, make yourself a simple mob farm or head to the nether.

**Comment by nzminecraftDOTcom** [comment]
Ok then that part of it must be broken, they are spawning as if it is night time, and the sky keeps flashing black.

**Comment by piisawheel** [comment]
Did your forced setnight command start a cycle that is fighting the eternal daytime mod? Just a thought...
