### ISSUE TITLE
[SOLVED] Sky flashing black [SOLVED]

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Sky-Odyssey#43]
Sky flashes black, as if it was trying to become night. had an issue already here (closed now) about the eternal day, however now that is sorted, the sky continually flashes as if it's night.

If anyone is able to explain how I can disable this eternal day and just set gamerule dodaylightcycle false, this may solve my issue.

**Comment by Slowpoke101** [comment]
It’s a mod that’s pausing the day cycle. Will have to see if we can find out why this is happening to you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Naxanria** [comment]
The sky does turn back at a certain height level, that might also be causing it?

**Comment by nzminecraftDOTcom** [comment]
I'm on an island that has spawned in. The issue does not happen on Single player, however.

**Comment by Jake-E** [comment]
Hmm.. maybe this isn't stopping the daylight cycle properly on servers? It appears to work fine on mine?

**Comment by Inrixia** [comment]
Going into the ftbu config and enabling its daytime tick fixing thing (Setting it to 6000) seems to overwrite whatever is doing it and remove the flashing, this does as far as I know disable the progression of time though, but its a half decent fix for now.

**Comment by nzminecraftDOTcom** [comment]
^ Have confirmed with @Inrixia that this is a fix, on both our servers.

Happy fixing everybody!

**Comment by Naxanria** [comment]
Progression of time is meant to be set at day time only.
The flashing is weird though.

**Comment by nzminecraftDOTcom** [comment]
> Progression of time is meant to be set at day time only.
> The flashing is weird though.

That is because FTBUtilities was trying to run time as normal, where another mod was trying to keep it noon, setting both to noon means they don't conflict.

**Comment by piisawheel** [comment]
Do you think running the set night command started a cycle?
