### ISSUE TITLE
Instant Crash When Trying To Load Save

### ISSUE THREAD

**Issue by NullifiedUser** [FTBTeam/FTB-Sky-Odyssey#435]
* **Modpack Version**: 1.1.0

* **Issue**: Instant crash when loading my save

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/662e92f9

* **Is it Repeatable?**: No?

* **Mod/s Affected**: don't really know maybe Ender IO or Botania

* **Known Fix**: No fix as can not load save

**Comment by MrKinau** [comment]
Had this on a server multiple times when looking at a Capacitor bank. To join the world again you can edit your position in the world files. Changing yaw & pitch + y worked for me very well.

1. Open your world and navigate to playerdata
2. Open the file <your_uuid>.dat with NBTExplorer
3. Change the fields Pos and Rotation to different values (for me it worked to just change the rot and the y-values)

**Comment by NullifiedUser** [comment]
Thank you for the help fixed my issue.

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> Had this on a server multiple times when looking at a Capacitor bank. To join the world again you can edit your position in the world files. Changing yaw & pitch + y worked for me very well.
> 
>     1. Open your world and navigate to playerdata
> 
>     2. Open the file <your_uuid>.dat with NBTExplorer
> 
>     3. Change the fields Pos and Rotation to different values (for me it worked to just change the rot and the y-values)

Hi, I did the same thing, but it didn't work. I even changed the dimension ( I set it to 1 ) but there still is this blue screen, do you have any idea that could help me ?

**Comment by MrKinau** [comment]
Have you tried deleting the whole file?

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> Have you tried deleting the whole file?

No, but isn't it dangerous to delete the whole file ?

**Comment by MrKinau** [comment]
Yes, you definitely should backup it. You will lose your complete inventory, but it's worth a try

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> Yes, you definitely should backup it. You will lose your complete inventory, but it's worth a try

I deleted the the inside of the playerdata file, but when I launched minecraft ( it crashed again ), I was able to see for 10 sec that my inventory was still the same ( I froze in the ESC screen, so I was still able to see my hotbar ). Idk if this can help, but I used the unbreakable wand w/on vibrant banks. So, is my save definitely broken and should I use the last back-up, even though I'd lost ~6-8 hours ?

**Comment by MrKinau** [comment]
Using this wand on capacitors kills your game. If you could see your hotbar items something went wrong. All inventory items are saved im this file. If you still hold the unbreakable wand you could Change the hold Item in the file, but I think you are working with the wrong file. Another step which sometimes helped is to view the world in an external application (I think it's named mcedit) and destroy all capacitors. Good luck

**Comment by Thisisnotanappropriatepseudo** [comment]
Hi, thanks ALOT because my save works now, but I lost all of the things I had in the transmutation tablet. As I am in the map " The Middle", I could have taken the tome of knowledge, but it doesn't work. Do you have any idea to get back my transmutations ? Or is there a way to "un-learn" something in the transmutation table ? I'd like to test smth if I knew how to "un-learn" x)

**Comment by MrKinau** [comment]
Sorry cant help you with this, maybe the learned thins are saved in the user storage. You may look around in the files from this mod or open the playerdata file with NBTExplorer maybe the recipes are saved there, but I have no idea where it is saved

**Comment by Thisisnotanappropriatepseudo** [comment]
> 
> 
> Sorry cant help you with this, maybe the learned thins are saved in the user storage. You may look around in the files from this mod or open the playerdata file with NBTExplorer maybe the recipes are saved there, but I have no idea where it is saved

ALL problems are finally solved. If you want to know, you just have to turn in NBTExplorer " fullknowledge 0" in full knowledge 1". And, the last thing I'll say is : THANKS A LOT.

**Comment by Luevan09** [comment]
How do you open your world files?

**Comment by beastboy123g** [comment]
> Had this on a server multiple times when looking at a Capacitor bank. To join the world again you can edit your position in the world files. Changing yaw & pitch + y worked for me very well.
> 
> Open your world and navigate to playerdata
> Open the file <your_uuid>.dat with NBTExplorer
> Change the fields Pos and Rotation to different values (for me it worked to just change the rot and the y-values)

i open the file from saves - new world - player data - and there is no file like youruuid threre is a weird file with weird letters and words in it and the file calls like 914e37f0-713c-4f1e-9298-2eaeae08457f did i do something wrong?

**Comment by FurkanOzaydinAp** [comment]
> Had this on a server multiple times when looking at a Capacitor bank. To join the world again you can edit your position in the world files. Changing yaw & pitch + y worked for me very well.
> 
> Open your world and navigate to playerdata
> Open the file <your_uuid>.dat with NBTExplorer
> Change the fields Pos and Rotation to different values (for me it worked to just change the rot and the y-values)

same pls help i did change those all values by 10 and same crash happened :( crazypants.enderio.base.power.forge.item.IInternalPoweredItem

**Comment by MrKinau** [comment]
Well I dont really know why this could happen after you ported yourself to another location. Try to do the following:
1. Port to any position where you definitely wont expect any blocks around you (change pos with the NBTExplorer) i.e. port to y 255 or higher (you will probably die)
2. Maybe change your Rotation in the NBTExplorer
3. As it seems to be an issue while holding any building wand and looking at a capacitor bank, change your selected Item slot in the dat file to a slot without a building wand (use the NBTExplorer)
4. Last option is to delete the file completely (which will result in data loss, all your inventory items and some other things are stored in this file, I guess EMP is also stored there)

![image](https://user-images.githubusercontent.com/13185260/83042365-e0058d00-a041-11ea-98da-b67faed25147.png)
This example is not from a modded server, but demonstrates which fields can be safely changed to fix this bug

**Comment by FurkanOzaydinAp** [comment]
> Well I dont really know why this could happen after you ported yourself to another location. Try to do the following:
> 
> Port to any position where you definitely wont expect any blocks around you (change pos with the NBTExplorer) i.e. port to y 255 or higher (you will probably die)
> Maybe change your Rotation in the NBTExplorer
> As it seems to be an issue while holding any building wand and looking at a capacitor bank, change your selected Item slot in the dat file to a slot without a building wand (use the NBTExplorer)
> Last option is to delete the file completely (which will result in data loss, all your inventory items and some other things are stored in this file, I guess EMP is also stored there)
> 
> 
> This example is not from a modded server, but demonstrates which fields can be safely changed to fix this bug

pls help see i deleted everything in that file D;

![minecraft crash](https://user-images.githubusercontent.com/66019888/83049884-f6184b00-a04b-11ea-88dc-fbedf63e9492.gif)

**Comment by MrKinau** [comment]
You should not delete the fields, as last alternative you should delete the whole dat file (hopefully you have a backup) or before deleting everything, changing the slot field (SelectedItemSlot) to another value may work. At least after deleting the whole file you should be able to join the world again (You can restore all relevant data from the dat file (if you have a backup))

**Comment by FurkanOzaydinAp** [comment]
> You should not delete the fields, as last alternative you should delete the whole dat file (hopefully you have a backup) or before deleting everything, changing the slot field (SelectedItemSlot) to another value may work. At least after deleting the whole file you should be able to join the world again (You can restore all relevant data from the dat file (if you have a backup))

Duddddeee it was so easy to fixxx i just had to like download mcedit and delete vibrant capacitator but still thx :D

**Comment by MrKinau** [comment]
Thats another option xD

**Comment by T7love** [comment]
I tried all of these things and none of them are working... any other ideas?

**Comment by T7love** [comment]
nvm i figured it out!
