### ISSUE TITLE
[Request] chisel bit bag stack size

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Sky-Odyssey#44]
The stack size of the bit bag from chisel and bits is a bit lacking. you chisel one whole block and the bag is suddenly a quarter full.

In the chisel and Bits config, could you please increase the stack size? prefferably to 4096, so each slot in the bit bag can hold up to one whole block.

**Comment by Naxanria** [comment]
That sounds liek a good idea to have it hold at least one block :D

**Comment by Slowpoke101** [comment]
Should be upgraded in the next release.

**Comment by Naxanria** [comment]
Open till update is released.
