### ISSUE TITLE
Refined Storage and EMC

### ISSUE THREAD

**Issue by applemes** [FTBTeam/FTB-Sky-Odyssey#45]
Can the Compressed Refined EMC Link be used in the Refined Storage, similarly to the AE2 Storage? I tried with the RS Importer/Exporter but i cant get it working

**Comment by Naxanria** [comment]
You would need to use a external storage instead.

**Comment by applemes** [comment]
awesome thanks!

**Comment by TheOfficialButton** [comment]
Connecting an External Storage to the Compressed Refined EMC Link will allow you to see items

**Comment by RCgaming77** [comment]
Dear TheOfficialButton: i just tried to connect a compressed refined emc link with a external storage to my RS but it show nothing in RS Crafting grid

**Comment by dirvkjd** [comment]
Same for me, connecting external storage to Compressed Refined EMC Link does nothing.
