### ISSUE TITLE
Game crashes on particular world

### ISSUE THREAD

**Issue by suprem3huntr** [FTBTeam/FTB-Sky-Odyssey#457]
* **Modpack Version**: 1.1.0
* **Issue**: The mudpack loads smoothly and my test world as well as new worlds open, but when I open my main world it crashes the game immediately

* **Link to Log or Crash File Paste**:https://paste.feed-the-beast.com/view/49464944

* **Is it Repeatable?**:repeatable on my computer

**Comment by SuplierZWTF** [comment]
lord god stop using ender io stuff except for alloy smelter
