### ISSUE TITLE
Game crashes after exiting world save

### ISSUE THREAD

**Issue by Doomblaze852** [FTBTeam/FTB-Sky-Odyssey#46]
the game crashed/ became unresponsive after exiting a world no crash log was given or created just froze up and i had to manually close it i have a pc with 11Gb ram and a nvidia gtx 1050TI with an intelcore i7 processor with 4 terabytes of memory

**Comment by nzminecraftDOTcom** [comment]
11gb of ram?

What an odd number, can you please confirm this with a screenshot.

**Comment by Jake-E** [comment]
Did you open the world to LAN?

**Comment by Doomblaze852** [comment]
yes, I opened to LAN first tried to fix the chosen map start problem for myself
![about pc](https://user-images.githubusercontent.com/48712824/54652733-255d2080-4a75-11e9-9e84-1e491f9fd8e9.png)

**Comment by TheOfficialButton** [comment]
This is a Minecraft issue and cannot be solved by us. Hopefully this is fixed in the future. Trying playing without opening to LAN and this should solve the issue
