### ISSUE TITLE
Curseforge files dont work

### ISSUE THREAD

**Issue by TheDan726** [FTBTeam/FTB-Sky-Odyssey#47]
The curseforge files are practically empty for some reason.
Twitch laucher just times out cause of bad internet and FTB launcher cannot launch packs for some reason.
Is the pack on technic or something?

**Comment by ahmedmamdoh18** [comment]
I have the same issue and i got this message every try 
Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip

**Comment by TheDan726** [comment]
cant reinstall what is not installed to begin with

**Comment by TheDan726** [comment]
check the curseforge files for yourself they are only 120mb big

**Comment by TheDan726** [comment]
Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip 
every timeffs

**Comment by Naxanria** [comment]
If you download the zip, create a custom profile, click on import, then select the zip file you downloaded.

**Comment by TheDan726** [comment]
open twitch launcher
click mods
click minecraft
browse modpacks
ftb sky odyssey
install

**Comment by ahmedmamdoh18** [comment]
also where is the mods? 
idont see the mods in the files

**Comment by ahmedmamdoh18** [comment]
yes

**Comment by TheDan726** [comment]
actual bs

**Comment by Jake-E** [comment]
The zip is an export that requires importing.
It is not BS if you know how a twitch export works.

Download the zip, import via create custom pack.

**Comment by Naxanria** [comment]
The zip is the info of the pack, twithc launcher actually downloads the mods

**Comment by ahmedmamdoh18** [comment]
could anyone help iam trying to download the modpack for 5 hours

**Comment by TheDan726** [comment]
if i do that auto update wont work

**Comment by TheDan726** [comment]
why tf does twitch timeout after like 10 minutes

**Comment by ahmedmamdoh18** [comment]
Create new profile
import
choose the jar file 
it worked and its downloading right now

**Comment by TheDan726** [comment]
which jar file?

**Comment by TheDan726** [comment]
i don't get why there is no standalone download that is not for twitch launcher!!!

**Comment by ahmedmamdoh18** [comment]
sorry i mean the zip file of the pack 
 https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip

**Comment by Naxanria** [comment]
Why would there be a standalone version? Through the Twitch launcher, Twitch keeps track of the downloads for the mods and can give reward points accordingly.

**Comment by TheDan726** [comment]
Twitch is very bad for people with bad internet because it times out no matter what

**Comment by Naxanria** [comment]
I dont know honestly.

**Comment by modmuss50** [comment]
support issue, closing.
