### ISSUE TITLE
I have a minecraft server but some Templates is missing

### ISSUE THREAD

**Issue by ToastWithCheeze** [FTBTeam/FTB-Sky-Odyssey#478]
I Have a Minecarft server but some of the Templates
 is missing

**Comment by honzapatCZ** [comment]
Look at teamislands config file, they have the structurenbt name wrong, correct it(you can see all available templates in maps/*/*.nbt) and restart server, now you will have the templates available

**Comment by ToastWithCheeze** [comment]
I deleted my sky odyssesy server but maybe this can help me later because i'm going to switch server host And Thanks For The Help I hope i work
