### ISSUE TITLE
Twerking not working

### ISSUE THREAD

**Issue by ivuckovecki** [FTBTeam/FTB-Sky-Odyssey#48]
I loaded up Chosen architects map and the only sapling provided was the dark oak sapling. However, twerking does not seem to be working, even though i can see the particles.

I checked the mod setting and it is at 100 so should be growing the tree quite quickly.  However, nothing happens.

Even leaving the tree to grow out on its own does not happen.  Any ideas?

**Comment by Jake-E** [comment]
Is there enough light? Does it have enough room above it to grow?

**Comment by Naxanria** [comment]
The dark oak saplings do work with twerking. It just cant grow in a 1x1, it is a 2x2 tree ;)

**Comment by ivuckovecki** [comment]
I planted it in a 2 x 2 area. as for light, it is outside, when i check the light levels, i do see yellow crosses on the ground which would suggest that lighting is not optimal, but that is how the map was created.  I do not have the ability to add more light (literally cant grow my first tree!)

**Comment by Naxanria** [comment]
Did you put 4 saplings down?

**Comment by ivuckovecki** [comment]
no. do i have to put 4 saplings at once for it to grow? did not know that :)

**Comment by Naxanria** [comment]
Yeah. in a 2x2 pattern :)

**Comment by ivuckovecki** [comment]
ahh got it. Thanks a lot!
