### ISSUE TITLE
How do I generate a server world from template?

### ISSUE THREAD

**Issue by Zickzii** [FTBTeam/FTB-Sky-Odyssey#49]
How do I make a server generate the world template I want?

**Comment by nzminecraftDOTcom** [comment]
Level-type=void_world

Run your server and generate a world

You will have an empty world

When you create a team you will get an island

Hope it helps :)

**Comment by dsabecky** [comment]
> Level-type=void_world in server.properties
> 
> Run your server and generate a world
> 
> You will have an empty world
> 
> When you create a team you will get an island
> 
> Hope it helps :)

Setting level-type in server.properties is not required.

**Comment by nzminecraftDOTcom** [comment]
> > Level-type=void_world in server.properties
> > Run your server and generate a world
> > You will have an empty world
> > When you create a team you will get an island
> > Hope it helps :)
> 
> Setting level-type in server.properties is not required.

It was if you were generating the server files from the game downloaded ones, when there were no premade configs, this may be fixed by downloading the official server files now I assume.
