### ISSUE TITLE
Updates: Flux Networks and More

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Sky-Odyssey#498]
* **Modpack Version**: 1.1.0

* **Issue**: Outdated mods need updating to overcome old issues and hurdles. For instance, Flux Networks needs to be updated otherwise the hard limit of power transfer from the Plugs to the Draconic Core is set at 2.15B RF, as well as ProjectE which had a huge number of bug fixes since the version in this modpack, namely the limit after which items can no longer be placed into the table/tablet.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: Update some mods.

**Comment by Naxanria** [comment]
Sky odyssey 1.2.0 is out (on the FTB App) with many updated mods.
