### ISSUE TITLE
Cannot craft TR Advanced Electronic Circuit

### ISSUE THREAD

**Issue by Slyklaw** [FTBTeam/FTB-Sky-Odyssey#5]
The recipe creates an IC2 Advanced Circuit. Fortunately, the Advanced Circuit is usable in recipes so this is a minor issue.

![advanced](https://user-images.githubusercontent.com/44900062/50269165-047a3480-0460-11e9-8fbf-e93b3917e029.png)

**Comment by Slowpoke101** [comment]
Fixed

**Comment by manmaed** [comment]
@LatvianModder or @Slowpoke101 can you close this
