### ISSUE TITLE
[Request] Ore Dictionary for Wood/Sapling

### ISSUE THREAD

**Issue by PyroBurnem** [FTBTeam/FTB-Sky-Odyssey#50]
When starting out in a world without specifically oak wood, this quest:
![image](https://user-images.githubusercontent.com/31893867/54599798-5a1da780-4a76-11e9-9f42-c9d499935120.png)
does not register. I'm unsure if its by design or unintentional as this is possibly the very first quest people would complete, and starting islands without oak wood would not be able to complete the quest until later when they are able to get it. Same goes for the sapling, but the world I started out in had some oak leaves placed as decoration and I got a sapling from those, which lead me to believe that this was unintentional.

**Comment by Naxanria** [comment]
You can get them really early as they are inexpensive in the shop. And yes, it is by design :)

**Comment by PyroBurnem** [comment]
Glad to have this confusion cleared up. Cheers!

**Comment by TheOfficialButton** [comment]
You can buy this in the shop for super cheap. This should solve your issue :)
