### ISSUE TITLE
Tech Reborn industrial centrifuge crash

### ISSUE THREAD

**Issue by Alsososcar** [FTBTeam/FTB-Sky-Odyssey#500]
Modpack Version: v1.2.0

Issue: Tech Reborn machine industrial centrifuge crashes when put down. And when trying to open world again just crash.

Crash-report: [crash-2020-06-10_20.36.40-server.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/4760597/crash-2020-06-10_20.36.40-server.txt)

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  StructureUtilsASM (StructureUtils-1.1.0.4.jar)
  BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (LoadingTips-1.12.2-1.1.0.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  FTBUltimineASM (FTBUltimine_1.12-1.2.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/10/20 8:36 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: active
	at techreborn.tiles.processing.TileMachine.func_73660_a(TileMachine.java:139)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at techreborn.tiles.processing.TileMachine.func_73660_a(TileMachine.java:139)

-- Block entity being ticked --
Details:
	Name: techreborn:industrial_centrifuge // techreborn.tiles.processing.TileIndustrialCentrifuge
	Block type: ID #512 (tile.techreborn.industrial_centrifuge // techreborn.blocks.tier2.BlockIndustrialCentrifuge // techreborn:industrial_centrifuge)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (-6,106,56), Chunk: (at 10,6,8 in -1,3; contains blocks -16,0,48 to -1,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #512 (tile.techreborn.industrial_centrifuge // techreborn.blocks.tier2.BlockIndustrialCentrifuge // techreborn:industrial_centrifuge)
	Actual block data value: 7 / 0x7 / 0b0111
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['AlsosOscar'/202, l='New World', x=-7.81, y=106.00, z=57.38]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -271631916340565512
	Level generator: ID 07 - void, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (68,64,280), Chunk: (at 4,4,8 in 4,17; contains blocks 64,0,272 to 79,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3306589 game time, 6001 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 115804 (now: false), thunder time: 3048 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

Is it Repeatable?: Yes. i opened the backup and placed again and boom crash. 

* **Mod/s Affected**: Tech Reborn

Known Fix: Nope

**Comment by Bioniclegenius** [comment]
Happens to me, too. Unable to complete the game without cheating because I can't place a centrifuge, let alone use it. Tested in a blank world, same story. Save is overwritten by autosave on crash, so I can't even reload a save, I have to restore a backup.

**Comment by KingArtMan** [comment]
> Happens to me, too. Unable to complete the game without cheating because I can't place a centrifuge, let alone use it. Tested in a blank world, same story. Save is overwritten by autosave on crash, so I can't even reload a save, I have to restore a backup.

I am also having this issue.
I do not know a way to get around the progress block in terms of completing the game (without cheating), however, I do know a way to get your world back without having to restore a backup. If you open the modpack folder and go into the config folder, there should be a text file for Forge. in that config, change the following settings from false to true:

    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true

This should work to fix any crash that involves ticking Entities/TileEntities

After changing these settings, your world will load again, however the industrial centrifuge is still worthless, you can almost open the GUI, but it auto closes immediately. I even tried piping materials in automatically and still it won't run not even accept energy inputs. The block is simply completely unusable. Maybe they could transfer the recipes over to a different centrifugal device like the one from industrialcraft2?... idk

After you get your world loaded again, you will want to remove the industrial centrifuge, save and exit the game, close the program, reopen the Forge config, and return the above settings to false. Apparently they can cause serious issues if they are left on all the time (which I assume is why they are turned off by default) which can lead to the loss of the world.

I hope that helps someone, I am going to have to cheat in the resources for now, fortunately they are EMC-able, so having legitimately crafted the machine and ingredients I don't feel too bad about it, but it's a huge bummer to someone who doesn't know the fix or whose last backup will set them back a ways.

Goodluck!

**Comment by Alsososcar** [comment]
Thank you for helping me! Too bad that i didnt know about that method earlier. But one thing i have not tried is to delete the mod inside the modpack and install the newest version of the modpack in 12.2

**Comment by magerooster** [comment]
I encountered this exact issue. You can fix this issue by updating TechReborn (I updated to TechReborn-1.12.2-2.27.3.1084-universal) and RebornCore (I updated to RebornCore-1.12.2-3.19.4.529-universal).

https://www.curseforge.com/minecraft/mc-mods/techreborn/files/2966851
https://www.curseforge.com/minecraft/mc-mods/reborncore/files/2966845

As a side note, the reason why it opens the GUI and closes it again is because Forge tries to regenerate the tile entity when you interact with the block, then deletes it when it crashes. The client is expecting that block to have a GUI, but then the server/client resync happens going "nope, that's just an unusually machine-looking stone block, stop trying to right click that thing that clearly doesn't have a tile entity" and the client goes "my bad" and closes the GUI again.

ADDENDUM: This does not seem to be a perfect fix as some of the centrifuge's recipes are not producing the correct outputs for me after updating. (It seems to be matching the first recipe with the right stack size of empty cells and ignoring their contents. For the most part, this is playable but you will need to cheat in tritium.)

**Comment by Alsososcar** [comment]
Thank you. Its now fixed :D

**Comment by rastrof** [comment]
> I encountered this exact issue. You can fix this issue by updating TechReborn (I updated to TechReborn-1.12.2-2.27.3.1084-universal) and RebornCore (I updated to RebornCore-1.12.2-3.19.4.529-universal).
> 
> https://www.curseforge.com/minecraft/mc-mods/techreborn/files/2966851
> https://www.curseforge.com/minecraft/mc-mods/reborncore/files/2966845
> 
> As a side note, the reason why it opens the GUI and closes it again is because Forge tries to regenerate the tile entity when you interact with the block, then deletes it when it crashes. The client is expecting that block to have a GUI, but then the server/client resync happens going "nope, that's just an unusually machine-looking stone block, stop trying to right click that thing that clearly doesn't have a tile entity" and the client goes "my bad" and closes the GUI again.
> 
> ADDENDUM: This does not seem to be a perfect fix as some of the centrifuge's recipes are not producing the correct outputs for me after updating. (It seems to be matching the first recipe with the right stack size of empty cells and ignoring their contents. For the most part, this is playable but you will need to cheat in tritium.)

You saved my world magerooster, awesome !. lets hope the FtbClient guuys fix the official release soon
