### ISSUE TITLE
[Request] Discord RP

### ISSUE THREAD

**Issue by HeyJack1** [FTBTeam/FTB-Sky-Odyssey#51]
Can you add some sort of DiscordRP like in stoneblock 2 
e.g. https://minecraft.curseforge.com/projects/minecraft-rich-presence

**Comment by Naxanria** [comment]
As its a clientside mod, you can just add it yourself and enjoy it :)

**Comment by modmuss50** [comment]
I dont think this will be added, like @Naxanria said you can just add it
