### ISSUE TITLE
Closing world when in Lan mode hangs the game.

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-Sky-Odyssey#52]
When closing a single player world that has been opened to Lan, it hangs the client.
There is no crash report or errors showing up at all when this happens.

Possibly related to https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/46

**Comment by Rushmead** [comment]
I've tested this and it seems to be caused by Xaero's minimap. Removing the mod seems to make it work perfectly fine for me. Waiting on @Naxanria to confirm.

**Comment by modmuss50** [comment]
This has been a bug in vanilla for a while, not sure on this.

**Comment by Rushmead** [comment]
I confirmed that this is not the case. The problem re-occured.

**Comment by TheOfficialButton** [comment]
This is a Vanilla issue and cannot be solved for the pack sadly.
