### ISSUE TITLE
Not being able to download off of twitch.

### ISSUE THREAD

**Issue by Zero757** [FTBTeam/FTB-Sky-Odyssey#53]
Anyone else not able to download Sky Odyssey off of Twitch, getting this every time
"Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip" whats doing this.

**Comment by Laiiiff** [comment]
Same issue from 10+ hours. So frustrating.

**Comment by DinnerBeef** [comment]
it works fine to me. What type of internet do you have?

**Comment by DinnerBeef** [comment]
yea so it does not show that it is downloading. but it is

**Comment by wendictive** [comment]
try start your twitch app in administrator mode

**Comment by modmuss50** [comment]
Support issue, if you still have issues go to twitch's support pages.
