### ISSUE TITLE
[Crash] Game Crash by shift click Legendary Phaser Rifle

### ISSUE THREAD

**Issue by Mack3sh** [FTBTeam/FTB-Sky-Odyssey#54]
Shift Clicking on a "Legendary Phaser Rifle" from MatterOverdrive: Legacy Edition will crash the client

[crash-2019-03-19_15.15.16-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2983776/crash-2019-03-19_15.15.16-client.txt)

**Comment by wendictive** [comment]
its a know bug with  MatterOverdrive ... sugest u delete that weapon

**Comment by TheOfficialButton** [comment]
This is a mod issue and has been reported to the mod dev.
