### ISSUE TITLE
Why is Ore Excavation gone?

### ISSUE THREAD

**Issue by ToastWithCheeze** [FTBTeam/FTB-Sky-Odyssey#540]
So i updated my game and i go in my server and i don't find in controlls that excavate is gone then i check mods and it's gone but in changelog they didn't say that Ore Excavation was removed

**Comment by Arrowpuppet** [comment]
The current mod for ore excavation in this pack is called FTB Ultimine. It is functionally identical to OE, with some additional shaped excavation options. Make sure you have the mode set to "shapeless" if you are trying to mine out veins of a certain block type.

**Comment by ToastWithCheeze** [comment]
Ok that's why 

i'm closing this issue
