### ISSUE TITLE
Saplings don't grow on ChosenArchitect island prefab

### ISSUE THREAD

**Issue by Yuval1Gutman** [FTBTeam/FTB-Sky-Odyssey#546]
* **Modpack Version**: 1.3.0

* **Issue**: Saplings don't grow on ChosenArchitect island prefab, even with bone meal, restarted the game many times, created a new world many times, but the saplings just don't grow.
I've tried to grow them in other worlds prefab and they work fine.
* **Is it Repeatable?**: Yes

**Comment by Naxanria** [comment]
You need to use them 2x2, so 4 in total.

**Comment by Yuval1Gutman** [comment]
> You need to use them 2x2, so 4 in total.

Thanks!
