### ISSUE TITLE
kinda infinite emc

### ISSUE THREAD

**Issue by llamanator07** [FTBTeam/FTB-Sky-Odyssey#548]
* **Modpack Version**: 1.12.2 (the one on twich)

* **Issue**: the quest book can be turned into practically infinite emc if you use any generator powering a coin generator, that is more than 120 emc per coin. kinda broken, especially in the early game.

* **Link to Log or Crash File Paste**: i did not crash
* **Is it Repeatable?**: yes

* **Mod/s Affected**: prodject e and ex and more

* **Known Fix**: iduno

**Comment by Naxanria** [comment]
There are many ways to get infinite emc :) It is intended.
