### ISSUE TITLE
Silicon Oredicts and Applied Energistic Presses recipes

### ISSUE THREAD

**Issue by TruckerTorpedo** [FTBTeam/FTB-Sky-Odyssey#55]
Modpack Version: 1.0.0 Singleplayer & Multiplayer

Issue: Trying to create Applied Energistic Inscriber presses. The only silicon usable is Ender IO silicon. or else you have to go into Mystical Agriculture. And Inscriber Silicon press works with all types of silicon when using Certus Quartz Essence.

Another thing to note, is that Certus Quartz and Gold is swapped in the recipes. Certus should be for Inscriber Calculation Press, and Gold for Inscriber Logic Press.

Link to Log or Crash File Paste:

Is it Repeatable?: Just look up Inscriber Presses in JEI, and you can see both issues.

Mod/s Affected: 

Known Fix: Change the recipes, and ordict Silicon in the recipes.

**Comment by wendictive** [comment]
just sagmill sand

**Comment by TruckerTorpedo** [comment]
I know how to go around it, thats not the issue.

**Comment by Slowpoke101** [comment]
Fixed in next release.
