### ISSUE TITLE
Multiplayer nether portal issue

### ISSUE THREAD

**Issue by bennyb1971** [FTBTeam/FTB-Sky-Odyssey#56]
I know this pack wasnt really meant for multiplayer play, but on servers nether portals sometimes get you to the portal of someone else. If the other has claimed a huge area around it that causes issues. This can be solved by adding Nether Portal Fix mod to the pack

**Comment by PebbleTwig** [comment]
Nether portal fix is already in the pack.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheOfficialButton** [comment]
Nether portal fix has been added to the pack
