### ISSUE TITLE
Problematic mods when trying to join a server

### ISSUE THREAD

**Issue by heat0** [FTBTeam/FTB-Sky-Odyssey#574]
* **1.3.0** 

* **When I try to log into me and my friends server, it says a bunch of different mods are outdated and some are above the version needed.** 

* Its not a crash, its more of im just not able to access my server. 
![image](https://user-images.githubusercontent.com/80774879/111341012-5a85b480-8636-11eb-9b10-5e0389c819de.png)
(friend is owner) 

* **Yes.** 

* **No known fix from me yet.**

**Comment by Quetzi** [comment]
You need to use the same pack and version of the pack on the client and the server. Your screenshot shows that most of the mods that you have on the server are not on the client at all, and those that are are newer on the client than the sever.
