### ISSUE TITLE
Can't use commands in singleplayer

### ISSUE THREAD

**Issue by Havoc1001** [FTBTeam/FTB-Sky-Odyssey#60]
When playing a single player normal forest map, i can't use commands like gamemode, weather, time...it says i don't have permission.

**Comment by DinnerBeef** [comment]
and why is this an issue?

**Comment by Havoc1001** [comment]
Why isn't this an issue. If something with the pack is blocking the use of
the commands from base Minecraft,  then yes it's an issue.

**Comment by nzminecraftDOTcom** [comment]
If it's single player, have you clicked Open To Lan - cheats on?

**Comment by DinnerBeef** [comment]
yea I would not do that to a bug. instead, I would add this mod https://minecraft.curseforge.com/projects/enable-cheats

**Comment by Havoc1001** [comment]
Yeah I figured it out I appreciate the help thank you
