### ISSUE TITLE
Java Access Violation Crash on Startup

### ISSUE THREAD

**Issue by drrk** [FTBTeam/FTB-Sky-Odyssey#62]
The pack was working fine last night, but when I tried to launch it today I am getting a crash with an Access violation in the logs. 

I have tried deleting and reistalling the pack with the Twitch Launcher.

Full output from Launcher here: https://gist.github.com/drrk/be5755317e70e996b99c20810c5f90a6

**Comment by drrk** [comment]
Launches fine with Legacy FTB Launcher.

**Comment by tahg** [comment]
Please post the .log file referenced in that gist.

**Comment by drrk** [comment]
[hs_err_pid25220.log](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2984896/hs_err_pid25220.log)

Attached.

**Comment by Slowpoke101** [comment]
Can you try restarting your PC and letting me know if you are still getting this crash?

**Comment by drrk** [comment]
I can, but it won't be until after around Midnight tonight (GMT) as I am
out at a work function tonight.

**Comment by drrk** [comment]
Today it works fine.  (I shutdown my laptop every night.)  I am sorry for the annoying heisenbug.

**Comment by Slowpoke101** [comment]
No that's absolutely perfect. We just wanted to make sure that this was the error we though it was.

**Comment by drrk** [comment]
> No that's absolutely perfect. We just wanted to make sure that this was the error we though it was.

Did you change something that fixed it then?  I'm intrigued now.

**Comment by drrk** [comment]
Booted up my machine and loaded the pack today, and the error is back, will see what happens after a reboot.

**Comment by drrk** [comment]
And a reboot fixed it, am I going to have to go through this every time?
