### ISSUE TITLE
issue with ahkasic tome  

### ISSUE THREAD

**Issue by mattbat13** [FTBTeam/FTB-Sky-Odyssey#63]
when i was fooling around with the modpack i found you can make a ahkasic tome the tome that is all the books in one  ,  found out if you  put a dirt block in the crafting grid and you get one  is these.  is this  a error or issue or what is it .

**Comment by PebbleTwig** [comment]
That is intentional to my knowledge

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mattbat13** [comment]
oh ok i didn't know

**Comment by TheOfficialButton** [comment]
This is intended. It is aimed to be an easy option for help for anyone who gets stuck.
