### ISSUE TITLE
Nuclear reactor

### ISSUE THREAD

**Issue by Cheesballs** [FTBTeam/FTB-Sky-Odyssey#64]
When you destroy the nuclear reactor block it gives you a generator instead of the nuclear reactor block again.

**Comment by DinnerBeef** [comment]
I would assume this is and ic2 nuclear reactor. If so you have to use a wrench to break the block and get it back

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheOfficialButton** [comment]
This is an intended feature for the mod. Using a wrench to pick it up will stop the block being destroyed.
