### ISSUE TITLE
missing Recources on Chosen Architect's island

### ISSUE THREAD

**Issue by Philipp766** [FTBTeam/FTB-Sky-Odyssey#65]
There is no earlygame way on the Chosen Island to get gravel. You have to get into Extra utils and power to obtain your first gravel. The same thing with water and Lava. For water you need industrial foregoing and for Lava the same.

**Comment by DinnerBeef** [comment]
use the Philosophers Stone on sandstone

**Comment by bloodbound121** [comment]
What about lava? there is no way to get lava without obsidian and that is unattainable.

**Comment by Philipp766** [comment]
that's why I opened this thread, to highlight this problems

**Comment by bloodbound121** [comment]
found solution 1500 coins and the shop under baubles

**Comment by Philipp766** [comment]
yea, but i think this is more an workaround than an fix. the same thing with gravel, sand and water. i think this things should be added to the chest. on top of that the jei search bar and cheat mode should be disabled.

**Comment by Firefox37** [comment]
just use the default island then and build your own version of chosen architects island. its meant to be a finalized base not a starting island, kind of a challenge.

**Comment by Philipp766** [comment]
thank you for the good answers. i think I can close this issue.

**Comment by ThePoet444** [comment]
Water = Aqueous accumulator. It's slow but eventually you get a bucket. The vulcan amulet in the store has a recipe with a bucket and I think redstone in a crafting table to get a lava bucket. Sand I got a chicken, Flint I got a chicken, and gravel I got with a pulverizer (which was a moot point by then). I then got obsidian by 2 water buckets and 2 lava buckets in a crafting grid.  This was all on Chosen's island.

**Comment by Naxanria** [comment]
It is not a work around to use shop items. It is intended, it is what the shop is for :)
Gravel can be made with philo stone, or the crusher from Extra Util.

All islands are complete-able.

**Comment by hron84** [comment]
If anyone struggling with lava, Magma crucible is able to produce lava from cobblestone, netherrack can be obtained via Philosopher stone +gravel and gravel is obtainable by completing a crusher quest (pulverizer, macerator and crusher are able to produce gravel).
