### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by stearnsbq** [FTBTeam/FTB-Sky-Odyssey#66]
Crafting Project x collectors / relays complete the final version quests.

Reduce the emc value of grains of infinity, each cost 50 beast coin and each grain is 16k emc it should be reduced to a cheaper amount as you can get a few million emc right off the bat in the game

EDIT: I will be updating this as I progress

**Comment by dsabecky** [comment]
I would say increase the beast coin cost to 1,000 to match "top" ores (emerald, diamond), vice reducing EMC.

**Comment by stearnsbq** [comment]
I would just reduce the emc value to the price of iron or redstone.

**Comment by dsabecky** [comment]
> EDIT: I will be updating this as I progress

Make sure to open new issues for separate issues for tracking purposes. ♥

**Comment by Naxanria** [comment]
Grains having that amount of emc, while maybe a bit silly. It doenst matter at all in this pack.
Collectors Relays has already an issue https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/41
And yes, open new issues for separate issues, as its easier to track, less likely for duplicated isssues.

**Comment by stearnsbq** [comment]
> Grains having that amount of emc, while maybe a bit silly. It doenst matter at all in this pack.
> Collectors Relays has already an issue #41
> And yes, open new issues for separate issues, as its easier to track, less likely for duplicated isssues.

Fair enough, A big point of this pack is making exponential amounts of emc in a short amount of time but I felt like it really made the early game nonexistent(Personally I hate the early game in mod packs), but I mainly made this issue for people that prefer the early game. I will make new Issues if I find anymore bugs while playing. Thanks

**Comment by Slowpoke101** [comment]
Thanks for the suggestions
