### ISSUE TITLE
Thaumcraft 6 lava doesn't work

### ISSUE THREAD

**Issue by KaraNoelle** [FTBTeam/FTB-Sky-Odyssey#71]
I looked into the issue of creating a bucket of lava as Chosen's island doesn't have any in it. Apparently Thaumcraft can create it but there's a bug where it doesn't allow you to create it properly and it just adds the bucket to the pot instead of creating the bucket of lava. This was apparently a known bug about 9 months ago found [here](https://www.reddit.com/r/Thaumcraft/comments/8q356v/cant_produce_lava_in_thaumcraft_6/).

It appears that this bug is still present. If at all possible, remove the recipe from the list or something so people aren't going to run into this issue.

**Comment by toolongtospell** [comment]
There's an item in the shop that spawns lava.

**Comment by Slowpoke101** [comment]
Before you can make a lava bucket, you must first progress through Thaumcraft research up till Hedge Alchemy. I have just confirmed this recipe is working in dev.
