### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by ryry3003** [FTBTeam/FTB-Sky-Odyssey#74]
So I was in the nether trying to get wither skeletons to spawn (not sure if thats the way to do it but thats how i was) and I was fighting a horde of pigmen. I was pushed off the edge and died,when i respawned I bought some more quantum armor, flew down and grabed my stone, kept fighting. At one point I went to go pick up items and was hit by a pigman, and then my game froze and crashed. The Crash log is below.
[crash-2019-03-19_15.40.46-server.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2985834/crash-2019-03-19_15.40.46-server.txt)

**Comment by wendictive** [comment]
you need to be ontop of a fortress for wither skellies to spawn

**Comment by wendictive** [comment]
its the matter overdrive weapon ... known bug ... delete the weapons and all should be fine

**Comment by TheOfficialButton** [comment]
Matter Overdrive weapons can cause issues sometimes. This has been reported to the mod dev and will hopefully be fixed in the future.
