### ISSUE TITLE
Joning Team overwrites said teams island.

### ISSUE THREAD

**Issue by OldDogy** [FTBTeam/FTB-Sky-Odyssey#75]
I requested an invite to my friends team , and when he accepted (invited me) Instantly a screen popped out for me asking me what type of island do I want.
There was no way for me to quit that menu , and when i made a choice Both him and I were teleported to the origin point of his island, and that area was regenerated. 

I know that after getting an invite I should only get teleported to his island instead of regenerating a new island over his .

**Comment by Rushmead** [comment]
@LatvianModder 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dsabecky** [comment]
@OldDogy Out of curiousity, (if they did /sethome), are they able to go back to their base? Asking to see if it overwrites it or teleports both of you to a new area.

**Comment by LatvianModder** [comment]
You can go back to your old /home but the area is unclaimed and if you die you will respawn at new one

**Comment by OldDogy** [comment]
Me joining his team overwrote his island . We both got teleported to his area .
