### ISSUE TITLE
Creative Energy Cell from AE2

### ISSUE THREAD

**Issue by joshrath** [FTBTeam/FTB-Sky-Odyssey#76]
I've reached the point of buying the Creative Energy Cell from AE2 and did indeed spend 150,000 beast coin on it. However, conduit nor flux plug is receiving any power from this item. Am I missing something or is the block malfunctioning?

**Comment by dsabecky** [comment]
The Applied Energistics energy cell is meant to power Applied Energistics machines only. It doesn't produce RF, but AE. There's a reason it's 350,000 cheaper than the other creative power cell.

**Comment by joshrath** [comment]
Yes, however Flux Networks are compatible with AE power. If this has been disabled, and it is truely only for AE machines in this pack, I guess it may be time to edit my files and restore my 150K beast coin that was a waste. And possibly add a note about that in the shop.

**Comment by TheOfficialButton** [comment]
This block is intended to only be used with AE and nothing else. Save up for the creative energy cell. That will give you all the RF you need :)
