### ISSUE TITLE
Woot Controller Quest not completing

### ISSUE THREAD

**Issue by 2013emi** [FTBTeam/FTB-Sky-Odyssey#78]
Created a Controller from Woot for the quest. However it won't submit. I made several with different mobs and none of them would complete the quest.

**Comment by Slowpoke101** [comment]
Thanks, this is now fixed in dev.

**Comment by 2013emi** [comment]
Just noticed but it seems the Stabilized Spawner quest has the same issue.

**Comment by Neuclerium** [comment]
Not sure if it was posted but the Stabilized Mob Spawner quest has the same problem.
