### ISSUE TITLE
[Bug] Hardened Signalum Glass

### ISSUE THREAD

**Issue by dsabecky** [FTBTeam/FTB-Sky-Odyssey#79]
The following recipe does not work with any Fused Quartz.

![image](https://user-images.githubusercontent.com/778367/54651794-c30f1a80-4a8a-11e9-8b62-cd17f378cecf.png)

**Comment by dsabecky** [comment]
The crafting table recipe does not work either.
![image](https://user-images.githubusercontent.com/778367/54651897-2305c100-4a8b-11e9-841c-33941efc87ad.png)

**Comment by Naxanria** [comment]
Confirmed, Thermal Expansion induction smelter does not seem to respect the oredict.

**Comment by LocalBoomer** [comment]
Is this for all the TE Hardened glass types or just signalum hardened glass?

**Comment by dsabecky** [comment]
@Chupp4-Jo3 The induction smelter recipe does not work period. Crafting table recipe works only with white hardened.

**Comment by LocalBoomer** [comment]
@dsabecky I meant is the issue of using Fused Quartz with a metal dust to make TE Hardened Glass not working for all different TE Hardened Glass Recipes or just Signalum Hardened Glass?

**Comment by martingolding96** [comment]
Both recipes work on 1.1.0
