### ISSUE TITLE
[Request] Deep Mob Learning Guide Book

### ISSUE THREAD

**Issue by SomeRandomPetey** [FTBTeam/FTB-Sky-Odyssey#80]
Deep Mob Learning adds a guide book, however this guide book requires Patchouli, which is not currently in the pack. Plus, the mod lacks pretty much any other documentation besides the guide book.

**Comment by CastielAngelow** [comment]
I mean, isn't this enough information you need to be honest? That mod is not that extremely "hard". :)
https://minecraft.curseforge.com/projects/deep-mob-learning

**Comment by Jake-E** [comment]
This is down to @Slowpoke101 to decide if he wants to add Patchouli in just for this mods guidebook.

**Comment by Slowpoke101** [comment]
Thanks for letting me know, this is now fixed in dev.
