### ISSUE TITLE
[BUG] Stone Spikes Recipe not available due to missing compressed cobble

### ISSUE THREAD

**Issue by piisawheel** [FTBTeam/FTB-Sky-Odyssey#81]
There's no compressed cobble, therefore, you cannot make the stone spikes recipe in this pack.  i recommend changing the recipe to smooth stone or something else if ex compressum isn't going in this pack.

**Comment by Naxanria** [comment]
There are other options for mob killing (See Mob Grinding quest tab).
Ex Compressum will not be in the pack.

**Comment by piisawheel** [comment]
I am aware of this, however, it is confusing to punch in JEI and see recipes for the _other_ spikes that _do_ work.  I assume if we can't build it, we shouldn't see it, unless it's just too much time and effort to remove broken recipes from the pack.  Early game stone spikes keep spiders off the roof of my mob trap... something I cannot do with wooden spikes and something _very_ expensive to do in iron spikes.  It just seems like you left a hole in early game mob farms.  I guess having 1 broken recipe in a list of related items just bothers my OCD. As a programmer, I would classify this as a bug because you have intended functionality that is not accessible.

**Comment by TheOfficialButton** [comment]
There are many other solutions to stopping mobs spawning on your roof of your mob farm (slabs). This is a minor issue that we can fix in the future but I would suggest slabs for stopping spawns

**Comment by piisawheel** [comment]
I meant I like to stick them on the walls to keep spiders from climbing and huddling in the ceiling corner away from my vector plates and other damage.  It is a minor issue, but being a programmer, I diligently report all issues in software I like to use frequently.  All in all a very solid pack.

**Comment by Slowpoke101** [comment]
fixed in dev.
