### ISSUE TITLE
Quest issue: Ore Doubling

### ISSUE THREAD

**Issue by bestxp** [FTBTeam/FTB-Sky-Odyssey#83]
Add to valid items Crusher from Actually Additions mod, thx

**Comment by Naxanria** [comment]
![image](https://user-images.githubusercontent.com/3246224/54662701-1dd26180-4adf-11e9-83a1-ce7f866e0acd.png)

It is.

**Comment by TheOfficialButton** [comment]
The Crusher is already an option for completing the quest.

**Comment by LatvianModder** [comment]
I added that in server, not been actually fixed

**Comment by Slowpoke101** [comment]
Thanks, this is now fixed in dev.
