### ISSUE TITLE
Will Not Install

### ISSUE THREAD

**Issue by mammothmau5** [FTBTeam/FTB-Sky-Odyssey#86]
I have never had a problem installing mod packs before it is just this specific pack i try downloading  it and every time it says ( Timeout attempting to download: https://files.forgecdn.net/files/2688/902/FTBSkyOdyssey-1.0.0-1.12.2.zip )

**Comment by CastielAngelow** [comment]
Are you sure it is not case of overloaded servers? If so, make sure to wait approx. 10 - 20 minutes and try it again before posting an issue. It happened to me too before on another pack. Unaccessible file. Sometimes, it can happen. Try it now, does issue still persist?

**Comment by mammothmau5** [comment]
Yes it does

**Comment by CastielAngelow** [comment]
Lets be clear here, dude. Link you are giving is not even official link lul. Maybe wanna try to download from here: https://www.feed-the-beast.com/projects/ftb-sky-odyssey/files/2688902 and install profile manually and/or look for your trusted domains on broswer. It might get blocked ;)

**Comment by Jake-E** [comment]
@CastielAngelow Link is completely valid. It's the curseforge CDN download link.

We are looking to remove the animation files to make the downloading/extracting process much easier.
