### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by PikachuMC99** [FTBTeam/FTB-Sky-Odyssey#87]
Every time I launch the pack with optifine added to my mods folder the game crashes right as I hit play and I get "An unexpected issue has occurred and the game has crashed. We're sorry for the inconvenience." yet it's fine when I remove optifine. I was wondering why this is happening and how I can play with optifine.

**Comment by CastielAngelow** [comment]
If there is mod that using some custom rendering or apply some patches to Minecraft base classes ( coremod ) it does not have to go extremely well or even be compatible. No mods do native "compatibility" with Optifine as its close-sourced and is not hosted on Curse, therefore there is no real "troubleshoot" anyone can give you and will be right. But for sake of good, post here your Console Log.
One you can get when you go into your logs folder or when you allow in launcher settings "Show console at start of a game". Then come back, might help you more :)

**Comment by wendictive** [comment]
dont use optifine

**Comment by Jake-E** [comment]
Adding optifine is a user decision, the impacts it has on the pack are not our fault.
