### ISSUE TITLE
The Pizza Recipie contains all items that have EMC but Pizza Doesnt have EMC value ( Also for most of Actually Additions ITems)

### ISSUE THREAD

**Issue by SweetestPumpkin** [FTBTeam/FTB-Sky-Odyssey#88]
The Pizza Recipie contains all items that have EMC but Pizza Doesnt have EMC value ( Also for most of Actually Additions ITems)

**Comment by TheOfficialButton** [comment]
This is something that you will need to Auto craft if you want to mass produce them.
