### ISSUE TITLE
Copper Chicken

### ISSUE THREAD

**Issue by Rethgual** [FTBTeam/FTB-Sky-Odyssey#89]
Able to cross breed to get the copper chicken normally or by using the custom recipe.

**Comment by Naxanria** [comment]
Copper chicken can be bred, not sure what your issue is?

**Comment by Rethgual** [comment]
I thought it was suppose to be set to the custom recipe and the cross breeding turned off for that particular chicken.

**Comment by wendictive** [comment]
cross breading is allowerd for all ores that spawn naturally in the world ...such as copper why its allso craftable i donno ill mention this to slow

**Comment by Rethgual** [comment]
Got ya, thank you Wendi and Nax.
