### ISSUE TITLE
EMC Flowers while offline

### ISSUE THREAD

**Issue by cf-Botan** [FTBTeam/FTB-Sky-Odyssey#90]
I've just uploaded SMP World to an Server and continued playing. Then I went off for about 9 Hours. As I entered my server is saw that the chunk loading worked like it should. But  sure enough the EMC value was still at about 20 million. I thought ist should be more with two MK7 Flowers.
So is this normal or is my world just broken ?

**Comment by Naxanria** [comment]
Reported to mod author.

**Comment by TheOfficialButton** [comment]
This is a mod issue and has been reported. ^
