### ISSUE TITLE
Task Screen

### ISSUE THREAD

**Issue by TheError007** [FTBTeam/FTB-Sky-Odyssey#91]
Hello, I've crafted Task screen to finish some of the quests that require liquids like Resonant Ender, etc, however after placing the task screen, I am unable to Shift-right click it.
Tried to recreate this bug in another world, however when i crafted the Task Screen there, i was able to Shift-Rightclick it.

Also I have noticed that the world where I can't connect the Screen to quest, team name on the item is Green.
In the testing world, the team name is Purple.

Is there any way to fix it?

Also i know that i can't do it by buckets, but it takes too long to do that.

**Comment by DinnerBeef** [comment]
did you try an use a new screen? 
the color you are seeing is your team color btw.

**Comment by TheError007** [comment]
Yeah, tried to Craft a new one, one from Transmutation table, even one from creative mode didnt helped.

**Comment by Slowpoke101** [comment]
Were you able to resolve this, its something that may be difficult to diagnose what is going wrong.

**Comment by TheError007** [comment]
Apparently it was some kind of rare bug, because yesterday, the bug was still there even after restaring the game few times, however today, I tried to re-use the screen, at everything was working just fine.

Will update/create new post if this happends again.

**Comment by applemes** [comment]
Ive never been able to shift-click it? I have been trying for like the past 2 hours to do the liquid quests/repeatable quest and i just cant get the task screen working. Is there a keybind that I could have maybe changed accidently, or something to be able to configure it

**Comment by TheError007** [comment]
Well, i wasnt able to shift-click it either, however the next day it worked completly fine, don't know what's the issue

**Comment by applemes** [comment]
Mine is now working, and I think I know why it wasn't. I'm pretty sure it was because I had food in my offhand the whole time, and taking it out lets me use it now.

**Comment by TheError007** [comment]
Hmm, that could be the thing, having food in offhand, however, I'll check that.

**Comment by TheError007** [comment]
So its confirmed, the task screen won't open if you have food, or anything in your off-hand.
