### ISSUE TITLE
Change the ae press recipe 

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-Sky-Odyssey#92]
make the silicon not just ender io make it ore dict.

Lines 336-363 (RecipeChanges.zs).

**Comment by DinnerBeef** [comment]
do a replace all for <enderio:item_material:5> to whatever the ore dict silicon

**Comment by PebbleTwig** [comment]
Same as issue #55.

**Comment by Slowpoke101** [comment]
Fixed in dev.
