### ISSUE TITLE
Game Crashes While Loading

### ISSUE THREAD

**Issue by CuddlesMcRawr** [FTBTeam/FTB-Sky-Odyssey#94]
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)"

The above error code appears when trying to load the game. Attached is the crash report.

[crash-2019-03-20_14.12.46-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2988595/crash-2019-03-20_14.12.46-client.txt)

**Comment by Jake-E** [comment]
Try re-installing the pack, this seems like the configs haven't downloaded properly for you.

**Comment by CuddlesMcRawr** [comment]
Ive tried "Repair profile". I'll try deleting then reinstalling then reply back.

**Comment by Knoxxar** [comment]
Update your Java Version plz, 1.8.0_51 is really old ....

**Comment by CuddlesMcRawr** [comment]
Tried reinstalling, now crashing for a different reason:
"The game crashed whilst initializing game
The game crashed whilst initializing game
Error: SplashProgress has detected a error loading Minecraft."

[crash-2019-03-20_15.43.47-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2988999/crash-2019-03-20_15.43.47-client.txt)

**Comment by Knoxxar** [comment]
try to update your java
https://www.java.com

**Comment by Slowpoke101** [comment]
Is this still an issue for you?

**Comment by CuddlesMcRawr** [comment]
No, but I did lose my world from it :/

**Comment by CrummyPaper80** [comment]
My game is crashing when i launch it. I've already deleted it and reinstalled it and I've tried other things in this thread. I'll leave a link to the crash report. What should i do?
[crash-2019-03-23_12.20.26-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2999596/crash-2019-03-23_12.20.26-client.txt)


The game crashed whilst initializing game
The game crashed whilst initializing game
Error: net.minecraft.client.renderer.StitcherException: Unable to fit: extracells:blocks/walrus2 - size: 925x925 - Maybe try a lowerresolution resourcepack?

**Comment by Knoxxar** [comment]
Plz update your System, is not to heavy to keep it up to date. Your java is 150 Versions behind the actually.

**Comment by Dorian-X** [comment]
Help! Ive tried uninstalling and reinstalling the modpack, and Ive updated java, and Ive changed the amount of ram to 4G, but it still wont load. 
[crash-2019-10-30_03.27.25-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3787426/crash-2019-10-30_03.27.25-client.txt)
