### ISSUE TITLE
Cant use EMC Tablet

### ISSUE THREAD

**Issue by applemes** [FTBTeam/FTB-Sky-Odyssey#95]
After my EMC gets up to about 10.00E (10,000,000,000,000,000,000), it wont let me add any of my EMC items into my tablet, but I can put them in a box, that is putting items into my personal EMC link, it just seems I can't manually add them to tablet, or to the table. I can even manually add them to the link.

**Comment by TheOfficialButton** [comment]
This is a Java issue as it can only read numbers up to 9.4 quintillion. If you want to add things to you tablet you cannot burn them. Instead, you have to put them in the middle on the right side of the tablet to learn them that way. To fix this the entire game would need to be re-written in a different coding language. So sadly that is the only solution for using the tablet manually.
