### ISSUE TITLE
The Final Collector

### ISSUE THREAD

**Issue by Knoxxar** [FTBTeam/FTB-Sky-Odyssey#97]
The Final Collector should mine 1.00T/s but with normal build (EMC Link, Relay above and 5 Final Collecter around), 5 Collector = 5.00T/s but it produces 10.00T/s, can you look at this? I mean its an bug.

**Comment by Jake-E** [comment]
The relay provides a 1.00T/s bonus, this could be stacking per collector? @LatvianModder

**Comment by Knoxxar** [comment]
i think, it should be only 1 Bonus for one Relay not for every collector or i mixed something in my brain,

**Comment by LatvianModder** [comment]
No, its correct. Collector gives bonus to every relay and that's how it's always been
