### ISSUE TITLE
Quest Chest accepts from Fluidtransposer without consuming item.

### ISSUE THREAD

**Issue by kaspermwh** [FTBTeam/FTB-Sky-Odyssey#98]
Fluid transposer is set to empty and ejecting directly into the Quest Chest. Counts as a turn in, but neither the bucket or the oil is consumed.
[Imgur link](https://imgur.com/a/mqhfDKE)

**Comment by Jake-E** [comment]
This may be a @LatvianModder issue - not sure if fixed in new builds?
