### ISSUE TITLE
Game Crashes when loading world

### ISSUE THREAD

**Issue by iBrianRS** [FTBTeam/FTB-Sky-Odyssey#99]
it crashes mid world-load, i played yesterday with no crashes

error message:
The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)

**Comment by Jake-E** [comment]
Can you provide your full client log on pastebin or something?

**Comment by iBrianRS** [comment]
it happens at the loading world - building terrain section

Crash log : https://pastebin.com/fNwmtnhV

**Comment by Naxanria** [comment]
That looks like the minetogether config is incorrect/corrupt.

**Comment by Jake-E** [comment]
This has been fixed in the dev version of MineTogether. Once released we will push it with an update.
